import type { RailPass } from './types';

export const RAIL_PASSES: RailPass[] = [
  {
    slug: 'usa-rail-pass',
    name: 'USA Rail Pass',
    operator: 'Amtrak',
    country: 'US',
    price: 'from $499',
    validity: '10 segments within 30 days',
    coverage: 'Coach seats on almost every Amtrak route nationwide (Acela, Auto Train and sleepers excluded; upgrades payable).',
    bestFor: 'Multi-city US itineraries — e.g. New York → Chicago → Denver → San Francisco → Los Angeles on one pass.',
    howToBuy: 'Sold by Amtrak with occasional flash sales; our rail desk plans segment-efficient routings and books each leg.',
    available: true,
  },
  {
    slug: 'california-rail-pass',
    name: 'California Rail Pass',
    operator: 'Amtrak California',
    country: 'US',
    price: 'from $159',
    validity: '7 travel days within 21 days',
    coverage: 'Pacific Surfliner, Capitol Corridor, San Joaquins and connecting thruway buses across California.',
    bestFor: 'Coastal + valley loops: San Diego, LA, Santa Barbara, Bay Area, Sacramento and Yosemite gateway towns.',
    howToBuy: 'Bookable through Amtrak California channels; we build the day-by-day plan around validity rules.',
    available: true,
  },
  {
    slug: 'brightline-passes',
    name: 'Brightline Commuter & Trip Passes',
    operator: 'Brightline',
    country: 'US',
    price: 'from $399/mo',
    validity: 'Monthly unlimited or 10/20/40-ride packs',
    coverage: 'All Brightline stations Miami–West Palm Beach; Orlando add-ons priced separately.',
    bestFor: 'South Florida commuters and frequent Miami↔Orlando travellers.',
    howToBuy: 'Sold via the Brightline app; we advise on the break-even math vs single fares.',
    available: true,
  },
  {
    slug: 'irctc-circular-journey',
    name: 'Indian Railways Circular Journey Tickets',
    operator: 'Indian Railways',
    country: 'IN',
    price: 'Distance-based (telescopic fares)',
    validity: 'Up to 56 days, max 8 break points',
    coverage: 'Any self-planned circular route on Indian Railways, in any class — fares telescope so long loops cost far less than separate tickets.',
    bestFor: 'Grand tours like Delhi → Jaipur → Mumbai → Goa → Bengaluru → Chennai → Kolkata → Delhi.',
    howToBuy: 'Applied for through zonal railway offices — paperwork our rail desk handles end to end.',
    available: true,
  },
  {
    slug: 'eurail-global-pass',
    name: 'Eurail Global Pass',
    operator: 'Eurail (33 European countries)',
    country: 'GLOBAL',
    price: 'from €194',
    validity: '4 travel days to 3 months',
    coverage: 'National railways across 33 European countries — relevant for US/India travellers heading to Europe next.',
    bestFor: 'Multi-country European trips; pairs with our flight and visa desks for a complete itinerary.',
    howToBuy: 'We issue Eurail passes and seat reservations as part of Europe itineraries.',
    available: true,
  },
  {
    slug: 'japan-rail-pass',
    name: 'Japan Rail Pass',
    operator: 'JR Group',
    country: 'GLOBAL',
    price: 'from ¥50,000',
    validity: '7 / 14 / 21 consecutive days',
    coverage: 'JR trains nationwide including most Shinkansen — for the Japan leg of round-the-world itineraries.',
    bestFor: 'First-time Japan visitors covering Tokyo, Kyoto, Osaka and Hiroshima.',
    howToBuy: 'Purchasable before travel through authorised agents — ask our rail desk.',
    available: true,
  },
];

export function passBySlug(slug: string): RailPass | undefined {
  return RAIL_PASSES.find((p) => p.slug === slug);
}
