import type { AgeBand, CoverageDetail, InsurancePlan } from './types';

/**
 * Curated plan catalog — coverage profiles compiled from insurers' publicly
 * available brochures and typical market structures, normalised into one
 * comparable shape. Figures are indicative and admin-correctable via
 * /admin/insurance (InsurancePlanOverride); the insurer's issued policy
 * wording is always the binding source. Premium base rates are OUR estimate
 * model inputs, not insurer tariffs — every quote is labelled an estimate.
 */

const INR_PER_USD = 85;

function money(n: number, currency: 'USD' | 'INR' = 'USD'): string {
  if (currency === 'INR') return `₹${n.toLocaleString('en-IN')}`;
  return `$${n.toLocaleString('en-US')}`;
}

/** USD benefit. */
const usd = (n: number, note?: string): CoverageDetail => ({ label: money(n), approxUsd: n, ...(note ? { note } : {}) });
/** INR benefit with USD normalisation for sorting. */
const inr = (n: number, note?: string): CoverageDetail => ({ label: money(n, 'INR'), approxUsd: Math.round(n / INR_PER_USD), ...(note ? { note } : {}) });
/** Non-amount benefit ("Included", "100% of trip cost"…). */
const incl = (label: string, approxUsd = 0, note?: string): CoverageDetail => ({ label, approxUsd, ...(note ? { note } : {}) });
const addOn = (d: CoverageDetail): CoverageDetail => ({ ...d, addOn: true });

/** Flat rate helper for age-band tables. */
const bands = (r: [number, number, number, number, number, number, number]): Record<AgeBand, number> => ({
  '0-17': r[0], '18-35': r[1], '36-50': r[2], '51-60': r[3], '61-70': r[4], '71-80': r[5], '81+': r[6],
});

const COMMON_EXCLUSIONS = [
  'Pre-existing medical conditions, unless the plan states otherwise or a waiver applies',
  'Travelling against medical advice or to obtain planned/elective treatment (unless a medical-travel cover is bought)',
  'Injuries from alcohol/drug influence, self-harm, or criminal acts',
  'War, invasion, and active participation in civil unrest',
  'Professional or competitive sports; extreme activities not on the plan’s covered list',
  'Baggage left unattended in a public place; undeclared valuables above per-item limits',
  'Losses recoverable from airlines, hotels, or other insurance first (most benefits pay secondary)',
];

const US_CLAIM_PROCESS =
  'File online with the insurer (receipts, proof of loss, medical reports). Emergencies: call the 24×7 assistance line first — they direct you to network care and arrange evacuations. Most document-complete claims are decided in 5–15 business days.';
const IN_CLAIM_PROCESS =
  'Call the insurer’s assistance line before or at hospital admission for cashless treatment abroad where the network allows; otherwise pay, keep every bill/report, and file for reimbursement online within the policy’s notification window (usually 30 days of return).';
const VISITOR_CLAIM_PROCESS =
  'Show your insurance ID at network hospitals for direct billing where available; otherwise file through the member portal with itemised bills. Always call the assistance line for admissions — unapproved non-emergency admissions can reduce benefits.';

export const INSURANCE_PLANS: InsurancePlan[] = [
  // ================= US MARKET =================
  {
    id: 'allianz-onetrip-basic',
    slug: 'allianz-onetrip-basic',
    providerId: 'allianz',
    name: 'Allianz OneTrip Basic',
    tagline: 'Entry-level trip protection covering the essentials at the lowest cost.',
    market: 'US',
    currency: 'USD',
    categories: ['single_trip', 'family'],
    regions: ['worldwide'],
    eligibility: { minAge: 0, maxAge: 99, maxTripDays: 90 },
    medicalSumInsuredUsd: 10_000,
    medicalSumInsuredLabel: '$10,000',
    deductibleLabel: '$0 deductible',
    coverage: {
      emergency_medical: usd(10_000),
      medical_evacuation: usd(50_000),
      trip_cancellation: incl('100% of insured trip cost', 10_000),
      trip_interruption: incl('100% of insured trip cost', 10_000),
      trip_delay: usd(300, '$150/day after 6h delay'),
      baggage_loss: usd(500),
      baggage_delay: usd(200),
      covid_medical: incl('Covered as any illness (Epidemic Coverage Endorsement)'),
      telemedicine: incl('Included via Allyz TravelSmart'),
    },
    highlights: ['Cheapest way to protect a modest prepaid trip', 'Kids’ rates discounted', 'Epidemic coverage endorsement included'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: US_CLAIM_PROCESS,
    pricingModel: 'trip_cost',
    baseRates: bands([0.035, 0.042, 0.048, 0.058, 0.075, 0.10, 0.13]),
    minPremium: 25,
    bestFor: ['Short domestic & international trips with low prepaid costs', 'Budget-focused travellers'],
  },
  {
    id: 'allianz-onetrip-prime',
    slug: 'allianz-onetrip-prime',
    providerId: 'allianz',
    name: 'Allianz OneTrip Prime',
    tagline: 'Allianz’s most popular plan — solid limits plus free cover for kids 17 and under.',
    market: 'US',
    currency: 'USD',
    categories: ['single_trip', 'family', 'cruise'],
    regions: ['worldwide'],
    eligibility: { minAge: 0, maxAge: 99, maxTripDays: 180 },
    medicalSumInsuredUsd: 25_000,
    medicalSumInsuredLabel: '$25,000',
    deductibleLabel: '$0 deductible',
    coverage: {
      emergency_medical: usd(25_000),
      medical_evacuation: usd(500_000),
      trip_cancellation: incl('100% of insured trip cost', 25_000),
      trip_interruption: incl('150% of insured trip cost', 37_500),
      trip_delay: usd(800, '$200/day after 6h'),
      missed_connection: usd(800),
      baggage_loss: usd(1_000),
      baggage_delay: usd(300),
      covid_medical: incl('Covered as any illness (Epidemic Coverage Endorsement)'),
      pre_existing_conditions: incl('Waiver if bought within 14 days of first trip payment'),
      telemedicine: incl('Included'),
    },
    highlights: ['Children 17 and under covered free with a parent', 'Pre-existing condition waiver window', 'Strong evacuation limit for cruises'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: US_CLAIM_PROCESS,
    pricingModel: 'trip_cost',
    baseRates: bands([0.0, 0.052, 0.058, 0.07, 0.088, 0.115, 0.145]),
    minPremium: 39,
    bestFor: ['Families (kids free)', 'Cruises and package holidays', 'Most US leisure travellers'],
  },
  {
    id: 'allianz-onetrip-premier',
    slug: 'allianz-onetrip-premier',
    providerId: 'allianz',
    name: 'Allianz OneTrip Premier',
    tagline: 'Top-tier limits — double Prime’s medical and $1M evacuation.',
    market: 'US',
    currency: 'USD',
    categories: ['single_trip', 'cruise', 'business', 'family'],
    regions: ['worldwide'],
    eligibility: { minAge: 0, maxAge: 99, maxTripDays: 180 },
    medicalSumInsuredUsd: 50_000,
    medicalSumInsuredLabel: '$50,000',
    deductibleLabel: '$0 deductible',
    coverage: {
      emergency_medical: usd(50_000),
      medical_evacuation: usd(1_000_000),
      trip_cancellation: incl('100% of insured trip cost', 50_000),
      trip_interruption: incl('160% of insured trip cost', 80_000),
      trip_delay: usd(1_600, '$200/day'),
      missed_connection: usd(1_600),
      baggage_loss: usd(2_000),
      baggage_delay: usd(600),
      rental_car_excess: addOn(usd(50_000, 'Optional Rental Car Damage Protector')),
      covid_medical: incl('Covered as any illness (Epidemic Coverage Endorsement)'),
      pre_existing_conditions: incl('Waiver if bought within 14 days of first trip payment'),
      telemedicine: incl('Included'),
    },
    highlights: ['$1M emergency evacuation', 'Kids 17 and under free', 'Highest Allianz single-trip limits'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: US_CLAIM_PROCESS,
    pricingModel: 'trip_cost',
    baseRates: bands([0.0, 0.062, 0.069, 0.082, 0.10, 0.128, 0.16]),
    minPremium: 55,
    bestFor: ['Expensive itineraries and long-haul trips', 'Cruises to remote regions', 'Travellers who want headroom on every limit'],
  },
  {
    id: 'travel-guard-preferred',
    slug: 'travel-guard-preferred',
    providerId: 'travel-guard',
    name: 'Travel Guard Preferred',
    tagline: 'AIG’s mid-tier bestseller — balanced limits with a deep add-on menu.',
    market: 'US',
    currency: 'USD',
    categories: ['single_trip', 'family', 'cruise', 'group'],
    regions: ['worldwide'],
    eligibility: { minAge: 0, maxAge: 99, maxTripDays: 365 },
    medicalSumInsuredUsd: 50_000,
    medicalSumInsuredLabel: '$50,000',
    deductibleLabel: '$0 deductible',
    coverage: {
      emergency_medical: usd(50_000),
      medical_evacuation: usd(500_000),
      trip_cancellation: incl('100% of insured trip cost', 50_000),
      trip_interruption: incl('150% of insured trip cost', 75_000),
      trip_delay: usd(800, '$200/day after 5h'),
      missed_connection: usd(1_000),
      baggage_loss: usd(1_000),
      baggage_delay: usd(300),
      cancel_for_any_reason: addOn(incl('50% of trip cost (optional CFAR)', 0, 'Buy within 15 days of initial deposit')),
      covid_medical: incl('Covered as any sickness'),
      pre_existing_conditions: incl('Waiver if bought within 15 days of initial deposit'),
    },
    highlights: ['Add-ons: adventure sports, pet, wedding, name-your-family', 'Trips up to a full year', 'CFAR upgrade available'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: US_CLAIM_PROCESS,
    pricingModel: 'trip_cost',
    baseRates: bands([0.04, 0.052, 0.06, 0.072, 0.09, 0.118, 0.15]),
    minPremium: 40,
    bestFor: ['Travellers who want to tailor cover with add-ons', 'Groups and cruises'],
  },
  {
    id: 'travel-guard-deluxe',
    slug: 'travel-guard-deluxe',
    providerId: 'travel-guard',
    name: 'Travel Guard Deluxe',
    tagline: 'AIG’s flagship: $100k medical, $1M evacuation, generous delay benefits.',
    market: 'US',
    currency: 'USD',
    categories: ['single_trip', 'cruise', 'business', 'adventure'],
    regions: ['worldwide'],
    eligibility: { minAge: 0, maxAge: 99, maxTripDays: 365 },
    medicalSumInsuredUsd: 100_000,
    medicalSumInsuredLabel: '$100,000',
    deductibleLabel: '$0 deductible',
    coverage: {
      emergency_medical: usd(100_000),
      medical_evacuation: usd(1_000_000),
      trip_cancellation: incl('100% of insured trip cost', 100_000),
      trip_interruption: incl('150% of insured trip cost', 150_000),
      trip_delay: usd(1_000, '$250/day after 5h'),
      missed_connection: usd(1_000),
      baggage_loss: usd(2_500),
      baggage_delay: usd(500),
      adventure_sports: addOn(incl('Optional adventure sports bundle')),
      cancel_for_any_reason: addOn(incl('50% of trip cost (optional CFAR)')),
      covid_medical: incl('Covered as any sickness'),
      pre_existing_conditions: incl('Waiver if bought within 15 days of initial deposit'),
      compassionate_visit: incl('Bedside visit benefit included'),
    },
    highlights: ['$100k medical + $1M evacuation', 'Adventure sports bundle available', 'Premium delay/missed-connection limits'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: US_CLAIM_PROCESS,
    pricingModel: 'trip_cost',
    baseRates: bands([0.045, 0.06, 0.068, 0.082, 0.102, 0.132, 0.165]),
    minPremium: 52,
    bestFor: ['High-value trips', 'Adventure itineraries (with bundle)', 'Travellers who want top-shelf limits'],
  },
  {
    id: 'seven-corners-trip-choice',
    slug: 'seven-corners-trip-choice',
    providerId: 'seven-corners',
    name: 'Seven Corners Trip Protection Choice',
    tagline: 'High medical limits for a US comprehensive plan, cruise-friendly benefits.',
    market: 'US',
    currency: 'USD',
    categories: ['single_trip', 'cruise', 'adventure', 'family'],
    regions: ['worldwide'],
    eligibility: { minAge: 0, maxAge: 99, maxTripDays: 90 },
    medicalSumInsuredUsd: 250_000,
    medicalSumInsuredLabel: '$250,000',
    deductibleLabel: '$0 deductible',
    coverage: {
      emergency_medical: usd(250_000),
      medical_evacuation: usd(1_000_000),
      trip_cancellation: incl('100% of insured trip cost', 100_000),
      trip_interruption: incl('150% of insured trip cost', 150_000),
      trip_delay: usd(2_000, '$250/day after 6h'),
      missed_connection: usd(1_500),
      baggage_loss: usd(2_500),
      baggage_delay: usd(500),
      cancel_for_any_reason: addOn(incl('75% of trip cost (optional CFAR)', 0, 'Buy within 20 days of initial deposit')),
      covid_medical: incl('Covered as any sickness'),
      pre_existing_conditions: incl('Waiver if bought within 20 days of initial deposit'),
      adventure_sports: addOn(incl('Optional sports & golf bundle')),
    },
    highlights: ['$250k medical — among the highest on US comprehensive plans', '75% CFAR option', 'Generous 20-day waiver window'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: US_CLAIM_PROCESS,
    pricingModel: 'trip_cost',
    baseRates: bands([0.045, 0.058, 0.066, 0.08, 0.10, 0.13, 0.162]),
    minPremium: 45,
    bestFor: ['Travellers prioritising medical limits', 'Cruises', 'Late bookers who still want a CFAR window'],
  },
  {
    id: 'travelex-travel-select',
    slug: 'travelex-travel-select',
    providerId: 'travelex',
    name: 'Travelex Travel Select',
    tagline: 'The family favourite — children 17 and under insured free with an adult.',
    market: 'US',
    currency: 'USD',
    categories: ['single_trip', 'family', 'cruise'],
    regions: ['worldwide'],
    eligibility: { minAge: 0, maxAge: 99, maxTripDays: 180 },
    medicalSumInsuredUsd: 50_000,
    medicalSumInsuredLabel: '$50,000',
    deductibleLabel: '$0 deductible',
    coverage: {
      emergency_medical: usd(50_000),
      medical_evacuation: usd(500_000),
      trip_cancellation: incl('100% of insured trip cost', 50_000),
      trip_interruption: incl('150% of insured trip cost', 75_000),
      trip_delay: usd(2_000, '$250/day after 5h'),
      missed_connection: usd(750),
      baggage_loss: usd(1_000),
      baggage_delay: usd(200),
      cancel_for_any_reason: addOn(incl('75% of trip cost (optional CFAR)')),
      adventure_sports: addOn(incl('Optional adventure activities upgrade')),
      covid_medical: incl('Covered as any sickness'),
      pre_existing_conditions: incl('Waiver if bought within 15 days of initial deposit'),
    },
    highlights: ['Kids 17 and under free', 'Upgradeable with CFAR and adventure packs', 'Primary medical coverage (pays first)'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: US_CLAIM_PROCESS,
    pricingModel: 'trip_cost',
    baseRates: bands([0.0, 0.054, 0.061, 0.074, 0.092, 0.12, 0.15]),
    minPremium: 42,
    bestFor: ['Families with children', 'Multi-generation trips'],
  },
  {
    id: 'world-nomads-standard',
    slug: 'world-nomads-standard',
    providerId: 'world-nomads',
    name: 'World Nomads Standard',
    tagline: 'Backpacker classic — 150+ adventure activities covered as standard.',
    market: 'US',
    currency: 'USD',
    categories: ['single_trip', 'backpacker', 'adventure', 'digital_nomad'],
    regions: ['worldwide'],
    eligibility: { minAge: 18, maxAge: 69, maxTripDays: 180 },
    medicalSumInsuredUsd: 100_000,
    medicalSumInsuredLabel: '$100,000',
    deductibleLabel: '$0 deductible',
    coverage: {
      emergency_medical: usd(100_000),
      medical_evacuation: usd(300_000),
      repatriation: incl('Included in evacuation limit'),
      trip_cancellation: usd(2_500),
      trip_interruption: usd(2_500),
      trip_delay: usd(500),
      baggage_loss: usd(1_000),
      adventure_sports: incl('150+ activities covered as standard'),
      covid_medical: incl('Emergency medical for COVID-19 included'),
      electronics: addOn(incl('Optional gear cover upgrade')),
    },
    highlights: ['Buy or extend mid-trip from abroad', 'Adventure activities on by default', 'Built for long, flexible itineraries'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: US_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([0, 5.2, 6.0, 7.4, 9.5, 0, 0]),
    minPremium: 45,
    bestFor: ['Backpackers and gap years', 'Trekking, diving, surfing itineraries', 'Digital nomads on the move'],
  },
  {
    id: 'world-nomads-explorer',
    slug: 'world-nomads-explorer',
    providerId: 'world-nomads',
    name: 'World Nomads Explorer',
    tagline: 'Higher limits plus winter sports and higher-risk activities unlocked.',
    market: 'US',
    currency: 'USD',
    categories: ['single_trip', 'backpacker', 'adventure', 'digital_nomad'],
    regions: ['worldwide'],
    eligibility: { minAge: 18, maxAge: 69, maxTripDays: 180 },
    medicalSumInsuredUsd: 150_000,
    medicalSumInsuredLabel: '$150,000',
    deductibleLabel: '$0 deductible',
    coverage: {
      emergency_medical: usd(150_000),
      medical_evacuation: usd(500_000),
      repatriation: incl('Included in evacuation limit'),
      trip_cancellation: usd(10_000),
      trip_interruption: usd(10_000),
      trip_delay: usd(1_500),
      baggage_loss: usd(3_000),
      adventure_sports: incl('200+ activities incl. higher-risk tiers'),
      winter_sports: incl('Skiing/snowboarding included'),
      covid_medical: incl('Emergency medical for COVID-19 included'),
      electronics: addOn(incl('Optional gear cover upgrade')),
    },
    highlights: ['Winter sports included', 'Higher cancellation and gear limits', 'Extend cover from anywhere'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: US_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([0, 7.2, 8.2, 10.0, 12.8, 0, 0]),
    minPremium: 60,
    bestFor: ['Ski/snowboard trips', 'High-adventure expeditions', 'Long multi-country routes'],
  },
  {
    id: 'travel-guard-annual',
    slug: 'travel-guard-annual',
    providerId: 'travel-guard',
    name: 'Travel Guard Annual',
    tagline: 'One yearly premium covers every trip you take, up to 90 days each.',
    market: 'US',
    currency: 'USD',
    categories: ['annual_multi_trip', 'business'],
    regions: ['worldwide'],
    eligibility: { minAge: 18, maxAge: 99, maxTripDays: 365, perTripCapDays: 90 },
    medicalSumInsuredUsd: 50_000,
    medicalSumInsuredLabel: '$50,000',
    deductibleLabel: '$0 deductible',
    coverage: {
      emergency_medical: usd(50_000),
      medical_evacuation: usd(500_000),
      trip_cancellation: usd(2_500, 'Annual aggregate'),
      trip_interruption: usd(2_500),
      trip_delay: usd(1_500, '$150/day after 5h'),
      missed_connection: usd(1_000),
      baggage_loss: usd(2_500),
      baggage_delay: usd(1_000),
      covid_medical: incl('Covered as any sickness'),
    },
    highlights: ['Unlimited trips per year (≤90 days each)', 'Strong baggage & delay limits', 'Ideal from ~3 international trips/year'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: US_CLAIM_PROCESS,
    pricingModel: 'annual_flat',
    baseRates: bands([0, 259, 279, 309, 359, 429, 0]),
    minPremium: 259,
    bestFor: ['Frequent flyers and consultants', 'Anyone taking 3+ trips a year'],
  },
  {
    id: 'allianz-alltrips-prime',
    slug: 'allianz-alltrips-prime',
    providerId: 'allianz',
    name: 'Allianz AllTrips Prime',
    tagline: 'Simple flat-price annual protection for every trip of the year.',
    market: 'US',
    currency: 'USD',
    categories: ['annual_multi_trip', 'business'],
    regions: ['worldwide'],
    eligibility: { minAge: 18, maxAge: 99, maxTripDays: 365, perTripCapDays: 45 },
    medicalSumInsuredUsd: 25_000,
    medicalSumInsuredLabel: '$25,000',
    deductibleLabel: '$0 deductible',
    coverage: {
      emergency_medical: usd(25_000),
      medical_evacuation: usd(500_000),
      trip_cancellation: usd(3_000, 'Annual aggregate'),
      trip_interruption: usd(3_000),
      trip_delay: usd(600, '$200/day'),
      baggage_loss: usd(1_000),
      baggage_delay: usd(300),
      rental_car_excess: usd(45_000, 'Included — a standout annual benefit'),
      covid_medical: incl('Epidemic Coverage Endorsement included'),
    },
    highlights: ['Rental car damage cover included all year', 'Flat family pricing options', 'Covers domestic getaways ≥100 miles too'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: US_CLAIM_PROCESS,
    pricingModel: 'annual_flat',
    baseRates: bands([0, 249, 259, 289, 329, 389, 0]),
    minPremium: 249,
    bestFor: ['Frequent weekenders and road-trippers', 'Business travellers who also rent cars'],
  },

  // ================= GLOBAL (visitor / travel-medical) =================
  {
    id: 'img-patriot-america-plus',
    slug: 'img-patriot-america-plus',
    providerId: 'img',
    name: 'IMG Patriot America Plus',
    tagline: 'The benchmark visitor-medical plan for parents and guests visiting the USA.',
    market: 'GLOBAL',
    currency: 'USD',
    categories: ['visitors_usa', 'single_trip'],
    regions: ['us_canada'],
    eligibility: { minAge: 0, maxAge: 89, maxTripDays: 365, note: 'Ages 70+ limited to $50,000–100,000 sum insured' },
    medicalSumInsuredUsd: 250_000,
    medicalSumInsuredLabel: 'Up to $250,000 (selectable)',
    deductibleLabel: 'Deductible selectable $0–$2,500',
    coverage: {
      emergency_medical: usd(250_000, 'Choose $50k–$1M sum insured'),
      medical_evacuation: usd(1_000_000),
      repatriation: usd(50_000),
      trip_interruption: usd(10_000),
      baggage_loss: usd(500, 'Checked baggage'),
      accidental_death: usd(25_000),
      covid_medical: incl('COVID-19 treated as any illness'),
      pre_existing_conditions: incl('Acute onset of pre-existing conditions covered to age 69'),
      dental: usd(300, 'Acute emergency dental'),
      telemedicine: incl('Included'),
    },
    highlights: ['Direct billing at US PPO network hospitals', 'Acute-onset pre-existing cover under 70', 'Buy for any length from 5 days to a year'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: VISITOR_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([1.9, 2.4, 3.1, 4.6, 8.2, 13.5, 19.0]),
    minPremium: 30,
    bestFor: ['Parents visiting children in the USA', 'Tourists and B1/B2 visitors', 'New immigrants awaiting US health cover'],
  },
  {
    id: 'img-patriot-platinum',
    slug: 'img-patriot-platinum',
    providerId: 'img',
    name: 'IMG Patriot Platinum',
    tagline: 'Premium travel medical with sums insured up to $8M and top-tier assistance.',
    market: 'GLOBAL',
    currency: 'USD',
    categories: ['visitors_usa', 'digital_nomad', 'medical_travel', 'single_trip'],
    regions: ['worldwide', 'us_canada'],
    eligibility: { minAge: 0, maxAge: 89, maxTripDays: 365 },
    medicalSumInsuredUsd: 1_000_000,
    medicalSumInsuredLabel: 'Up to $1,000,000 (selectable to $8M)',
    deductibleLabel: 'Deductible selectable $0–$25,000',
    coverage: {
      emergency_medical: usd(1_000_000),
      medical_evacuation: usd(1_000_000),
      repatriation: usd(50_000),
      trip_interruption: usd(10_000),
      baggage_loss: usd(2_500),
      accidental_death: usd(50_000),
      covid_medical: incl('COVID-19 treated as any illness'),
      pre_existing_conditions: incl('Acute onset covered; full cover needs long-term GMI plan'),
      dental: usd(500),
      compassionate_visit: incl('Emergency reunion benefit included'),
      telemedicine: incl('Included'),
    },
    highlights: ['Sums insured to $8M', 'Worldwide or US-inclusive cover', 'Concierge-grade assistance services'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: VISITOR_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([2.6, 3.4, 4.4, 6.4, 11.0, 17.5, 24.0]),
    minPremium: 40,
    bestFor: ['Long international stays needing serious limits', 'Executives and premium travellers', 'Complication cover context around planned treatment (ask our desk)'],
  },
  {
    id: 'img-patriot-international',
    slug: 'img-patriot-international',
    providerId: 'img',
    name: 'IMG Patriot International',
    tagline: 'Travel medical for trips outside the USA — including visitors to India.',
    market: 'GLOBAL',
    currency: 'USD',
    categories: ['visitors_india', 'single_trip', 'digital_nomad'],
    regions: ['worldwide_excl_us'],
    eligibility: { minAge: 0, maxAge: 89, maxTripDays: 365 },
    medicalSumInsuredUsd: 100_000,
    medicalSumInsuredLabel: 'Up to $100,000 (selectable to $1M)',
    deductibleLabel: 'Deductible selectable $0–$2,500',
    coverage: {
      emergency_medical: usd(100_000),
      medical_evacuation: usd(1_000_000),
      repatriation: usd(50_000),
      trip_interruption: usd(10_000),
      baggage_loss: usd(500),
      accidental_death: usd(25_000),
      covid_medical: incl('COVID-19 treated as any illness'),
      dental: usd(300),
      telemedicine: incl('Included'),
    },
    highlights: ['Cheaper band for non-US destinations', 'Covers foreign visitors travelling to India', 'Evacuation to centre of excellence'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: VISITOR_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([1.3, 1.7, 2.2, 3.2, 5.6, 9.0, 13.0]),
    minPremium: 25,
    bestFor: ['Visitors to India and Asia', 'Non-US itineraries needing US-style medical cover'],
  },
  {
    id: 'seven-corners-travel-medical-usa',
    slug: 'seven-corners-travel-medical-usa',
    providerId: 'seven-corners',
    name: 'Seven Corners Travel Medical USA',
    tagline: 'Flexible visitor medical for the USA with strong acute-onset benefits.',
    market: 'GLOBAL',
    currency: 'USD',
    categories: ['visitors_usa', 'single_trip', 'student'],
    regions: ['us_canada'],
    eligibility: { minAge: 0, maxAge: 89, maxTripDays: 364 },
    medicalSumInsuredUsd: 175_000,
    medicalSumInsuredLabel: 'Up to $175,000 (selectable)',
    deductibleLabel: 'Deductible selectable $0–$5,000',
    coverage: {
      emergency_medical: usd(175_000),
      medical_evacuation: usd(500_000),
      repatriation: usd(50_000),
      trip_interruption: usd(5_000),
      baggage_loss: usd(500),
      accidental_death: usd(25_000),
      covid_medical: incl('COVID-19 treated as any illness'),
      pre_existing_conditions: incl('Acute onset covered (age-capped)'),
      dental: usd(300),
      telemedicine: incl('Included'),
    },
    highlights: ['Renewable up to 364 days', 'US PPO network direct billing', 'Solid budget alternative to Patriot plans'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: VISITOR_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([1.7, 2.1, 2.8, 4.2, 7.4, 12.0, 17.0]),
    minPremium: 28,
    bestFor: ['Visiting family on a budget', 'Students before university cover starts'],
  },
  {
    id: 'seven-corners-travel-medical-global',
    slug: 'seven-corners-travel-medical-global',
    providerId: 'seven-corners',
    name: 'Seven Corners Travel Medical Global',
    tagline: 'Worldwide travel medical for long stays outside your home country.',
    market: 'GLOBAL',
    currency: 'USD',
    categories: ['visitors_india', 'digital_nomad', 'single_trip', 'backpacker'],
    regions: ['worldwide', 'worldwide_excl_us'],
    eligibility: { minAge: 0, maxAge: 89, maxTripDays: 364 },
    medicalSumInsuredUsd: 100_000,
    medicalSumInsuredLabel: 'Up to $100,000 (selectable to $5M)',
    deductibleLabel: 'Deductible selectable $0–$5,000',
    coverage: {
      emergency_medical: usd(100_000),
      medical_evacuation: usd(500_000),
      repatriation: usd(50_000),
      trip_interruption: usd(5_000),
      baggage_loss: usd(500),
      accidental_death: usd(25_000),
      covid_medical: incl('COVID-19 treated as any illness'),
      adventure_sports: addOn(incl('Optional adventure activities rider')),
      dental: usd(300),
      telemedicine: incl('Included'),
    },
    highlights: ['Cover in 180+ countries', 'Optional adventure rider', 'Renewable for long nomad stints'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: VISITOR_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([1.4, 1.8, 2.4, 3.5, 6.0, 9.8, 14.0]),
    minPremium: 25,
    bestFor: ['Digital nomads', 'Foreign visitors to India', 'Multi-country long trips'],
  },

  // ================= INDIA MARKET =================
  {
    id: 'tata-aig-travel-guard-silver',
    slug: 'tata-aig-travel-guard-silver',
    providerId: 'tata-aig',
    name: 'Tata AIG Travel Guard Silver',
    tagline: 'India’s bestselling starter tier for Asia and Europe holidays.',
    market: 'IN',
    currency: 'INR',
    categories: ['single_trip', 'schengen', 'family', 'pilgrimage'],
    regions: ['asia', 'schengen_europe', 'worldwide_excl_us'],
    eligibility: { minAge: 0, maxAge: 70, maxTripDays: 180 },
    medicalSumInsuredUsd: 50_000,
    medicalSumInsuredLabel: '$50,000',
    deductibleLabel: '$100 medical deductible',
    coverage: {
      emergency_medical: usd(50_000),
      medical_evacuation: incl('Included within medical sum insured'),
      repatriation: incl('Included'),
      trip_cancellation: usd(500),
      trip_interruption: usd(750),
      trip_delay: usd(125, 'After 12h delay'),
      baggage_loss: usd(750),
      baggage_delay: usd(100),
      passport_loss: usd(250),
      personal_liability: usd(100_000),
      accidental_death: usd(10_000),
      covid_medical: incl('Medical expenses for COVID-19 covered'),
      dental: usd(250),
      hijack_distress: usd(500, '$125/day'),
    },
    highlights: ['Schengen-compliant certificate issued instantly', 'Strong personal liability cover', 'Trusted claim assistance network'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([55, 62, 72, 95, 145, 235, 0]),
    minPremium: 350,
    bestFor: ['First international trips', 'Schengen visa applications', 'Budget-conscious families'],
  },
  {
    id: 'tata-aig-travel-guard-gold',
    slug: 'tata-aig-travel-guard-gold',
    providerId: 'tata-aig',
    name: 'Tata AIG Travel Guard Gold',
    tagline: 'US-ready $250k medical cover — the workhorse for USA/Canada trips.',
    market: 'IN',
    currency: 'INR',
    categories: ['single_trip', 'family', 'business', 'group', 'medical_travel'],
    regions: ['worldwide', 'us_canada'],
    eligibility: { minAge: 0, maxAge: 70, maxTripDays: 180 },
    medicalSumInsuredUsd: 250_000,
    medicalSumInsuredLabel: '$250,000',
    deductibleLabel: '$100 medical deductible',
    coverage: {
      emergency_medical: usd(250_000),
      medical_evacuation: incl('Included within medical sum insured'),
      repatriation: incl('Included'),
      trip_cancellation: usd(1_000),
      trip_interruption: usd(1_500),
      trip_delay: usd(250),
      missed_connection: usd(500),
      baggage_loss: usd(1_000),
      baggage_delay: usd(200),
      passport_loss: usd(250),
      personal_liability: usd(200_000),
      accidental_death: usd(25_000),
      covid_medical: incl('Medical expenses for COVID-19 covered'),
      pre_existing_conditions: incl('Life-threatening episodes covered up to sub-limit'),
      compassionate_visit: incl('Round-trip fare for a family member'),
      dental: usd(500),
      home_burglary: inr(200_000, 'Cover for your locked home while away'),
    },
    highlights: ['$250k medical suits US visits', 'Home burglary cover while travelling', 'Compassionate-visit benefit'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([70, 80, 95, 130, 210, 340, 0]),
    minPremium: 450,
    bestFor: ['USA/Canada trips from India', 'Business travel', 'Anyone wanting headroom on medical limits'],
  },
  {
    id: 'tata-aig-travel-guard-platinum',
    slug: 'tata-aig-travel-guard-platinum',
    providerId: 'tata-aig',
    name: 'Tata AIG Travel Guard Platinum',
    tagline: 'Flagship tier: $500k medical and the richest benefit set in the range.',
    market: 'IN',
    currency: 'INR',
    categories: ['single_trip', 'business', 'family'],
    regions: ['worldwide', 'us_canada'],
    eligibility: { minAge: 0, maxAge: 70, maxTripDays: 180 },
    medicalSumInsuredUsd: 500_000,
    medicalSumInsuredLabel: '$500,000',
    deductibleLabel: '$100 medical deductible',
    coverage: {
      emergency_medical: usd(500_000),
      medical_evacuation: incl('Included within medical sum insured'),
      repatriation: incl('Included'),
      trip_cancellation: usd(2_000),
      trip_interruption: usd(3_000),
      trip_delay: usd(500),
      missed_connection: usd(1_000),
      baggage_loss: usd(1_500),
      baggage_delay: usd(300),
      passport_loss: usd(300),
      personal_liability: usd(500_000),
      accidental_death: usd(50_000),
      covid_medical: incl('Medical expenses for COVID-19 covered'),
      pre_existing_conditions: incl('Life-threatening episodes covered up to sub-limit'),
      compassionate_visit: incl('Included'),
      dental: usd(750),
      home_burglary: inr(500_000),
    },
    highlights: ['Half-million-dollar medical limit', 'Premium liability and AD&D sums', 'Best-in-range delay benefits'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([85, 98, 118, 160, 255, 410, 0]),
    minPremium: 550,
    bestFor: ['Long US stays', 'Premium travellers', 'Executives with employer top-ups'],
  },
  {
    id: 'tata-aig-student-guard',
    slug: 'tata-aig-student-guard',
    providerId: 'tata-aig',
    name: 'Tata AIG Student Guard',
    tagline: 'University-compliant cover for Indian students abroad, up to 2 years.',
    market: 'IN',
    currency: 'INR',
    categories: ['student'],
    regions: ['worldwide', 'us_canada'],
    eligibility: { minAge: 16, maxAge: 35, maxTripDays: 730 },
    medicalSumInsuredUsd: 250_000,
    medicalSumInsuredLabel: '$250,000',
    deductibleLabel: '$100 medical deductible',
    coverage: {
      emergency_medical: usd(250_000),
      medical_evacuation: incl('Included'),
      repatriation: incl('Included'),
      trip_interruption: usd(1_000, 'Study interruption benefit'),
      baggage_loss: usd(1_000),
      passport_loss: usd(250),
      personal_liability: usd(100_000),
      accidental_death: usd(15_000),
      covid_medical: incl('Covered'),
      compassionate_visit: incl('Two-way ticket for family member'),
      dental: usd(500),
      legal_assistance: incl('Bail bond & legal cover included'),
    },
    highlights: ['Meets most US/UK university waiver requirements', 'Study-interruption & sponsor-protection benefits', 'Cheaper than campus plans in most cases'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([0, 52, 60, 0, 0, 0, 0]),
    minPremium: 500,
    bestFor: ['Indian students heading to the US, UK, Canada, Australia', 'Parents comparing against university plans'],
  },
  {
    id: 'icici-lombard-gold',
    slug: 'icici-lombard-gold',
    providerId: 'icici-lombard',
    name: 'ICICI Lombard International Travel Gold',
    tagline: 'Balanced worldwide cover from India’s largest private insurer.',
    market: 'IN',
    currency: 'INR',
    categories: ['single_trip', 'schengen', 'family', 'group'],
    regions: ['worldwide', 'us_canada', 'schengen_europe', 'asia'],
    eligibility: { minAge: 0, maxAge: 85, maxTripDays: 180 },
    medicalSumInsuredUsd: 100_000,
    medicalSumInsuredLabel: '$100,000',
    deductibleLabel: '$100 medical deductible',
    coverage: {
      emergency_medical: usd(100_000),
      medical_evacuation: incl('Included'),
      repatriation: incl('Included'),
      trip_cancellation: usd(750),
      trip_interruption: usd(1_000),
      trip_delay: usd(150),
      baggage_loss: usd(1_000),
      baggage_delay: usd(100),
      passport_loss: usd(300),
      personal_liability: usd(100_000),
      accidental_death: usd(25_000),
      covid_medical: incl('Covered'),
      dental: usd(250),
      hijack_distress: usd(1_000),
    },
    highlights: ['Issues to age 85 — rare in the market', 'Instant Schengen certificate', 'Large overseas cashless network'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([58, 66, 78, 105, 160, 260, 380]),
    minPremium: 380,
    bestFor: ['Worldwide holidays', 'Older travellers other insurers refuse', 'Schengen applications'],
  },
  {
    id: 'icici-lombard-senior',
    slug: 'icici-lombard-senior',
    providerId: 'icici-lombard',
    name: 'ICICI Lombard Senior Citizen Travel',
    tagline: 'Purpose-built for travellers 61–85, with pre-existing life-threat cover.',
    market: 'IN',
    currency: 'INR',
    categories: ['senior', 'single_trip', 'visitors_usa'],
    regions: ['worldwide', 'us_canada', 'schengen_europe', 'asia'],
    eligibility: { minAge: 61, maxAge: 85, maxTripDays: 180 },
    medicalSumInsuredUsd: 50_000,
    medicalSumInsuredLabel: '$50,000',
    deductibleLabel: '$200 medical deductible',
    coverage: {
      emergency_medical: usd(50_000),
      medical_evacuation: incl('Included'),
      repatriation: incl('Included'),
      trip_delay: usd(150),
      baggage_loss: usd(750),
      passport_loss: usd(250),
      personal_liability: usd(100_000),
      accidental_death: usd(10_000),
      covid_medical: incl('Covered'),
      pre_existing_conditions: incl('Life-threatening episodes covered up to sub-limit'),
      dental: usd(250),
      compassionate_visit: incl('Included'),
    },
    highlights: ['Cover to age 85 without medical tests for most trips', 'Pre-existing life-threat sub-limit', 'Designed for parents visiting children abroad'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([0, 0, 0, 0, 175, 285, 420]),
    minPremium: 600,
    bestFor: ['Senior citizens visiting the USA', 'Parents on long family visits'],
  },
  {
    id: 'hdfc-ergo-travel-gold',
    slug: 'hdfc-ergo-travel-gold',
    providerId: 'hdfc-ergo',
    name: 'HDFC ERGO Travel Gold',
    tagline: 'Instant Schengen-compliant cover with gadget and adventure add-ons.',
    market: 'IN',
    currency: 'INR',
    categories: ['single_trip', 'schengen', 'family', 'adventure'],
    regions: ['worldwide', 'us_canada', 'schengen_europe', 'asia'],
    eligibility: { minAge: 0, maxAge: 70, maxTripDays: 180 },
    medicalSumInsuredUsd: 100_000,
    medicalSumInsuredLabel: '$100,000',
    deductibleLabel: '$100 medical deductible',
    coverage: {
      emergency_medical: usd(100_000),
      medical_evacuation: incl('Included'),
      repatriation: incl('Included'),
      trip_cancellation: usd(500),
      trip_interruption: usd(750),
      trip_delay: usd(120),
      baggage_loss: usd(1_000),
      baggage_delay: usd(100),
      passport_loss: usd(300),
      personal_liability: usd(100_000),
      accidental_death: usd(25_000),
      covid_medical: incl('Covered'),
      adventure_sports: addOn(incl('Optional adventure sports add-on')),
      electronics: addOn(incl('Optional gadget cover add-on')),
      dental: usd(300),
    },
    highlights: ['Adventure & gadget add-ons', 'Fast fully-digital issuance', 'Trusted bancassurance brand'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([56, 64, 76, 102, 155, 255, 0]),
    minPremium: 370,
    bestFor: ['Schengen trips', 'Travellers carrying expensive gear', 'Light adventure itineraries'],
  },
  {
    id: 'hdfc-ergo-annual-multi-trip',
    slug: 'hdfc-ergo-annual-multi-trip',
    providerId: 'hdfc-ergo',
    name: 'HDFC ERGO Annual Multi-Trip',
    tagline: 'A year of international trips on one policy — built for frequent flyers.',
    market: 'IN',
    currency: 'INR',
    categories: ['annual_multi_trip', 'business'],
    regions: ['worldwide', 'us_canada'],
    eligibility: { minAge: 18, maxAge: 70, maxTripDays: 365, perTripCapDays: 45 },
    medicalSumInsuredUsd: 250_000,
    medicalSumInsuredLabel: '$250,000',
    deductibleLabel: '$100 medical deductible',
    coverage: {
      emergency_medical: usd(250_000),
      medical_evacuation: incl('Included'),
      repatriation: incl('Included'),
      trip_delay: usd(150),
      baggage_loss: usd(1_000),
      baggage_delay: usd(100),
      passport_loss: usd(300),
      personal_liability: usd(200_000),
      accidental_death: usd(25_000),
      covid_medical: incl('Covered'),
      dental: usd(300),
    },
    highlights: ['Unlimited trips (≤45 days each)', 'US-ready $250k medical', 'One certificate for every visa application'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'annual_flat',
    baseRates: bands([0, 6_500, 7_500, 9_800, 14_500, 0, 0]),
    minPremium: 6_500,
    bestFor: ['Consultants and sales leaders flying monthly', 'Founders doing US–India loops'],
  },
  {
    id: 'bajaj-allianz-travel-prime-gold',
    slug: 'bajaj-allianz-travel-prime-gold',
    providerId: 'bajaj-allianz',
    name: 'Bajaj Allianz Travel Prime Gold',
    tagline: 'Feature-dense worldwide cover with standout home-burglary protection.',
    market: 'IN',
    currency: 'INR',
    categories: ['single_trip', 'schengen', 'family'],
    regions: ['worldwide', 'us_canada', 'schengen_europe', 'asia'],
    eligibility: { minAge: 0, maxAge: 70, maxTripDays: 180 },
    medicalSumInsuredUsd: 100_000,
    medicalSumInsuredLabel: '$100,000',
    deductibleLabel: '$100 medical deductible',
    coverage: {
      emergency_medical: usd(100_000),
      medical_evacuation: incl('Included'),
      repatriation: incl('Included'),
      trip_cancellation: usd(600),
      trip_interruption: usd(800),
      trip_delay: usd(120),
      baggage_loss: usd(1_000),
      baggage_delay: usd(100),
      passport_loss: usd(300),
      personal_liability: usd(200_000),
      accidental_death: usd(25_000),
      covid_medical: incl('Covered'),
      home_burglary: inr(300_000),
      hijack_distress: usd(500),
      dental: usd(300),
    },
    highlights: ['Home burglary cover while you travel', 'Fast-track small medical claims', 'Wide age acceptance'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([57, 65, 77, 103, 158, 258, 0]),
    minPremium: 375,
    bestFor: ['Homeowners on long trips', 'Worldwide holidays', 'Schengen applications'],
  },
  {
    id: 'bajaj-allianz-travel-prime-senior',
    slug: 'bajaj-allianz-travel-prime-senior',
    providerId: 'bajaj-allianz',
    name: 'Bajaj Allianz Travel Prime Senior',
    tagline: 'Dedicated senior plan (61–75) with medical cover tuned for US family visits.',
    market: 'IN',
    currency: 'INR',
    categories: ['senior', 'single_trip', 'visitors_usa'],
    regions: ['worldwide', 'us_canada', 'schengen_europe', 'asia'],
    eligibility: { minAge: 61, maxAge: 75, maxTripDays: 180 },
    medicalSumInsuredUsd: 50_000,
    medicalSumInsuredLabel: '$50,000',
    deductibleLabel: '$200 medical deductible',
    coverage: {
      emergency_medical: usd(50_000),
      medical_evacuation: incl('Included'),
      repatriation: incl('Included'),
      trip_delay: usd(120),
      baggage_loss: usd(750),
      passport_loss: usd(250),
      personal_liability: usd(100_000),
      accidental_death: usd(10_000),
      covid_medical: incl('Covered'),
      pre_existing_conditions: incl('Life-threatening episodes covered up to sub-limit'),
      dental: usd(500, 'Higher dental sub-limit than standard tiers'),
      compassionate_visit: incl('Included'),
    },
    highlights: ['No medical check-up for issuance', 'Senior-tuned benefit sub-limits', 'Assistance-first claims handling'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([0, 0, 0, 0, 170, 275, 0]),
    minPremium: 580,
    bestFor: ['Parents 61–75 visiting family abroad', 'Senior group tours'],
  },
  {
    id: 'care-explore-asia',
    slug: 'care-explore-asia',
    providerId: 'care-health',
    name: 'Care Explore — Asia',
    tagline: 'Sharp pricing for Asia trips — Thailand, Dubai, Singapore, Bali and more.',
    market: 'IN',
    currency: 'INR',
    categories: ['single_trip', 'family', 'pilgrimage', 'backpacker'],
    regions: ['asia'],
    eligibility: { minAge: 0, maxAge: 70, maxTripDays: 180 },
    medicalSumInsuredUsd: 25_000,
    medicalSumInsuredLabel: '$25,000',
    deductibleLabel: '$50 medical deductible',
    coverage: {
      emergency_medical: usd(25_000),
      medical_evacuation: incl('Included'),
      repatriation: incl('Included'),
      trip_cancellation: usd(300),
      trip_delay: usd(100),
      baggage_loss: usd(500),
      baggage_delay: usd(75),
      passport_loss: usd(200),
      personal_liability: usd(50_000),
      accidental_death: usd(10_000),
      covid_medical: incl('Covered'),
      dental: usd(200),
    },
    highlights: ['Among the cheapest Asia covers from India', 'Quick digital issuance', 'Health-insurer claims muscle'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([38, 44, 52, 70, 108, 175, 0]),
    minPremium: 250,
    bestFor: ['Southeast Asia holidays', 'Umrah/pilgrimage routes in Asia', 'Short business hops to the Gulf'],
  },
  {
    id: 'care-explore-europe',
    slug: 'care-explore-europe',
    providerId: 'care-health',
    name: 'Care Explore — Europe',
    tagline: 'Schengen-compliant certificate at student-friendly prices.',
    market: 'IN',
    currency: 'INR',
    categories: ['single_trip', 'schengen', 'family'],
    regions: ['schengen_europe'],
    eligibility: { minAge: 0, maxAge: 70, maxTripDays: 180 },
    medicalSumInsuredUsd: 50_000,
    medicalSumInsuredLabel: '$50,000',
    deductibleLabel: '$50 medical deductible',
    coverage: {
      emergency_medical: usd(50_000, 'Comfortably above the €30,000 Schengen floor'),
      medical_evacuation: incl('Included'),
      repatriation: incl('Included'),
      trip_cancellation: usd(400),
      trip_delay: usd(100),
      baggage_loss: usd(750),
      baggage_delay: usd(75),
      passport_loss: usd(250),
      personal_liability: usd(100_000),
      accidental_death: usd(10_000),
      covid_medical: incl('Covered'),
      dental: usd(250),
    },
    highlights: ['Meets Schengen visa rules with margin', 'Embassy-accepted certificate format', 'Aggressive pricing'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([44, 50, 60, 82, 126, 205, 0]),
    minPremium: 300,
    bestFor: ['Schengen visa applicants', 'Europe tours on a budget'],
  },
  {
    id: 'care-explore-student',
    slug: 'care-explore-student',
    providerId: 'care-health',
    name: 'Care Explore — Student',
    tagline: 'Long-stay student cover with high sums at a fraction of campus plans.',
    market: 'IN',
    currency: 'INR',
    categories: ['student'],
    regions: ['worldwide', 'us_canada'],
    eligibility: { minAge: 16, maxAge: 40, maxTripDays: 730 },
    medicalSumInsuredUsd: 100_000,
    medicalSumInsuredLabel: '$100,000 (selectable higher)',
    deductibleLabel: '$100 medical deductible',
    coverage: {
      emergency_medical: usd(100_000),
      medical_evacuation: incl('Included'),
      repatriation: incl('Included'),
      trip_interruption: usd(750, 'Study interruption'),
      baggage_loss: usd(750),
      passport_loss: usd(250),
      personal_liability: usd(100_000),
      accidental_death: usd(15_000),
      covid_medical: incl('Covered'),
      compassionate_visit: incl('Included'),
      dental: usd(400),
    },
    highlights: ['Up to 2 years continuous cover', 'University-waiver documentation support', 'Health-insurer network abroad'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([0, 46, 54, 0, 0, 0, 0]),
    minPremium: 450,
    bestFor: ['Students comparing against mandatory university plans', 'Long study-abroad semesters'],
  },
  {
    id: 'reliance-travel-care-gold',
    slug: 'reliance-travel-care-gold',
    providerId: 'reliance-general',
    name: 'Reliance Travel Care Gold',
    tagline: 'Frequently the lowest quote for Schengen and Asia trips from India.',
    market: 'IN',
    currency: 'INR',
    categories: ['single_trip', 'schengen', 'family', 'pilgrimage'],
    regions: ['worldwide', 'schengen_europe', 'asia', 'worldwide_excl_us'],
    eligibility: { minAge: 0, maxAge: 70, maxTripDays: 180 },
    medicalSumInsuredUsd: 50_000,
    medicalSumInsuredLabel: '$50,000',
    deductibleLabel: '$100 medical deductible',
    coverage: {
      emergency_medical: usd(50_000),
      medical_evacuation: incl('Included'),
      repatriation: incl('Included'),
      trip_cancellation: usd(500),
      trip_delay: usd(100),
      baggage_loss: usd(750),
      baggage_delay: usd(100),
      passport_loss: usd(250),
      personal_liability: usd(100_000),
      accidental_death: usd(10_000),
      covid_medical: incl('Covered'),
      dental: usd(250),
    },
    highlights: ['Sharp premiums', 'Simple online purchase', 'Schengen-accepted certificates'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([40, 46, 56, 76, 118, 190, 0]),
    minPremium: 280,
    bestFor: ['Price-first shoppers', 'Standard Europe/Asia holidays'],
  },
  {
    id: 'digit-international',
    slug: 'digit-international',
    providerId: 'digit',
    name: 'Digit International Travel',
    tagline: 'Paperless cover with automatic flight-delay payouts — no claim forms.',
    market: 'IN',
    currency: 'INR',
    categories: ['single_trip', 'schengen', 'backpacker', 'digital_nomad'],
    regions: ['worldwide', 'us_canada', 'schengen_europe', 'asia'],
    eligibility: { minAge: 0, maxAge: 70, maxTripDays: 180 },
    medicalSumInsuredUsd: 100_000,
    medicalSumInsuredLabel: '$100,000 (selectable)',
    deductibleLabel: '$0 deductible options available',
    coverage: {
      emergency_medical: usd(100_000),
      medical_evacuation: incl('Included'),
      repatriation: incl('Included'),
      trip_cancellation: usd(500),
      trip_delay: incl('Auto-payout on qualifying flight delays', 100),
      missed_connection: usd(300),
      baggage_loss: usd(1_000),
      baggage_delay: usd(100),
      passport_loss: usd(300),
      personal_liability: usd(100_000),
      accidental_death: usd(15_000),
      covid_medical: incl('Covered'),
      adventure_sports: addOn(incl('Optional adventure add-on')),
      dental: usd(250),
    },
    highlights: ['Flight-delay benefit pays automatically from flight data', 'Missed-call claim intimation', 'Zero-deductible options'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([50, 58, 68, 92, 142, 230, 0]),
    minPremium: 330,
    bestFor: ['Digital-first travellers', 'Anyone burned by flight delays before', 'Backpackers wanting app-based claims'],
  },
  {
    id: 'digit-domestic',
    slug: 'digit-domestic',
    providerId: 'digit',
    name: 'Digit Domestic Travel',
    tagline: 'Low-cost protection for flights, trains and holidays within India.',
    market: 'IN',
    currency: 'INR',
    categories: ['domestic_india', 'pilgrimage', 'family'],
    regions: ['domestic_india'],
    eligibility: { minAge: 0, maxAge: 70, maxTripDays: 60 },
    medicalSumInsuredUsd: 6_000,
    medicalSumInsuredLabel: '₹5 lakh accident hospitalisation',
    deductibleLabel: 'No deductible',
    coverage: {
      emergency_medical: inr(500_000, 'Accidental hospitalisation'),
      medical_evacuation: inr(100_000),
      trip_cancellation: inr(25_000),
      trip_delay: incl('Auto-payout on qualifying flight delays', 50),
      missed_connection: inr(10_000),
      baggage_loss: inr(25_000),
      accidental_death: inr(1_000_000),
      permanent_disability: inr(1_000_000),
    },
    highlights: ['Covers Char Dham, weddings, and weekend trips alike', 'Flight-delay auto-payouts', 'From a few hundred rupees per trip'],
    exclusions: COMMON_EXCLUSIONS,
    claimProcess: IN_CLAIM_PROCESS,
    pricingModel: 'per_day',
    baseRates: bands([18, 22, 26, 34, 50, 80, 0]),
    minPremium: 129,
    bestFor: ['Domestic flights and holidays', 'Pilgrimage circuits', 'Family functions travel'],
  },
];

const byId = new Map(INSURANCE_PLANS.map((p) => [p.id, p]));
const bySlug = new Map(INSURANCE_PLANS.map((p) => [p.slug, p]));

export function planById(id: string): InsurancePlan | undefined {
  return byId.get(id);
}

export function planBySlug(slug: string): InsurancePlan | undefined {
  return bySlug.get(slug.toLowerCase());
}
