import type { CruiseLine } from './types';

export const CRUISE_LINES: CruiseLine[] = [
  {
    id: 'royal-caribbean',
    name: 'Royal Caribbean International',
    slug: 'royal-caribbean',
    category: ['Ocean Cruises', 'Family Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'midRange',
    commissionRate: 0.12,
    hqCountry: 'United States',
    description: 'Known for building the world\'s largest, most innovative cruise ships featuring rock-climbing walls, ice-skating rinks, surf simulators, and Broadway-style shows. Ideal for active families and couples.',
    keySellingPoints: ['Perfect Day at CocoCay private island', 'Mega-ships with neighborhood concepts', 'Unmatched family entertainment & kids programs']
  },
  {
    id: 'carnival',
    name: 'Carnival Cruise Line',
    slug: 'carnival',
    category: ['Ocean Cruises', 'Family Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'budget',
    commissionRate: 0.10,
    hqCountry: 'United States',
    description: 'The "Choose Fun" cruise line, offering high-energy, value-packed ocean cruises with water parks, casual dining, and a festive atmosphere. Great for families, groups, and solo travelers.',
    keySellingPoints: ['WaterWorks onboard waterparks', 'Guy Fieri partnerships (Burger Joint/Smokehouse)', 'Fun Ship atmosphere & excellent value']
  },
  {
    id: 'norwegian',
    name: 'Norwegian Cruise Line',
    slug: 'norwegian',
    category: ['Ocean Cruises', 'Family Cruises', 'Solo Cruises' as any],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'midRange',
    commissionRate: 0.12,
    hqCountry: 'United States',
    description: 'Pioneered "Freestyle Cruising" with no set dining times or dress codes. Features impressive entertainment, top-tier restaurants, go-kart racetracks, and dedicated studio cabins for solo travelers.',
    keySellingPoints: ['Freestyle Dining with no set seating times', 'Award-winning entertainment (Broadway shows)', 'Dedicated Solo Cabins & Solo Lounge']
  },
  {
    id: 'msc',
    name: 'MSC Cruises',
    slug: 'msc',
    category: ['Ocean Cruises', 'Family Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'budget',
    commissionRate: 0.10,
    hqCountry: 'Switzerland',
    description: 'A European-inspired cruise line offering modern, stylish mega-ships, an international onboard atmosphere, and a premium "ship-within-a-ship" concept with the MSC Yacht Club.',
    keySellingPoints: ['Ocean Cay MSC Marine Reserve private island', 'MSC Yacht Club VIP experience', 'Kids sail free promotions & family value']
  },
  {
    id: 'princess',
    name: 'Princess Cruises',
    slug: 'princess',
    category: ['Ocean Cruises', 'Seasonal Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'midRange',
    commissionRate: 0.12,
    hqCountry: 'United States',
    description: 'Famous as the cruise line from "The Love Boat." Princess focuses on destination-rich itineraries, culinary excellence, and technological innovation with the MedallionClass experience.',
    keySellingPoints: ['MedallionClass wearable technology', 'Alaska cruise-tours leader', 'Movies Under the Stars poolside screen']
  },
  {
    id: 'celebrity',
    name: 'Celebrity Cruises',
    slug: 'celebrity',
    category: ['Ocean Cruises', 'Luxury Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'premium',
    commissionRate: 0.13,
    hqCountry: 'United States',
    description: 'Offers a "new luxury" experience blending modern design, high-end culinary options, and excellent service. Known for its iconic Lawn Clubs with real grass and Edge-class outward-facing designs.',
    keySellingPoints: ['The Retreat premium suite-class experience', 'Magic Carpet cantilevered platform', 'Lawn Club real grass decks']
  },
  {
    id: 'holland-america',
    name: 'Holland America Line',
    slug: 'holland-america',
    category: ['Ocean Cruises', 'Small Ship Cruises', 'World Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'midRange',
    commissionRate: 0.12,
    hqCountry: 'United States',
    description: 'A classic, refined cruise line specializing in destination immersion, culinary arts, and live music. Attracts mature couples, multi-generational families, and world cruise travelers.',
    keySellingPoints: ['Music Walk live performance venues', 'Culinary Council partnerships with master chefs', 'Spacious, mid-sized traditional ships']
  },
  {
    id: 'disney',
    name: 'Disney Cruise Line',
    slug: 'disney',
    category: ['Ocean Cruises', 'Family Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'premium',
    commissionRate: 0.10,
    hqCountry: 'United States',
    description: 'The ultimate family cruise experience combining legendary Disney service, character meet-and-greets, rotational dining, themed deck parties, and dedicated adults-only areas.',
    keySellingPoints: ['Castaway Cay & Lookout Cay private islands', 'Rotational Dining with the same service team', 'Broadway-caliber Disney stage productions']
  },
  {
    id: 'virgin-voyages',
    name: 'Virgin Voyages',
    slug: 'virgin-voyages',
    category: ['Ocean Cruises', 'Adults-Only Cruises', 'Luxury Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: true,
    luxuryLevel: 'premium',
    commissionRate: 0.15,
    hqCountry: 'United States',
    description: 'An adults-only (18+), luxury-casual cruise line. Replaces buffets and dress codes with 20+ specialty restaurants, yacht-inspired design, dynamic fitness classes, and high-energy nightlife.',
    keySellingPoints: ['Strictly Adults-Only (18+)', 'No buffets, all specialty dining included', 'Gratuities, Wi-Fi, and basic drinks included']
  },
  {
    id: 'cunard',
    name: 'Cunard Line',
    slug: 'cunard',
    category: ['Ocean Cruises', 'Luxury Cruises', 'Repositioning Cruises', 'World Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'premium',
    commissionRate: 0.12,
    hqCountry: 'United Kingdom',
    description: 'Sophisticated ocean liner travel capturing the golden age of ocean travel. Renowned for transatlantic crossings, formal gala nights, white-glove Afternoon Tea, and royal class service.',
    keySellingPoints: ['Transatlantic crossing voyages', 'Queens Grill & Princess Grill luxury tiers', 'Traditional British heritage & formal galas']
  },
  {
    id: 'oceania',
    name: 'Oceania Cruises',
    slug: 'oceania',
    category: ['Ocean Cruises', 'Luxury Cruises', 'Small Ship Cruises', 'World Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'premium',
    commissionRate: 0.14,
    hqCountry: 'United States',
    description: 'Renowned for serving "The Finest Cuisine at Sea," Oceania offers mid-sized, elegant ships that focus on culinary excellence, destination-focused itineraries, and a club-like atmosphere.',
    keySellingPoints: ['The Finest Cuisine at Sea designed by Jacques Pépin', 'Destination-intensive, overnight-heavy itineraries', 'Country club-casual, boutique atmosphere']
  },
  {
    id: 'regent-seven-seas',
    name: 'Regent Seven Seas Cruises',
    slug: 'regent-seven-seas',
    category: ['Luxury Cruises', 'Small Ship Cruises', 'World Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'luxury',
    commissionRate: 0.16,
    hqCountry: 'United States',
    description: 'An ultra-luxury, all-inclusive cruise experience. Fares include round-trip flights, unlimited shore excursions, premium drinks, fine dining, Wi-Fi, laundry service, and gratuities.',
    keySellingPoints: ['Truly All-Inclusive (flights, tours, drinks)', 'All-suite, balcony-heavy fleet', 'Exceptional staff-to-guest ratios']
  },
  {
    id: 'silversea',
    name: 'Silversea Cruises',
    slug: 'silversea',
    category: ['Luxury Cruises', 'Expedition Cruises', 'Small Ship Cruises'],
    riverCruise: false,
    expeditionCruise: true,
    adultsOnly: false,
    luxuryLevel: 'luxury',
    commissionRate: 0.16,
    hqCountry: 'Monaco',
    description: 'An ultra-luxury line known for intimate small ships, butler service for every suite, and a robust fleet of luxury expedition ships sailing to the polar regions and Galapagos.',
    keySellingPoints: ['Personal Butler service for every single suite', 'Expedition cruises to remote regions with Zodiacs', 'All-inclusive gourmet dining & premium beverages']
  },
  {
    id: 'seabourn',
    name: 'Seabourn Cruise Line',
    slug: 'seabourn',
    category: ['Luxury Cruises', 'Small Ship Cruises', 'Expedition Cruises'],
    riverCruise: false,
    expeditionCruise: true,
    adultsOnly: false,
    luxuryLevel: 'luxury',
    commissionRate: 0.16,
    hqCountry: 'United States',
    description: 'Pioneered ultra-luxury cruising with small, yacht-like ships. Features open bars, Caviar in the Surf beach parties, and partnerships with Chef Thomas Keller.',
    keySellingPoints: ['Ultra-luxury yacht atmosphere', 'Partnership with Chef Thomas Keller', 'Caviar in the Surf / Marina platform features']
  },
  {
    id: 'azamara',
    name: 'Azamara',
    slug: 'azamara',
    category: ['Small Ship Cruises', 'Luxury Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'premium',
    commissionRate: 0.14,
    hqCountry: 'United States',
    description: 'A premium boutique line focusing on Destination Immersion. Offers longer stays, overnights in port, and unique cultural experiences like the AzAmazing Evening.',
    keySellingPoints: ['Destination Immersion (long days & overnights)', 'Exclusive "AzAmazing Evenings" private events', 'Small, club-like ships carrying ~700 guests']
  },
  {
    id: 'viking-ocean',
    name: 'Viking Ocean Cruises',
    slug: 'viking-ocean',
    category: ['Ocean Cruises', 'Adults-Only Cruises', 'Small Ship Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: true,
    luxuryLevel: 'premium',
    commissionRate: 0.15,
    hqCountry: 'Switzerland',
    description: 'An adults-only (18+), highly-rated ocean cruise line focusing on history, culture, and science. Free of casinos, children, and hidden fees, with a Nordic design aesthetic.',
    keySellingPoints: ['Strictly Adults-Only (18+)', 'One free shore excursion in every port', 'Elegant Scandinavian design & LivNordic Spa']
  },
  {
    id: 'viking-river',
    name: 'Viking River Cruises',
    slug: 'viking-river',
    category: ['River Cruises', 'Adults-Only Cruises'],
    riverCruise: true,
    expeditionCruise: false,
    adultsOnly: true,
    luxuryLevel: 'premium',
    commissionRate: 0.15,
    hqCountry: 'Switzerland',
    description: 'The world\'s leading river cruise line, operating a massive fleet of Longships across Europe, Egypt, Asia, and the Mississippi. Focuses on local history and culture.',
    keySellingPoints: ['Viking Longships with state-of-the-art design', 'Docking directly in historic city centers', 'Culturally-immersive lectures and local cuisine']
  },
  {
    id: 'amawaterways',
    name: 'AmaWaterways',
    slug: 'amawaterways',
    category: ['River Cruises', 'Family Cruises'],
    riverCruise: true,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'premium',
    commissionRate: 0.15,
    hqCountry: 'United States',
    description: 'A premier river cruise line known for active excursions (carrying a fleet of bicycles), award-winning cuisine, Chef\'s Table dining, and innovative double-balcony suites.',
    keySellingPoints: ['Complimentary bikes & active hiking tours', 'Multi-balcony cabins (french + outside)', 'Chef\'s Table specialty dining included']
  },
  {
    id: 'avalon',
    name: 'Avalon Waterways',
    slug: 'avalon',
    category: ['River Cruises'],
    riverCruise: true,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'premium',
    commissionRate: 0.14,
    hqCountry: 'United States',
    description: 'Known for its "Suite Ships" featuring Panorama Suites with wall-to-wall, floor-to-ceiling windows that open to create a giant Open-Air Balcony. Offers active and discovery cruises.',
    keySellingPoints: ['Panorama Suites with 11-foot open-air windows', 'Beds facing the river views', 'Avalon Choice active/discovery excursion options']
  },
  {
    id: 'scenic',
    name: 'Scenic Cruises',
    slug: 'scenic',
    category: ['River Cruises', 'Luxury Cruises', 'Expedition Cruises'],
    riverCruise: true,
    expeditionCruise: true,
    adultsOnly: false,
    luxuryLevel: 'luxury',
    commissionRate: 0.16,
    hqCountry: 'Australia',
    description: 'Offers 5-star, truly all-inclusive luxury river cruises in Europe and Asia, and ultra-luxury ocean voyages on the Scenic Eclipse "Discovery Yachts" equipped with helicopters and a submarine.',
    keySellingPoints: ['All-inclusive butler service & drinks', 'Scenic Eclipse discovery yachts with sub & helicopters', 'Tailormade GPS audio-guided tours']
  },
  {
    id: 'emerald',
    name: 'Emerald Cruises',
    slug: 'emerald',
    category: ['River Cruises', 'Small Ship Cruises'],
    riverCruise: true,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'midRange',
    commissionRate: 0.12,
    hqCountry: 'Switzerland',
    description: 'A modern, stylish river cruise and luxury yacht line offering excellent value. Features an innovative pool that transforms into a cinema at night on river ships.',
    keySellingPoints: ['Indoor heated pool converting to cinema', 'Modern, minimalist design aesthetic', 'Excellent value luxury-casual river cruising']
  },
  {
    id: 'uniworld',
    name: 'Uniworld Boutique River Cruises',
    slug: 'uniworld',
    category: ['River Cruises', 'Luxury Cruises'],
    riverCruise: true,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'luxury',
    commissionRate: 0.16,
    hqCountry: 'United States',
    description: 'Offers ultra-luxury, boutique river cruises. Each ship is a unique, lavishly designed work of art reflecting the destinations sailed, featuring antique decor and high culinary standards.',
    keySellingPoints: ['One-of-a-kind boutique art-deco ships', 'Farm-to-table dining & unlimited premium spirits', 'All-inclusive gratuities, excursions, and transfers']
  },
  {
    id: 'ponant',
    name: 'Ponant',
    slug: 'ponant',
    category: ['Expedition Cruises', 'Luxury Cruises', 'Small Ship Cruises'],
    riverCruise: false,
    expeditionCruise: true,
    adultsOnly: false,
    luxuryLevel: 'luxury',
    commissionRate: 0.15,
    hqCountry: 'France',
    description: 'A French luxury expedition cruise line. Offers small yacht-like ships, polar expeditions in ultra-luxury comfort, French culinary arts (partnered with Ducasse Conseil), and the Blue Eye underwater lounge.',
    keySellingPoints: ['French chic luxury & gourmet dining', 'High polar ice-class expedition ships', 'Blue Eye multi-sensory underwater lounge']
  },
  {
    id: 'hurtigruten',
    name: 'Hurtigruten',
    slug: 'hurtigruten',
    category: ['Expedition Cruises', 'Seasonal Cruises'],
    riverCruise: false,
    expeditionCruise: true,
    adultsOnly: false,
    luxuryLevel: 'midRange',
    commissionRate: 0.12,
    hqCountry: 'Norway',
    description: 'The global leader in sustainable expedition cruising, sailing Norway\'s coast since 1893. Operates hybrid-powered ships to Antarctica, the Arctic, and Greenland with a focus on science and nature.',
    keySellingPoints: ['Hybrid-powered eco-friendly expedition ships', 'Pioneers of coastal Norway & polar sailing', 'Onboard Science Centers and lecture rooms']
  },
  {
    id: 'windstar',
    name: 'Windstar Cruises',
    slug: 'windstar',
    category: ['Small Ship Cruises', 'Luxury Cruises'],
    riverCruise: false,
    expeditionCruise: false,
    adultsOnly: false,
    luxuryLevel: 'premium',
    commissionRate: 0.14,
    hqCountry: 'United States',
    description: 'Operates a fleet of small, masted sailing ships and luxury all-suite motor yachts. Carrying just 148–342 guests, Windstar accesses small harbors where large ships cannot go.',
    keySellingPoints: ['Iconic masted tall-sailing ships', 'Open bridge policy to interact with officers', 'Watersports platform off the stern of the ship']
  }
];

export const CRUISE_LINES_BY_ID: Record<string, CruiseLine> = Object.fromEntries(
  CRUISE_LINES.map((c) => [c.id, c])
);
