import type { CruisePort } from './types';

export const PORTS: CruisePort[] = [
  // US & Caribbean Ports
  {
    id: 'miami',
    name: 'PortMiami',
    code: 'MIA',
    city: 'Miami',
    country: 'United States',
    countryCode: 'US',
    region: 'Caribbean',
    lat: 25.7781,
    lon: -80.1774,
    overview: 'Known as the "Cruise Capital of the World," PortMiami is the global leader in cruise passengers, featuring stunning futuristic terminals and immediate proximity to downtown Miami and South Beach.',
    history: 'First established in 1897, the port grew rapidly along with the tourism boom of Southern Florida, becoming a dedicated cruise hub in the mid-20th century.',
    thingsToDo: ['Stroll down South Beach', 'Explore Art Deco Historic District', 'Take a food tour in Little Havana', 'Shop at Bayside Marketplace'],
    topAttractions: ['South Beach', 'Vizcaya Museum & Gardens', 'Wynwood Walls', 'Bayside Marketplace'],
    restaurants: ['Joe\'s Stone Crab', 'Versailles Restaurant', 'La Mar by Gastón Acurio'],
    shopping: ['Bayside Marketplace', 'Lincoln Road', 'Brickell City Centre'],
    beaches: ['South Beach', 'Key Biscayne', 'Crandon Park'],
    museums: ['Pérez Art Museum Miami (PAMM)', 'Phillip and Patricia Frost Museum of Science'],
    walkingTours: ['Little Havana Food and Culture Tour', 'Art Deco Architecture Tour'],
    transportation: 'Metrorail, free Coral Way Trolley, rideshares (Uber/Lyft), and taxis.',
    estimatedBudgetUSD: 120,
    accessibility: 'Excellent. Port terminals are fully ADA compliant, and local transport options support wheelchairs.',
    safety: 'Generally safe. Tourists should exercise standard precautions, especially in crowded nightlife areas like South Beach.',
    currency: 'USD',
    languages: ['English', 'Spanish'],
    timeZone: 'EST (UTC-5)',
    visaSummary: 'ESTA or tourist visa required for international visitors.'
  },
  {
    id: 'fort-lauderdale',
    name: 'Port Everglades',
    code: 'FLL',
    city: 'Fort Lauderdale',
    country: 'United States',
    countryCode: 'US',
    region: 'Caribbean',
    lat: 26.0856,
    lon: -80.1206,
    overview: 'A major gateway to the Caribbean, Port Everglades is located next to Fort Lauderdale-Hollywood International Airport, boasting a massive cruise terminal footprint and access to beautiful canals.',
    thingsToDo: ['Ride the Water Taxi through Fort Lauderdale canals', 'Relax on Fort Lauderdale Beach', 'Browse shops on Las Olas Boulevard'],
    topAttractions: ['Las Olas Boulevard', 'Hugh Taylor Birch State Park', 'Museum of Discovery and Science'],
    restaurants: ['Coconuts Seafood', 'Louie Bossi\'s Italian', 'Wild Sea Oyster Bar'],
    shopping: ['Las Olas Boulevard', 'Galleria Mall', 'Sawgrass Mills Outlet'],
    beaches: ['Fort Lauderdale Beach', 'Las Olas Beach'],
    museums: ['NSU Art Museum', 'Bonnet House Museum & Gardens'],
    walkingTours: ['Las Olas Historic Walking Tour'],
    transportation: 'Water Taxi, local buses, Uber/Lyft, and taxis.',
    estimatedBudgetUSD: 100,
    accessibility: 'High accessibility across terminals and major tourist sites.',
    safety: 'Very safe for tourists. Follow standard safety precautions.',
    currency: 'USD',
    languages: ['English'],
    timeZone: 'EST (UTC-5)',
    visaSummary: 'ESTA or visa required for foreign nationals.'
  },
  {
    id: 'port-canaveral',
    name: 'Port Canaveral',
    code: 'PCN',
    city: 'Port Canaveral',
    country: 'United States',
    countryCode: 'US',
    region: 'Caribbean',
    lat: 28.4116,
    lon: -80.6156,
    overview: 'The primary port for Orlando, offering cruisers access to the Kennedy Space Center, Cocoa Beach, and Central Florida theme parks.',
    thingsToDo: ['Visit Kennedy Space Center', 'Surf at Cocoa Beach', 'Explore Exploration Tower'],
    topAttractions: ['Kennedy Space Center Visitor Complex', 'Cocoa Beach Pier', 'Exploration Tower'],
    restaurants: ['Grills Seafood Deck & Tiki Bar', 'Rusty\'s Seafood', 'Fishlips Waterfront Bar & Grill'],
    shopping: ['Ron Jon Surf Shop', 'Historic Cocoa Village'],
    beaches: ['Cocoa Beach', 'Jetty Park Beach'],
    museums: ['Air Force Space and Missile Museum'],
    walkingTours: ['Space Coast Nature Walking Tour'],
    transportation: 'Car rentals, theme park shuttles, taxis, and rideshares.',
    estimatedBudgetUSD: 130,
    accessibility: 'Good. Space Center and cruise terminals are highly accessible.',
    safety: 'Very safe. Typical low-crime coastal area.',
    currency: 'USD',
    languages: ['English'],
    timeZone: 'EST (UTC-5)',
    visaSummary: 'ESTA/visa required for international guests.'
  },
  {
    id: 'galveston',
    name: 'Port of Galveston',
    code: 'GAL',
    city: 'Galveston',
    country: 'United States',
    countryCode: 'US',
    region: 'Caribbean',
    lat: 29.3096,
    lon: -94.7932,
    overview: 'Texas\' premier cruise port, serving the Gulf Coast and Southern US. Historic Strand district is adjacent to the cruise terminals.',
    thingsToDo: ['Walk the historic Strand District', 'Visit Moody Gardens', 'Enjoy Galveston Island Historic Pleasure Pier'],
    topAttractions: ['Moody Gardens', 'The Strand', 'Pleasure Pier', 'Bishop\'s Palace'],
    restaurants: ['Gaido\'s Seafood', 'Rudy & Paco Restaurant', 'Miller\'s Seawall Grill'],
    shopping: ['Historic Strand Shops', 'Postoffice Street galleries'],
    beaches: ['Stewart Beach', 'East Beach'],
    museums: ['Galveston Railroad Museum', 'Texas Seaport Museum & ELISSA'],
    walkingTours: ['Strand Historic District Ghost Tour'],
    transportation: 'Trolley buses, taxis, and rideshares.',
    estimatedBudgetUSD: 85,
    accessibility: 'Good access in historic areas, though some cobblestones exist.',
    safety: 'Generally safe. Seawall and Strand are safe during day/evening.',
    currency: 'USD',
    languages: ['English', 'Spanish'],
    timeZone: 'CST (UTC-6)',
    visaSummary: 'ESTA/US visa required for non-US travelers.'
  },
  {
    id: 'nassau',
    name: 'Nassau Cruise Port',
    code: 'NAS',
    city: 'Nassau',
    country: 'Bahamas',
    countryCode: 'BS',
    region: 'Bahamas',
    lat: 25.0784,
    lon: -77.3403,
    overview: 'A completely revitalized port with modern cruise terminals, offering cruisers immediate access to white-sand beaches, colonial fortresses, and luxury resorts like Atlantis.',
    thingsToDo: ['Visit Atlantis Resort & Aquaventure', 'Climb the Queen\'s Staircase', 'Taste rum at John Watling\'s Distillery', 'Snorkel at Cabbage Beach'],
    topAttractions: ['Atlantis Paradise Island', 'Queen\'s Staircase', 'Fort Fincastle', 'Straw Market'],
    restaurants: ['Graycliff Restaurant', 'The Poop Deck', 'Twin Brothers Fish Fry'],
    shopping: ['Bay Street duty-free shops', 'Nassau Straw Market'],
    beaches: ['Cabbage Beach', 'Junkanoo Beach', 'Cable Beach'],
    museums: ['Pirates of Nassau Museum', 'National Art Gallery of the Bahamas'],
    walkingTours: ['Colonial Nassau Historic Walking Tour'],
    transportation: 'Jitney buses (public minibuses), water taxis to Paradise Island, and licensed taxis.',
    estimatedBudgetUSD: 95,
    accessibility: 'Good. The newly renovated port area is flat and wheelchair friendly.',
    safety: 'Moderate. Stay in designated tourist areas and avoid carrying large amounts of cash.',
    currency: 'BSD (USD widely accepted)',
    languages: ['English'],
    timeZone: 'EST (UTC-5)',
    visaSummary: 'Visa-free for US, Canada, UK, and EU citizens for short visits.'
  },
  {
    id: 'cozumel',
    name: 'Puerta Maya & Punta Langosta',
    code: 'CZM',
    city: 'Cozumel',
    country: 'Mexico',
    countryCode: 'MX',
    region: 'Caribbean',
    lat: 20.4764,
    lon: -86.9742,
    overview: 'Mexico\'s largest cruise island, famous for its crystal-clear waters, vibrant coral reefs, snorkeling, and Mayan ruin shore excursions.',
    thingsToDo: ['Snorkel or dive the Palancar Reef', 'Explore San Gervasio Mayan ruins', 'Relax at Playa Mia Beach Club', 'Take a ferry to Playa del Carmen'],
    topAttractions: ['Chankanaab Adventure Beach Park', 'Palancar Reef', 'Punta Sur Eco Beach Park', 'San Miguel town center'],
    restaurants: ['Casa Mission', 'La Choza', 'Guido\'s Restaurant'],
    shopping: ['Plaza Del Sol duty-free', 'Royal Village Cozumel'],
    beaches: ['Playa Mia', 'Playa Palancar', 'Paradise Beach'],
    museums: ['Cozumel Island Museum'],
    walkingTours: ['San Miguel Food and Tequila Tour'],
    transportation: 'Taxis (regulated fares), scooter rentals, and ferries to mainland.',
    estimatedBudgetUSD: 75,
    accessibility: 'Excellent. Main piers and tourist centers have accessible ramps.',
    safety: 'Very safe. Cozumel is one of the safest tourist destinations in Mexico.',
    currency: 'MXN (USD widely accepted)',
    languages: ['Spanish', 'English'],
    timeZone: 'EST (UTC-5 - Cozumel does not observe DST)',
    visaSummary: 'FMM tourist card required (usually provided onboard / visa-free for major markets).'
  },

  // Mediterranean Ports
  {
    id: 'barcelona',
    name: 'Port de Barcelona',
    code: 'BCN',
    city: 'Barcelona',
    country: 'Spain',
    countryCode: 'ES',
    region: 'Mediterranean',
    lat: 41.3772,
    lon: 2.1812,
    overview: 'Europe\'s busiest cruise port, directly connected to the historic center of Barcelona. Perfect starting point for Mediterranean cruises, characterized by Gaudí\'s architecture.',
    thingsToDo: ['Visit La Sagrada Família', 'Walk down La Rambla', 'Explore the Gothic Quarter', 'See Park Güell'],
    topAttractions: ['La Sagrada Família', 'Gothic Quarter (Barri Gòtic)', 'Park Güell', 'Casa Batlló'],
    restaurants: ['7 Portes', 'Botafumeiro', 'El Nacional'],
    shopping: ['Passeig de Gràcia', 'La Boqueria Market', 'Portal de l\'Àngel'],
    beaches: ['Barceloneta Beach', 'Bogatell Beach'],
    museums: ['Picasso Museum', 'Joan Miró Foundation', 'National Art Museum of Catalonia (MNAC)'],
    walkingTours: ['Gothic Quarter Walking Tour', 'Gaudí Architecture Walking Tour'],
    transportation: 'Metro system, Portbus shuttle to cruise terminals, taxis, and public buses.',
    estimatedBudgetUSD: 90,
    accessibility: 'Very High. Barcelona\'s public transport and major museums are exceptionally wheelchair-friendly.',
    safety: 'Generally safe, but pickpocketing is very common on La Rambla and the Metro. Stay vigilant.',
    currency: 'EUR',
    languages: ['Spanish', 'Catalan', 'English'],
    timeZone: 'CET (UTC+1)',
    visaSummary: 'Schengen Visa rules apply (Visa-free for US/CA/UK/AU/etc.).'
  },
  {
    id: 'civitavecchia',
    name: 'Port of Civitavecchia (Rome)',
    code: 'CVV',
    city: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    region: 'Mediterranean',
    lat: 42.0963,
    lon: 11.7891,
    overview: 'The maritime gateway to Rome, located 80km northwest of the Eternal City. Trains connect Civitavecchia directly to Rome\'s Termini station.',
    thingsToDo: ['Visit the Colosseum and Roman Forum', 'Explore Vatican City (St. Peter\'s & Sistine Chapel)', 'Toss a coin in the Trevi Fountain', 'Walk around historic Civitavecchia fort'],
    topAttractions: ['Colosseum', 'Vatican Museums', 'Trevi Fountain', 'Pantheon'],
    restaurants: ['La Pergola', 'Armando al Pantheon', 'Da Enzo al 29'],
    shopping: ['Via del Corso', 'Via Condotti'],
    beaches: ['Santa Marinella (near Civitavecchia)'],
    museums: ['Vatican Museums', 'Borghese Gallery', 'Capitoline Museums'],
    walkingTours: ['Ancient Rome Archeological Walking Tour', 'Vatican Guided Tour'],
    transportation: 'Regional trains (FL5 line to Rome), excursion buses, taxis.',
    estimatedBudgetUSD: 110,
    accessibility: 'Moderate. Rome has ancient cobblestone streets which present challenges; modern train stations have lifts.',
    safety: 'Safe, but watch out for pickpockets at tourist landmarks and crowded trains.',
    currency: 'EUR',
    languages: ['Italian', 'English'],
    timeZone: 'CET (UTC+1)',
    visaSummary: 'Schengen Area rules apply.'
  },
  {
    id: 'piraeus',
    name: 'Port of Piraeus (Athens)',
    code: 'PIR',
    city: 'Athens',
    country: 'Greece',
    countryCode: 'GR',
    region: 'Mediterranean',
    lat: 37.9372,
    lon: 23.6349,
    overview: 'The largest passenger port in Europe, linking international cruise ships to the Acropolis and the ancient historical ruins of Athens.',
    thingsToDo: ['Climb the Acropolis to see the Parthenon', 'Walk through the old Plaka neighborhood', 'Visit the Acropolis Museum', 'Watch the changing of the guard at Syntagma Square'],
    topAttractions: ['Acropolis & Parthenon', 'Acropolis Museum', 'Ancient Agora of Athens', 'Plaka district'],
    restaurants: ['Spondi', 'Strofi Tavern', 'Mani Mani'],
    shopping: ['Ermou Street', 'Monastiraki Flea Market'],
    beaches: ['Glyfada Beach (Athens Riviera)'],
    museums: ['National Archaeological Museum', 'Acropolis Museum'],
    walkingTours: ['Acropolis & Plaka Guided Walking Tour'],
    transportation: 'Athens Metro (Line 1 from Piraeus), Hop-On Hop-Off buses, taxis.',
    estimatedBudgetUSD: 80,
    accessibility: 'Good. The Acropolis has a wheelchair lift, and the Acropolis Museum is fully accessible.',
    safety: 'Safe. Standard precautions against petty theft in metro trains and crowded squares.',
    currency: 'EUR',
    languages: ['Greek', 'English'],
    timeZone: 'EET (UTC+2)',
    visaSummary: 'Schengen Area rules apply.'
  },

  // Northern Europe & British Isles
  {
    id: 'southampton',
    name: 'Port of Southampton',
    code: 'SOU',
    city: 'Southampton',
    country: 'United Kingdom',
    countryCode: 'GB',
    region: 'Northern Europe',
    lat: 50.9081,
    lon: -1.4116,
    overview: 'The UK\'s busiest cruise port, legendary as the departure port of the Titanic and the traditional home of transatlantic crossings.',
    thingsToDo: ['Visit the SeaCity Museum (Titanic exhibit)', 'Explore the medieval city walls', 'Take a day trip to Stonehenge', 'Shop at Westquay'],
    topAttractions: ['SeaCity Museum', 'Tudor House and Garden', 'Stonehenge (day trip)', 'New Forest National Park'],
    restaurants: ['The Jetty', 'Coriander Lounge', 'Oxford Street bistros'],
    shopping: ['Westquay Shopping Centre', 'High Street'],
    beaches: ['Calshot Spit'],
    museums: ['SeaCity Museum', 'Solent Sky Aviation Museum'],
    walkingTours: ['Titanic Trail Historical Walking Tour'],
    transportation: 'Trains to London Waterloo (75 mins), local buses, and taxis.',
    estimatedBudgetUSD: 110,
    accessibility: 'High. Cruise terminals are modern, and public transit is highly accessible.',
    safety: 'Very safe. Typical low-crime UK city.',
    currency: 'GBP',
    languages: ['English'],
    timeZone: 'GMT (UTC+0)',
    visaSummary: 'UK visa regulations apply (Visa-free for US/CA/EU/AU citizens).'
  },
  {
    id: 'amsterdam-port',
    name: 'Passenger Terminal Amsterdam',
    code: 'AMS',
    city: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    region: 'Northern Europe',
    lat: 52.3783,
    lon: 4.9142,
    overview: 'Located in the heart of the city, just a short walk from Central Station. Serves as a key hub for Baltic and Norwegian Fjord voyages.',
    thingsToDo: ['Take a canal cruise', 'Visit the Rijksmuseum and Van Gogh Museum', 'Stroll through the Jordaan district', 'Explore the Anne Frank House'],
    topAttractions: ['Rijksmuseum', 'Van Gogh Museum', 'Anne Frank House', 'Canal Ring'],
    restaurants: ['De Kas', 'Rijks', 'Restaurant Breda'],
    shopping: ['Nine Streets (Negen Straatjes)', 'Kalverstraat'],
    beaches: ['Zandvoort (short train ride)'],
    museums: ['Rijksmuseum', 'Van Gogh Museum', 'Stedelijk Museum'],
    walkingTours: ['Historic Amsterdam Canal & Culture Walking Tour'],
    transportation: 'Trams, canal boats, bicycle rentals, trains from Central Station.',
    estimatedBudgetUSD: 115,
    accessibility: 'High. Most museums have ramps and lifts, though historic canal boats might have steps.',
    safety: 'Very safe. Be mindful of bicycle lanes and pickpockets in tourist centers.',
    currency: 'EUR',
    languages: ['Dutch', 'English'],
    timeZone: 'CET (UTC+1)',
    visaSummary: 'Schengen Area rules apply.'
  },

  // Alaska & West Coast Ports
  {
    id: 'seattle-port',
    name: 'Bell Street Pier & Smith Cove Terminals',
    code: 'SEA',
    city: 'Seattle',
    country: 'United States',
    countryCode: 'US',
    region: 'Alaska',
    lat: 47.6097,
    lon: -122.3422,
    overview: 'The primary US homeport for Alaska cruises, offering scenic departures down the Puget Sound. Terminals are located close to downtown landmarks.',
    thingsToDo: ['Visit Pike Place Market', 'Go up the Space Needle', 'Explore Chihuly Garden and Glass', 'Take a ferry to Bainbridge Island'],
    topAttractions: ['Pike Place Market', 'Space Needle', 'Chihuly Garden and Glass', 'Seattle Waterfront'],
    restaurants: ['The Pink Door', 'Dahlia Lounge', 'Ivar\'s Acres of Clams'],
    shopping: ['Pike Place Market retail', 'Downtown retail district'],
    beaches: ['Alki Beach'],
    museums: ['Museum of Pop Culture (MoPOP)', 'Seattle Art Museum'],
    walkingTours: ['Seattle Underground Walking Tour'],
    transportation: 'Link Light Rail, Monorail, ferries, rideshares, and taxis.',
    estimatedBudgetUSD: 120,
    accessibility: 'Excellent. Cruise terminals and light rail are highly accessible.',
    safety: 'Generally safe, but standard city caution is recommended in downtown areas after dark.',
    currency: 'USD',
    languages: ['English'],
    timeZone: 'PST (UTC-8)',
    visaSummary: 'ESTA/US visa required for foreign nationals.'
  },
  {
    id: 'vancouver-port',
    name: 'Canada Place Cruise Ship Terminal',
    code: 'YVR',
    city: 'Vancouver',
    country: 'Canada',
    countryCode: 'CA',
    region: 'Alaska',
    lat: 49.2888,
    lon: -123.1111,
    overview: 'An iconic sails-shaped building in downtown Vancouver, serving as the main gateway to Alaska\'s Inside Passage. Highly praised for scenery and efficiency.',
    thingsToDo: ['Bike around Stanley Park seawall', 'Walk across the Capilano Suspension Bridge', 'Explore historic Gastown', 'Take a water taxi to Granville Island'],
    topAttractions: ['Stanley Park', 'Capilano Suspension Bridge', 'Granville Island Public Market', 'Gastown Steam Clock'],
    restaurants: ['Blue Water Cafe', 'Miku Restaurant', 'Chambar'],
    shopping: ['Granville Island Market', 'Robson Street'],
    beaches: ['English Bay Beach', 'Kitsilano Beach'],
    museums: ['Museum of Anthropology (MOA)', 'Vancouver Art Gallery'],
    walkingTours: ['Gastown Historic Walking Tour'],
    transportation: 'SkyTrain metro system, Aquabus ferry, local buses, taxis.',
    estimatedBudgetUSD: 110,
    accessibility: 'Excellent. Canada Place terminal is modern and highly accessible.',
    safety: 'Very safe. Clean city with low violent crime rates.',
    currency: 'CAD',
    languages: ['English', 'French'],
    timeZone: 'PST (UTC-8)',
    visaSummary: 'eTA or tourist visa required for international visitors.'
  },
  {
    id: 'juneau',
    name: 'Juneau Cruise Port',
    code: 'JNU',
    city: 'Juneau',
    country: 'United States',
    countryCode: 'US',
    region: 'Alaska',
    lat: 58.3019,
    lon: -134.4197,
    overview: 'Alaska\'s capital city, accessible only by sea or air. Highlights include the Mendenhall Glacier, dog sledding, and whale watching.',
    thingsToDo: ['Visit Mendenhall Glacier', 'Go whale watching in Auke Bay', 'Ride the Goldbelt Mount Roberts Tramway', 'Eat fresh salmon at a salmon bake'],
    topAttractions: ['Mendenhall Glacier', 'Mount Roberts Tramway', 'Tracy Arm Fjord (excursion)', 'Red Dog Saloon'],
    restaurants: ['Tracy\'s King Crab Shack', 'The Hangar on the Wharf', 'Salt'],
    shopping: ['Franklin Street souvenirs', 'Local Native Alaskan art galleries'],
    beaches: ['Sandy Beach (Douglas Island)'],
    museums: ['Alaska State Museum', 'Juneau-Douglas City Museum'],
    walkingTours: ['Juneau Gold Rush Historical Walking Tour'],
    transportation: 'Glacier shuttle buses, shore excursion buses, taxis.',
    estimatedBudgetUSD: 140,
    accessibility: 'Good. Goldbelt Tram is wheelchair accessible; shuttle buses offer ramp options.',
    safety: 'Extremely safe. Typical welcoming Alaskan community.',
    currency: 'USD',
    languages: ['English'],
    timeZone: 'AKST (UTC-9)',
    visaSummary: 'US visa rules apply.'
  },

  // Asia & Oceania Ports
  {
    id: 'singapore-port',
    name: 'Marina Bay Cruise Centre & HarbourFront',
    code: 'SIN',
    city: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    region: 'Southeast Asia',
    lat: 1.2711,
    lon: 103.8597,
    overview: 'A world-class, ultra-modern terminal located in Marina Bay. Serves as the premier cruise hub of Southeast Asia, connecting to futuristic Gardens by the Bay.',
    thingsToDo: ['Explore Gardens by the Bay', 'Enjoy food at Lau Pa Sat hawker center', 'Stroll along the Marina Bay Waterfront', 'Visit Sentosa Island'],
    topAttractions: ['Gardens by the Bay', 'Marina Bay Sands SkyPark', 'Singapore Botanic Gardens', 'Sentosa Island'],
    restaurants: ['Odette', 'Jumbo Seafood', 'Liao Fan Hawker Chan (Michelin street food)'],
    shopping: ['Orchard Road malls', 'Chinatown', 'Marina Bay Sands Shoppes'],
    beaches: ['Siloso Beach (Sentosa)', 'Palawan Beach'],
    museums: ['ArtScience Museum', 'National Gallery Singapore'],
    walkingTours: ['Chinatown Heritage Trail', 'Kampong Glam & Little India Culture Tour'],
    transportation: 'MRT (Mass Rapid Transit) trains, public buses, Grab rideshares, and clean taxis.',
    estimatedBudgetUSD: 100,
    accessibility: 'Exceptional. Singapore is one of the most wheelchair-accessible cities in the world.',
    safety: 'Virtually crime-free. Extremely safe for solo and night travelers.',
    currency: 'SGD',
    languages: ['English', 'Mandarin', 'Malay', 'Tamil'],
    timeZone: 'SGT (UTC+8)',
    visaSummary: 'SG Arrival Card must be filled out online before entry (Visa-free for most).'
  },
  {
    id: 'tokyo-port',
    name: 'Tokyo International Cruise Terminal',
    code: 'TYO',
    city: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    region: 'Japan',
    lat: 35.6172,
    lon: 139.7758,
    overview: 'A newly built state-of-the-art terminal on Odaiba, offering easy access to Tokyo\'s legendary transit network and sights.',
    thingsToDo: ['Visit Senso-ji Temple in Asakusa', 'Experience Shibuya Crossing', 'See digital art at teamLab Planets', 'Eat sushi at Tsukiji Outer Market'],
    topAttractions: ['Senso-ji Temple', 'Shibuya Crossing', 'Tokyo Skytree', 'Meiji Jingu Shrine'],
    restaurants: ['Sukiyabashi Jiro', 'Ippudo Ramen', 'Tofuya Ukai'],
    shopping: ['Ginza retail stores', 'Shibuya', 'Akihabara electric town'],
    beaches: ['Odaiba Beach (scenic view only, no swimming)'],
    museums: ['Tokyo National Museum', 'Mori Art Museum', 'Edo-Tokyo Museum'],
    walkingTours: ['Asakusa Historic Walking Tour', 'Harajuku & Shibuya Youth Culture Tour'],
    transportation: 'Yurikamome monorail line, Tokyo Metro subways, taxis.',
    estimatedBudgetUSD: 100,
    accessibility: 'Very High. Elevators are standard in stations, and sidewalks are smooth.',
    safety: 'One of the safest capitals in the world. Extremely safe.',
    currency: 'JPY',
    languages: ['Japanese', 'English'],
    timeZone: 'JST (UTC+9)',
    visaSummary: 'Visa waiver agreement in place for citizens of 68 countries.'
  },
  {
    id: 'sydney-port',
    name: 'Overseas Passenger Terminal & White Bay',
    code: 'SYD',
    city: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    region: 'Australia',
    lat: -33.8583,
    lon: 151.2097,
    overview: 'The Overseas Passenger Terminal sits directly opposite the Sydney Opera House in Circular Quay, providing one of the most spectacular cruise arrivals in the world.',
    thingsToDo: ['Take a guided tour of the Sydney Opera House', 'Walk across the Sydney Harbour Bridge', 'Catch a ferry to Manly or Watson\'s Bay', 'Sunbathe at Bondi Beach'],
    topAttractions: ['Sydney Opera House', 'Sydney Harbour Bridge', 'Royal Botanic Garden', 'Darling Harbour'],
    restaurants: ['Quay', 'Tetsuya\'s', 'Bennelong'],
    shopping: ['Queen Victoria Building (QVB)', 'Pitt Street Mall'],
    beaches: ['Bondi Beach', 'Manly Beach', 'Balmoral Beach'],
    museums: ['Australian Museum', 'Art Gallery of New South Wales'],
    walkingTours: ['The Rocks Historic Ghost and Convict Tour'],
    transportation: 'Sydney Trains, public ferries from Circular Quay, light rail, and taxis.',
    estimatedBudgetUSD: 110,
    accessibility: 'High. Smooth pathways around Circular Quay and accessible trains.',
    safety: 'Very safe. Typical safe Western metropolis.',
    currency: 'AUD',
    languages: ['English'],
    timeZone: 'AEST (UTC+10)',
    visaSummary: 'Electronic Travel Authority (ETA) required before arrival for most passport holders.'
  },

  // River Ports
  {
    id: 'vienna-port',
    name: 'Reichsbrücke Danube Port',
    code: 'VIE',
    city: 'Vienna',
    country: 'Austria',
    countryCode: 'AT',
    region: 'Danube River',
    lat: 48.2272,
    lon: 16.4056,
    overview: 'The main docking area for Danube river cruises, located a few subway stops from Vienna\'s historic ring road and classical palaces.',
    thingsToDo: ['Tour Schönbrunn Palace', 'Attend a classical concert', 'Eat Sachertorte at a Viennese cafe', 'See Gustav Klimt\'s "The Kiss" at Belvedere Palace'],
    topAttractions: ['Schönbrunn Palace', 'St. Stephen\'s Cathedral', 'Belvedere Palace', 'Hofburg Palace'],
    restaurants: ['Steirereck', 'Plachutta Wollzeile', 'Figlmüller (famous schnitzel)'],
    shopping: ['Kärntner Straße', 'Naschmarkt'],
    beaches: ['Donauinsel (Danube Island recreational beach)'],
    museums: ['Kunsthistorisches Museum', 'Albertina', 'Leopold Museum'],
    walkingTours: ['Historic Vienna Ringstrasse Walking Tour'],
    transportation: 'Vienna U-Bahn (Subway Line U1 from port), trams, and taxis.',
    estimatedBudgetUSD: 95,
    accessibility: 'Excellent. Public transit is highly accessible, and palace grounds offer ramps.',
    safety: 'Extremely safe. Consistently ranked among the world\'s most liveable and safe cities.',
    currency: 'EUR',
    languages: ['German', 'English'],
    timeZone: 'CET (UTC+1)',
    visaSummary: 'Schengen Area rules apply.'
  },
  {
    id: 'budapest-port',
    name: 'Budapest River Cruise Terminal',
    code: 'BUD',
    city: 'Budapest',
    country: 'Hungary',
    countryCode: 'HU',
    region: 'Danube River',
    lat: 47.4984,
    lon: 19.0489,
    overview: 'River boats dock directly in the heart of the city, along the banks of the Danube between the Chain Bridge and Elizabeth Bridge, offering views of the illuminated Parliament Building.',
    thingsToDo: ['Soak in Széchenyi or Gellért Thermal Baths', 'Take photos at Fisherman\'s Bastion', 'Visit the Hungarian Parliament Building', 'Have a drink at a classic Ruin Bar'],
    topAttractions: ['Hungarian Parliament', 'Fisherman\'s Bastion', 'Buda Castle', 'Chain Bridge'],
    restaurants: ['Onyx', 'Gundel Restaurant', 'Borkonyha Winekitchen'],
    shopping: ['Great Market Hall', 'Váci Street'],
    beaches: ['Margaret Island baths'],
    museums: ['Hungarian National Museum', 'House of Terror'],
    walkingTours: ['Buda Castle Hill Historical Walking Tour', 'Jewish Quarter & Ruin Bar Tour'],
    transportation: 'Tram system (Scenic Tram 2 along river), metro, and taxis.',
    estimatedBudgetUSD: 70,
    accessibility: 'Moderate. Historical sites on Castle Hill have cobblestones and steep slopes.',
    safety: 'Safe. Watch out for taxi scams (use official apps like Bolt) and pickpockets.',
    currency: 'HUF (EUR accepted in tourist areas)',
    languages: ['Hungarian', 'English'],
    timeZone: 'CET (UTC+1)',
    visaSummary: 'Schengen Area rules apply.'
  },
  {
    id: 'strasbourg-port',
    name: 'Port of Strasbourg',
    code: 'SXB',
    city: 'Strasbourg',
    country: 'France',
    countryCode: 'FR',
    region: 'Rhine River',
    lat: 48.5734,
    lon: 7.7956,
    overview: 'Located on the Rhine river bordering Germany, Strasbourg features a beautiful historic center (Grande Île) known for half-timbered houses and canal locks.',
    thingsToDo: ['Explore Petite France neighborhood', 'Visit Strasbourg Cathedral', 'Take a boat tour on the Ill river', 'Taste Alsatian wine'],
    topAttractions: ['Strasbourg Cathedral (Notre-Dame)', 'Petite France district', 'European Parliament', 'Palais Rohan'],
    restaurants: ['Maison Kammerzell', 'Le Crocodile', 'Winstub Le Clou'],
    shopping: ['Place Kleber shops', 'Alsatian food markets'],
    beaches: ['None'],
    museums: ['Alsatian Museum', 'Museum of Modern and Contemporary Art'],
    walkingTours: ['Grande Île & Petite France Canal Walking Tour'],
    transportation: 'Modern tram system, bicycle rentals, walking.',
    estimatedBudgetUSD: 95,
    accessibility: 'High. The city center is flat and pedestrianized with accessible trams.',
    safety: 'Very safe. Quiet and highly secure city.',
    currency: 'EUR',
    languages: ['French', 'German', 'English'],
    timeZone: 'CET (UTC+1)',
    visaSummary: 'Schengen Area rules apply.'
  },

  // Hawaii & West Coast Ports
  {
    id: 'honolulu',
    name: 'Honolulu Harbor Cruise Terminal',
    code: 'HNL',
    city: 'Honolulu',
    country: 'United States',
    countryCode: 'US',
    region: 'Hawaii',
    lat: 21.3069,
    lon: -157.8583,
    overview: 'The hub for interisland Hawaii cruising, docking a short walk from Waikiki Beach and Honolulu\'s Aloha Tower Marketplace.',
    history: 'Honolulu Harbor has served as Oahu\'s primary port since the 19th century, historically the arrival point for sugar trade and now cruise and cargo traffic.',
    thingsToDo: ['Relax on Waikiki Beach', 'Climb Diamond Head Crater', 'Visit Pearl Harbor & USS Arizona Memorial', 'Explore Iolani Palace'],
    topAttractions: ['Diamond Head State Monument', 'Pearl Harbor National Memorial', 'Waikiki Beach', 'Iolani Palace'],
    restaurants: ['Duke\'s Waikiki', 'Helena\'s Hawaiian Food', 'Alan Wong\'s Honolulu'],
    shopping: ['Ala Moana Center', 'International Market Place'],
    beaches: ['Waikiki Beach', 'Ala Moana Beach Park'],
    museums: ['Bishop Museum', 'USS Bowfin Submarine Museum'],
    walkingTours: ['Historic Waikiki & Aloha Tower Walking Tour'],
    transportation: 'TheBus public transit, rideshares, and the Waikiki Trolley.',
    estimatedBudgetUSD: 140,
    accessibility: 'Good. Waikiki and the cruise pier area are flat and wheelchair-friendly.',
    safety: 'Very safe for tourists in Waikiki and downtown; standard beach safety precautions apply.',
    currency: 'USD',
    languages: ['English', 'Hawaiian'],
    timeZone: 'HST (UTC-10)',
    visaSummary: 'ESTA/US visa required for foreign nationals.'
  },
  {
    id: 'los-angeles-port',
    name: 'Port of Los Angeles (San Pedro / World Cruise Center)',
    code: 'LAX',
    city: 'Los Angeles',
    country: 'United States',
    countryCode: 'US',
    region: 'Mexican Riviera',
    lat: 33.7395,
    lon: -118.2610,
    overview: 'The World Cruise Center in San Pedro is the primary Southern California gateway to the Mexican Riviera, Panama Canal, and Hawaii sailings.',
    thingsToDo: ['Walk the San Pedro waterfront', 'Day trip to Hollywood & the Walk of Fame', 'Visit the Aquarium of the Pacific in Long Beach', 'Explore Santa Monica Pier'],
    topAttractions: ['Hollywood Walk of Fame', 'Santa Monica Pier', 'Griffith Observatory', 'Aquarium of the Pacific'],
    restaurants: ['San Pedro Fish Market', 'Ports O\' Call dining', 'Republique (Hollywood)'],
    shopping: ['Ports O\' Call Village', 'Del Amo Fashion Center'],
    beaches: ['Cabrillo Beach', 'Santa Monica Beach'],
    museums: ['Battleship USS Iowa Museum', 'Los Angeles Maritime Museum'],
    walkingTours: ['San Pedro Waterfront Walking Tour'],
    transportation: 'Car rentals, Metro Rail (with transfer), rideshares, and shuttle buses.',
    estimatedBudgetUSD: 130,
    accessibility: 'High. Terminal and San Pedro waterfront are fully accessible.',
    safety: 'Generally safe; typical big-city caution recommended after dark.',
    currency: 'USD',
    languages: ['English', 'Spanish'],
    timeZone: 'PST (UTC-8)',
    visaSummary: 'ESTA/US visa required for foreign nationals.'
  },

  // Northern Europe & Baltic Ports
  {
    id: 'copenhagen-port',
    name: 'Copenhagen Cruise Terminal (Oceankaj)',
    code: 'CPH',
    city: 'Copenhagen',
    country: 'Denmark',
    countryCode: 'DK',
    region: 'Baltic Sea',
    lat: 55.7058,
    lon: 12.6119,
    overview: 'A major turnaround port for Baltic Sea cruises, close to Tivoli Gardens, colorful Nyhavn harbor, and Scandinavian design boutiques.',
    thingsToDo: ['Wander the colorful Nyhavn harbor', 'Visit Tivoli Gardens amusement park', 'See the Little Mermaid statue', 'Tour Rosenborg Castle'],
    topAttractions: ['Nyhavn', 'Tivoli Gardens', 'The Little Mermaid', 'Rosenborg Castle'],
    restaurants: ['Noma', 'Torvehallerne food market', 'Restaurant Amass'],
    shopping: ['Strøget pedestrian shopping street', 'Torvehallerne Market'],
    beaches: ['Amager Strandpark'],
    museums: ['National Museum of Denmark', 'Ny Carlsberg Glyptotek'],
    walkingTours: ['Historic Copenhagen Canal & Castle Walking Tour'],
    transportation: 'Metro, harbor buses, bicycle rentals, and taxis.',
    estimatedBudgetUSD: 130,
    accessibility: 'Excellent. Copenhagen is flat, bike-friendly, and highly accessible.',
    safety: 'Extremely safe. Consistently ranked among the world\'s safest cities.',
    currency: 'DKK',
    languages: ['Danish', 'English'],
    timeZone: 'CET (UTC+1)',
    visaSummary: 'Schengen Area rules apply.'
  },

  // South America & Antarctica Ports
  {
    id: 'buenos-aires-port',
    name: 'Buenos Aires Cruise Terminal (Puerto Madero)',
    code: 'BUE',
    city: 'Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    region: 'South America',
    lat: -34.5875,
    lon: -58.3689,
    overview: 'The main homeport for South America cruises, located beside the revitalized Puerto Madero docklands and a short ride from the tango halls of San Telmo.',
    thingsToDo: ['Watch a tango show in San Telmo', 'Walk the colorful streets of La Boca', 'Tour Recoleta Cemetery', 'Stroll Puerto Madero docklands'],
    topAttractions: ['La Boca / Caminito', 'Recoleta Cemetery', 'Teatro Colón', 'Puerto Madero'],
    restaurants: ['Don Julio', 'La Cabrera', 'El Preferido de Palermo'],
    shopping: ['Florida Street', 'Palermo Soho boutiques'],
    beaches: ['None (river port; day trips to Uruguay beaches)'],
    museums: ['MALBA (Latin American Art Museum)', 'Museo Nacional de Bellas Artes'],
    walkingTours: ['San Telmo & La Boca Tango Walking Tour'],
    transportation: 'Subte metro, buses, and taxis.',
    estimatedBudgetUSD: 90,
    accessibility: 'Moderate. Puerto Madero is modern and accessible; older barrios have uneven sidewalks.',
    safety: 'Generally safe in tourist areas; petty theft is a concern, so standard city caution applies.',
    currency: 'ARS (USD widely accepted)',
    languages: ['Spanish'],
    timeZone: 'ART (UTC-3)',
    visaSummary: 'Visa-free for most US/CA/EU/AU/UK passport holders for short stays.'
  },
  {
    id: 'ushuaia-port',
    name: 'Port of Ushuaia',
    code: 'USH',
    city: 'Ushuaia',
    country: 'Argentina',
    countryCode: 'AR',
    region: 'Antarctica',
    lat: -54.8019,
    lon: -68.3030,
    overview: 'The southernmost city in the world and the primary gateway for expedition voyages across the Drake Passage to the Antarctic Peninsula.',
    thingsToDo: ['Hike in Tierra del Fuego National Park', 'Visit the End of the World Museum', 'Ride the Southern Fuegian Railway', 'Browse local Patagonian wool shops'],
    topAttractions: ['Tierra del Fuego National Park', 'End of the World Museum', 'Beagle Channel', 'Martial Glacier'],
    restaurants: ['Kalma Resto', 'Chez Manu', 'Tante Sara'],
    shopping: ['San Martín Avenue boutiques'],
    beaches: ['None (sub-polar coastline)'],
    museums: ['Museo del Fin del Mundo', 'Maritime & Prison Museum'],
    walkingTours: ['Ushuaia Waterfront & Old Town Walking Tour'],
    transportation: 'Local taxis, shore excursion buses, and walking (compact downtown).',
    estimatedBudgetUSD: 100,
    accessibility: 'Moderate. Downtown is walkable but hilly; expedition ships use Zodiac landings in Antarctica itself.',
    safety: 'Very safe. Remote, low-crime destination.',
    currency: 'ARS (USD widely accepted)',
    languages: ['Spanish', 'English'],
    timeZone: 'ART (UTC-3)',
    visaSummary: 'Visa-free for most US/CA/EU/AU/UK passport holders for short stays.'
  },

  // Arctic Ports
  {
    id: 'reykjavik-port',
    name: 'Port of Reykjavík (Skarfabakki)',
    code: 'REK',
    city: 'Reykjavik',
    country: 'Iceland',
    countryCode: 'IS',
    region: 'Arctic',
    lat: 64.1544,
    lon: -21.9407,
    overview: 'Iceland\'s capital and a key departure point for Arctic and Greenland expedition voyages, with easy access to geothermal spas and the Golden Circle.',
    thingsToDo: ['Soak in the Blue Lagoon geothermal spa', 'Drive the Golden Circle (geysers & waterfalls)', 'Walk historic downtown Reykjavik', 'Watch for the Northern Lights'],
    topAttractions: ['Hallgrímskirkja Church', 'Blue Lagoon', 'Golden Circle', 'Harpa Concert Hall'],
    restaurants: ['Dill Restaurant', 'Íslenski Barinn', 'Grillmarkaðurinn'],
    shopping: ['Laugavegur shopping street', 'Kolaportið flea market'],
    beaches: ['Nauthólsvík Geothermal Beach'],
    museums: ['National Museum of Iceland', 'Perlan Wonders of Iceland'],
    walkingTours: ['Historic Reykjavik Walking Tour'],
    transportation: 'City buses (Strætó), rideshares limited, tour buses, and taxis.',
    estimatedBudgetUSD: 160,
    accessibility: 'Good. Downtown Reykjavik and major attractions are wheelchair accessible.',
    safety: 'Extremely safe. Consistently ranked one of the world\'s most peaceful countries.',
    currency: 'ISK',
    languages: ['Icelandic', 'English'],
    timeZone: 'GMT (UTC+0)',
    visaSummary: 'Schengen Area rules apply.'
  },

  // Asia Ports
  {
    id: 'busan-port',
    name: 'Busan International Passenger Terminal',
    code: 'PUS',
    city: 'Busan',
    country: 'South Korea',
    countryCode: 'KR',
    region: 'South Korea',
    lat: 35.1055,
    lon: 129.0435,
    overview: 'South Korea\'s largest port city, offering cruisers a mix of beach resorts, mountain temples, and one of Asia\'s biggest seafood markets.',
    thingsToDo: ['Browse Jagalchi Fish Market', 'Relax at Haeundae Beach', 'Visit Haedong Yonggungsa Temple', 'Explore Gamcheon Culture Village'],
    topAttractions: ['Gamcheon Culture Village', 'Haedong Yonggungsa Temple', 'Haeundae Beach', 'Jagalchi Market'],
    restaurants: ['Jagalchi Market seafood stalls', 'Millak Raw Fish Town', 'Songjeong Samdae Guksu'],
    shopping: ['Seomyeon shopping district', 'Nampo-dong market'],
    beaches: ['Haeundae Beach', 'Gwangalli Beach'],
    museums: ['Busan Museum', 'F1963 art complex'],
    walkingTours: ['Gamcheon Culture Village Walking Tour'],
    transportation: 'Busan Metro, taxis, and airport limousine buses.',
    estimatedBudgetUSD: 85,
    accessibility: 'Good. Metro stations and major attractions have elevators and ramps.',
    safety: 'Very safe. Low crime rate typical of South Korea.',
    currency: 'KRW',
    languages: ['Korean', 'English'],
    timeZone: 'KST (UTC+9)',
    visaSummary: 'K-ETA required for most visa-free nationalities.'
  },
  {
    id: 'shanghai-port',
    name: 'Shanghai Wusongkou International Cruise Terminal',
    code: 'SHA',
    city: 'Shanghai',
    country: 'China',
    countryCode: 'CN',
    region: 'China',
    lat: 31.3444,
    lon: 121.5464,
    overview: 'China\'s premier cruise gateway, connecting travelers to Shanghai\'s futuristic skyline, historic Bund waterfront, and classical gardens.',
    thingsToDo: ['Walk along The Bund waterfront', 'Ride to the top of Shanghai Tower', 'Explore Yu Garden and the Old City', 'Stroll the French Concession'],
    topAttractions: ['The Bund', 'Yu Garden', 'Shanghai Tower Observation Deck', 'Nanjing Road'],
    restaurants: ['Din Tai Fung', 'Jean Georges Shanghai', 'Yang\'s Fry-Dumpling'],
    shopping: ['Nanjing Road pedestrian street', 'Tianzifang art & shopping lanes'],
    beaches: ['None (major river/harbor city)'],
    museums: ['Shanghai Museum', 'China Art Museum'],
    walkingTours: ['The Bund & French Concession Walking Tour'],
    transportation: 'Shanghai Metro, Maglev train, taxis, and rideshares.',
    estimatedBudgetUSD: 90,
    accessibility: 'Good. Modern metro stations and major sights have elevators and ramps.',
    safety: 'Very safe. Low violent crime rate for international visitors.',
    currency: 'CNY',
    languages: ['Mandarin', 'English (limited)'],
    timeZone: 'CST (UTC+8)',
    visaSummary: 'Visa required for most nationalities; some markets qualify for 15-day visa-free transit.'
  },

  // India & Middle East Ports
  {
    id: 'mumbai-port',
    name: 'Mumbai Cruise Terminal (Ballard Pier)',
    code: 'BOM',
    city: 'Mumbai',
    country: 'India',
    countryCode: 'IN',
    region: 'India',
    lat: 18.9220,
    lon: 72.8347,
    overview: 'India\'s primary cruise gateway, docking near the iconic Gateway of India and offering direct access to Mumbai\'s colonial architecture and bustling bazaars.',
    thingsToDo: ['Visit the Gateway of India', 'Tour Elephanta Caves by boat', 'Explore Crawford Market', 'Walk Marine Drive at sunset'],
    topAttractions: ['Gateway of India', 'Elephanta Caves', 'Chhatrapati Shivaji Terminus', 'Marine Drive'],
    restaurants: ['Leopold Cafe', 'Trishna', 'Britannia & Co.'],
    shopping: ['Colaba Causeway', 'Crawford Market'],
    beaches: ['Juhu Beach', 'Girgaum Chowpatty'],
    museums: ['Chhatrapati Shivaji Maharaj Vastu Sangrahalaya', 'Dr. Bhau Daji Lad Museum'],
    walkingTours: ['Colonial South Mumbai Heritage Walking Tour'],
    transportation: 'Local trains, metro, auto-rickshaws, taxis, and rideshares.',
    estimatedBudgetUSD: 60,
    accessibility: 'Moderate. Major landmarks have ramps; older areas can be crowded and uneven.',
    safety: 'Generally safe in tourist areas; standard precautions against pickpocketing recommended.',
    currency: 'INR',
    languages: ['Hindi', 'Marathi', 'English'],
    timeZone: 'IST (UTC+5:30)',
    visaSummary: 'e-Visa required for most foreign nationals; arranged in advance.'
  },
  {
    id: 'dubai-port',
    name: 'Dubai Cruise Terminal (Mina Rashid)',
    code: 'DXB',
    city: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    region: 'Middle East',
    lat: 25.2697,
    lon: 55.2769,
    overview: 'A modern, ultra-luxurious cruise terminal serving as the hub for Middle East and Arabian Gulf voyages, minutes from the Burj Khalifa and Dubai Mall.',
    thingsToDo: ['Ride to the top of the Burj Khalifa', 'Shop and watch the fountains at Dubai Mall', 'Explore the historic Al Fahidi district', 'Take an abra boat across Dubai Creek'],
    topAttractions: ['Burj Khalifa', 'Dubai Mall & Dubai Fountain', 'Palm Jumeirah', 'Dubai Creek & Al Fahidi'],
    restaurants: ['Al Ustad Special Kabab', 'Pierchic', 'Ravi Restaurant'],
    shopping: ['Dubai Mall', 'Gold & Spice Souks'],
    beaches: ['Jumeirah Beach', 'Kite Beach'],
    museums: ['Museum of the Future', 'Dubai Museum (Al Fahidi Fort)'],
    walkingTours: ['Old Dubai Souks & Creek Walking Tour'],
    transportation: 'Dubai Metro, taxis, rideshares, and abra water taxis.',
    estimatedBudgetUSD: 150,
    accessibility: 'Excellent. Metro and major malls are fully wheelchair accessible.',
    safety: 'Extremely safe. Very low crime rate.',
    currency: 'AED',
    languages: ['Arabic', 'English'],
    timeZone: 'GST (UTC+4)',
    visaSummary: 'Visa-on-arrival for most Western passport holders.'
  },

  // Australia & New Zealand Ports
  {
    id: 'auckland-port',
    name: 'Auckland Cruise Terminal (Queens Wharf)',
    code: 'AKL',
    city: 'Auckland',
    country: 'New Zealand',
    countryCode: 'NZ',
    region: 'New Zealand',
    lat: -36.8420,
    lon: 174.7690,
    overview: 'New Zealand\'s "City of Sails," docking downtown on the Waitematā Harbour and serving as the main gateway for New Zealand and South Pacific voyages.',
    thingsToDo: ['Ride the Sky Tower observation deck', 'Explore Waiheke Island wineries', 'Walk the Auckland Domain and War Memorial Museum', 'Visit Mission Bay Beach'],
    topAttractions: ['Sky Tower', 'Auckland War Memorial Museum', 'Waiheke Island', 'Viaduct Harbour'],
    restaurants: ['The Grove', 'Ortolana', 'Depot Eatery & Oyster Bar'],
    shopping: ['Britomart precinct', 'Queen Street'],
    beaches: ['Mission Bay Beach', 'Takapuna Beach'],
    museums: ['Auckland War Memorial Museum', 'Auckland Art Gallery'],
    walkingTours: ['Auckland Waterfront & Viaduct Walking Tour'],
    transportation: 'Auckland buses and ferries, rideshares, and taxis.',
    estimatedBudgetUSD: 120,
    accessibility: 'High. Waterfront precinct and major attractions are wheelchair accessible.',
    safety: 'Very safe. Low crime rate typical of New Zealand cities.',
    currency: 'NZD',
    languages: ['English', 'Māori'],
    timeZone: 'NZST (UTC+12)',
    visaSummary: 'NZeTA required for most visa-waiver nationalities.'
  },

  // Africa Ports
  {
    id: 'cape-town-port',
    name: 'Cape Town Cruise Terminal (V&A Waterfront)',
    code: 'CPT',
    city: 'Cape Town',
    country: 'South Africa',
    countryCode: 'ZA',
    region: 'Africa',
    lat: -33.9036,
    lon: 18.4231,
    overview: 'One of the world\'s most scenic cruise ports, docking at the V&A Waterfront beneath Table Mountain and serving as the gateway to South Africa\'s coastline.',
    thingsToDo: ['Ride the cableway up Table Mountain', 'Visit Robben Island', 'Tour the Cape of Good Hope and penguin colony', 'Explore Bo-Kaap\'s colorful streets'],
    topAttractions: ['Table Mountain', 'Robben Island', 'Cape of Good Hope', 'V&A Waterfront'],
    restaurants: ['The Test Kitchen', 'La Colombe', 'Kloof Street House'],
    shopping: ['V&A Waterfront malls', 'Greenmarket Square'],
    beaches: ['Camps Bay Beach', 'Boulders Beach (penguins)'],
    museums: ['Zeitz Museum of Contemporary Art Africa (MOCAA)', 'District Six Museum'],
    walkingTours: ['Bo-Kaap Cultural Walking Tour'],
    transportation: 'MyCiTi bus rapid transit, rideshares, and licensed taxis.',
    estimatedBudgetUSD: 90,
    accessibility: 'Good. Waterfront and cableway base station are accessible; some historic streets have steep terrain.',
    safety: 'Generally safe in tourist zones; avoid unfamiliar areas after dark and use registered transport.',
    currency: 'ZAR',
    languages: ['English', 'Afrikaans', 'Xhosa'],
    timeZone: 'SAST (UTC+2)',
    visaSummary: 'Visa-free for most US/CA/EU/AU/UK passport holders for short stays.'
  },

  // River Cruise Ports - Nile, Rhine, Mekong, Amazon, Mississippi
  {
    id: 'luxor-port',
    name: 'Luxor River Cruise Docks',
    code: 'LXR',
    city: 'Luxor',
    country: 'Egypt',
    countryCode: 'EG',
    region: 'Nile River',
    lat: 25.6872,
    lon: 32.6396,
    overview: 'Known as the world\'s greatest open-air museum, Luxor is the traditional starting point for Nile river cruises, home to the Valley of the Kings and Karnak Temple.',
    thingsToDo: ['Tour the Valley of the Kings', 'Explore Karnak Temple complex', 'Visit the Temple of Hatshepsut', 'Watch the Luxor Temple sound and light show'],
    topAttractions: ['Valley of the Kings', 'Karnak Temple', 'Luxor Temple', 'Temple of Hatshepsut'],
    restaurants: ['Sofra Restaurant', 'Al-Sahaby Lane', 'Kebabgy Nile-view restaurant'],
    shopping: ['Luxor Souk', 'Local alabaster and papyrus workshops'],
    beaches: ['None (Nile river city)'],
    museums: ['Luxor Museum', 'Mummification Museum'],
    walkingTours: ['East Bank Temples Guided Walking Tour'],
    transportation: 'Horse-drawn caleche carriages, taxis, and Nile ferries to the West Bank.',
    estimatedBudgetUSD: 70,
    accessibility: 'Moderate. Major temple sites have paved paths; some tombs involve steps and narrow passages.',
    safety: 'Safe in tourist areas; travel with licensed guides and registered excursion operators.',
    currency: 'EGP (USD widely accepted for tours)',
    languages: ['Arabic', 'English'],
    timeZone: 'EET (UTC+2)',
    visaSummary: 'Visa-on-arrival or e-Visa available for most nationalities.'
  },
  {
    id: 'aswan-port',
    name: 'Aswan River Cruise Docks',
    code: 'ASW',
    city: 'Aswan',
    country: 'Egypt',
    countryCode: 'EG',
    region: 'Nile River',
    lat: 24.0889,
    lon: 32.8998,
    overview: 'Egypt\'s southernmost Nile city and a classic turnaround point for river cruises, known for its Nubian culture, felucca sailboats, and the Philae Temple.',
    thingsToDo: ['Sail a traditional felucca around Elephantine Island', 'Visit the Temple of Philae', 'Tour the Aswan High Dam', 'Explore a Nubian village'],
    topAttractions: ['Philae Temple', 'Aswan High Dam', 'Unfinished Obelisk', 'Nubian Museum'],
    restaurants: ['1902 Restaurant (Old Cataract Hotel)', 'Nubian House restaurant', 'Aswan Moon'],
    shopping: ['Aswan Souk', 'Nubian handicraft stalls'],
    beaches: ['None (Nile river city)'],
    museums: ['Nubian Museum'],
    walkingTours: ['Aswan Souk & Nubian Village Walking Tour'],
    transportation: 'Felucca sailboats, taxis, and horse-drawn carriages.',
    estimatedBudgetUSD: 65,
    accessibility: 'Moderate. Temple sites reached by boat can involve uneven landings.',
    safety: 'Safe in tourist areas; travel with licensed guides and registered excursion operators.',
    currency: 'EGP (USD widely accepted for tours)',
    languages: ['Arabic', 'Nubian', 'English'],
    timeZone: 'EET (UTC+2)',
    visaSummary: 'Visa-on-arrival or e-Visa available for most nationalities.'
  },
  {
    id: 'basel-port',
    name: 'Basel River Cruise Port',
    code: 'BSL',
    city: 'Basel',
    country: 'Switzerland',
    countryCode: 'CH',
    region: 'Rhine River',
    lat: 47.5596,
    lon: 7.5886,
    overview: 'A common turnaround point for Rhine river cruises at the tri-border of Switzerland, Germany, and France, known for its Old Town and world-class art museums.',
    thingsToDo: ['Wander the medieval Basel Old Town', 'Visit the Fondation Beyeler art museum', 'Cross the Rhine on a traditional ferry', 'Climb Basel Münster cathedral tower'],
    topAttractions: ['Basel Münster', 'Old Town Basel', 'Fondation Beyeler', 'Rhine River Ferries'],
    restaurants: ['Restaurant Kunsthalle', 'Zum Roten Engel', 'Volkshaus Basel'],
    shopping: ['Freie Strasse pedestrian street', 'Basel Christmas Market (seasonal)'],
    beaches: ['None (Rhine riverside promenades used for swimming in summer)'],
    museums: ['Kunstmuseum Basel', 'Fondation Beyeler'],
    walkingTours: ['Basel Old Town Walking Tour'],
    transportation: 'Trams, buses, and the historic Rhine ferry crossings.',
    estimatedBudgetUSD: 130,
    accessibility: 'High. Trams and city center are well accessible.',
    safety: 'Extremely safe. Low crime, orderly Swiss city.',
    currency: 'CHF',
    languages: ['German', 'French', 'English'],
    timeZone: 'CET (UTC+1)',
    visaSummary: 'Schengen Area rules apply.'
  },
  {
    id: 'saigon-port',
    name: 'Ho Chi Minh City River Cruise Terminal',
    code: 'SGN',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    countryCode: 'VN',
    region: 'Mekong River',
    lat: 10.7769,
    lon: 106.7009,
    overview: 'The gateway to Mekong River cruising, docking near the Saigon River in Vietnam\'s largest city, rich with war history and vibrant street life.',
    thingsToDo: ['Tour the War Remnants Museum', 'Explore the Cu Chi Tunnels', 'Visit the Reunification Palace', 'Browse Ben Thanh Market'],
    topAttractions: ['War Remnants Museum', 'Cu Chi Tunnels', 'Reunification Palace', 'Notre-Dame Cathedral Basilica of Saigon'],
    restaurants: ['Cục Gạch Quán', 'Pho 2000', 'Quan Bui'],
    shopping: ['Ben Thanh Market', 'Dong Khoi Street boutiques'],
    beaches: ['None (Mekong Delta river city)'],
    museums: ['War Remnants Museum', 'Ho Chi Minh City Museum'],
    walkingTours: ['Saigon Colonial District Walking Tour'],
    transportation: 'Taxis, rideshares (Grab), and cyclos for short trips.',
    estimatedBudgetUSD: 55,
    accessibility: 'Moderate. Modern districts are accessible; older streets can be crowded and uneven.',
    safety: 'Generally safe; watch for traffic and petty theft on motorbikes in crowded markets.',
    currency: 'VND',
    languages: ['Vietnamese', 'English'],
    timeZone: 'ICT (UTC+7)',
    visaSummary: 'e-Visa required for most nationalities.'
  },
  {
    id: 'manaus-port',
    name: 'Manaus River Cruise Terminal',
    code: 'MAO',
    city: 'Manaus',
    country: 'Brazil',
    countryCode: 'BR',
    region: 'Amazon River',
    lat: -3.1319,
    lon: -60.0231,
    overview: 'The heart of the Brazilian Amazon, docking beside the historic floating harbor and serving as the launch point for rainforest and river wildlife cruises.',
    thingsToDo: ['Tour the ornate Amazon Theatre opera house', 'Visit the Meeting of the Waters (Rio Negro & Solimões)', 'Take a rainforest canopy walkway tour', 'Visit a riverside caboclo community'],
    topAttractions: ['Amazon Theatre', 'Meeting of the Waters', 'Museu da Amazônia (MUSA)', 'Ponta Negra Beach'],
    restaurants: ['Banzeiro', 'Caxiri', 'Tacacá da Gisela'],
    shopping: ['Manaus Municipal Market (Mercado Municipal)'],
    beaches: ['Ponta Negra Beach (seasonal river beach)'],
    museums: ['Museu da Amazônia (MUSA)', 'Museum of the Man of the North'],
    walkingTours: ['Historic Manaus Port District Walking Tour'],
    transportation: 'Taxis, riverboats, and shore excursion vessels for jungle access.',
    estimatedBudgetUSD: 75,
    accessibility: 'Limited. Rainforest excursions involve boardwalks and boats; the historic center is more accessible.',
    safety: 'Generally safe in central tourist areas; excursions into the rainforest are guided for safety.',
    currency: 'BRL',
    languages: ['Portuguese'],
    timeZone: 'AMT (UTC-4)',
    visaSummary: 'Visa-free for most US/CA/EU/AU/UK passport holders for short stays.'
  },
  {
    id: 'new-orleans-port',
    name: 'Port of New Orleans (Julia Street Terminal)',
    code: 'MSY',
    city: 'New Orleans',
    country: 'United States',
    countryCode: 'US',
    region: 'Mississippi River',
    lat: 29.9425,
    lon: -90.0621,
    overview: 'The historic starting point for Mississippi River cruises, docking steps from the French Quarter, live jazz clubs, and Creole cuisine.',
    thingsToDo: ['Explore the French Quarter and Bourbon Street', 'Take a jazz cruise on the Steamboat Natchez', 'Tour a Garden District mansion', 'Visit the National WWII Museum'],
    topAttractions: ['French Quarter', 'Jackson Square', 'Garden District', 'National WWII Museum'],
    restaurants: ['Commander\'s Palace', 'Cafe du Monde', 'Galatoire\'s'],
    shopping: ['Magazine Street boutiques', 'French Market'],
    beaches: ['None (Mississippi River city)'],
    museums: ['National WWII Museum', 'New Orleans Jazz Museum'],
    walkingTours: ['French Quarter Historic & Ghost Walking Tour'],
    transportation: 'Streetcars, buses, rideshares, and taxis.',
    estimatedBudgetUSD: 110,
    accessibility: 'Good. French Quarter sidewalks can be uneven; streetcars and major sites have accessible options.',
    safety: 'Generally safe in tourist areas; standard nightlife precautions recommended on and around Bourbon Street.',
    currency: 'USD',
    languages: ['English', 'French (Creole heritage)'],
    timeZone: 'CST (UTC-6)',
    visaSummary: 'ESTA/US visa required for foreign nationals.'
  }
];

export const PORTS_BY_ID: Record<string, CruisePort> = Object.fromEntries(
  PORTS.map((p) => [p.id, p])
);
export const PORTS_BY_REGION: Record<string, CruisePort[]> = PORTS.reduce((acc, port) => {
  if (!acc[port.region]) {
    acc[port.region] = [];
  }
  acc[port.region].push(port);
  return acc;
}, {} as Record<string, CruisePort[]>);
