// Exports the generated package dataset as plain Postgres INSERT statements —
// for direct `psql -f` import or environments that don't run Prisma. Requires
// `npm run generate:packages` to have been run first (reads its JSON output).
// Prefer `npm run db:seed:packages` (Prisma-based) for normal app use; this is
// the portable, driver-agnostic alternative.
//
// Usage: npm run generate:packages-sql

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { DestinationFacts, TravelPackage } from '../src/lib/packages/types';

const GENERATED_DIR = join(process.cwd(), 'src', 'data', 'generated');
const OUT_FILE = join(process.cwd(), 'prisma', 'seed-packages.sql');

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlJsonb(value: unknown): string {
  return `${sqlString(JSON.stringify(value))}::jsonb`;
}

function sqlTextArray(values: string[]): string {
  if (values.length === 0) return "ARRAY[]::text[]";
  return `ARRAY[${values.map(sqlString).join(', ')}]::text[]`;
}

function destinationId(slug: string): string {
  return `dest_${slug.replace(/-/g, '_')}`;
}

function main() {
  const destinations: DestinationFacts[] = JSON.parse(readFileSync(join(GENERATED_DIR, 'destinations.json'), 'utf8'));
  const packageFiles = readdirSync(join(GENERATED_DIR, 'packages')).filter((f) => f.endsWith('.json'));

  const lines: string[] = [
    '-- Generated by scripts/generate-sql-seed.ts — do not hand-edit.',
    '-- Run: psql "$DATABASE_URL" -f prisma/seed-packages.sql',
    '-- Requires the Destination and Package tables from prisma/schema.prisma to already exist (npx prisma db push).',
    'BEGIN;',
    '',
  ];

  for (const d of destinations) {
    const id = destinationId(d.slug);
    lines.push(
      `INSERT INTO "Destination" (id, "createdAt", "updatedAt", slug, name, country, "countryCode", region, continent, lat, lon, "airportCode", "airportName", currency, categories, facts)`,
      `VALUES (${sqlString(id)}, now(), now(), ${sqlString(d.slug)}, ${sqlString(d.name)}, ${sqlString(d.country)}, ${sqlString(d.countryCode)}, ${sqlString(d.region)}, ${sqlString(d.continent)}, ${d.lat}, ${d.lon}, ${sqlString(d.airportCode)}, ${sqlString(d.airportName)}, ${sqlString(d.currency)}, ${sqlTextArray(d.categories)}, ${sqlJsonb(d)})`,
      `ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, "updatedAt" = now(), facts = EXCLUDED.facts, categories = EXCLUDED.categories;`,
      '',
    );
  }

  for (const file of packageFiles) {
    const pkg: TravelPackage = JSON.parse(readFileSync(join(GENERATED_DIR, 'packages', file), 'utf8'));
    const id = `pkg_${pkg.slug.replace(/-/g, '_')}`;
    const destId = destinationId(pkg.destinationSlug);
    lines.push(
      `INSERT INTO "Package" (id, "createdAt", "updatedAt", slug, "destinationId", "destinationSlug", "durationDays", "durationNights", title, "metaTitle", "metaDescription", overview, categories, "aiTags", "fromPriceUSD", "ratingOverall", "reviewCount", content)`,
      `VALUES (${sqlString(id)}, now(), now(), ${sqlString(pkg.slug)}, ${sqlString(destId)}, ${sqlString(pkg.destinationSlug)}, ${pkg.durationDays}, ${pkg.durationNights}, ${sqlString(pkg.title)}, ${sqlString(pkg.metaTitle)}, ${sqlString(pkg.metaDescription)}, ${sqlString(pkg.overview)}, ${sqlTextArray(pkg.categories)}, ${sqlTextArray(pkg.aiTags)}, ${pkg.fromPriceUSD}, ${pkg.ratings.overall}, ${pkg.ratings.reviewCount}, ${sqlJsonb(pkg)})`,
      `ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, "updatedAt" = now(), content = EXCLUDED.content, "fromPriceUSD" = EXCLUDED."fromPriceUSD", "ratingOverall" = EXCLUDED."ratingOverall", "reviewCount" = EXCLUDED."reviewCount";`,
      '',
    );
  }

  lines.push('COMMIT;', '');
  writeFileSync(OUT_FILE, lines.join('\n'));
  console.log(`Wrote ${destinations.length} destination + ${packageFiles.length} package INSERT statements to ${OUT_FILE}`);
}

main();
