// Featured destinations added based on the Euromonitor International Top 100 City
// Destinations Index 2025 (Macau: #4 globally by international arrivals at 20.4M) and
// Lonely Planet's Best in Travel 2026 list (Mexico City, São Paulo), plus destinations
// with major 2025-26 tourism growth (AlUla — Saudi Arabia's Vision 2030 tourism push
// drove 122M national visitors in 2025) and long-standing high-volume destinations
// with a surprising gap in the existing catalog (Jeju, Antalya, Kuala Lumpur, Sharm
// El Sheikh, Ibiza). Same DestinationFacts shape as destinations-a..f.ts, run through
// the same generatePackage() engine — not a separate/different content pipeline.
import type { DestinationFacts } from './types';

export const DESTINATIONS_G: DestinationFacts[] = [
  {
    slug: 'macau',
    name: 'Macau',
    country: 'Macau SAR, China',
    countryCode: 'MO',
    region: 'East Asia',
    continent: 'Asia',
    lat: 22.1987,
    lon: 113.5439,
    airportCode: 'MFM',
    airportName: 'Macau International Airport',
    currency: 'MOP',
    languages: ['Cantonese', 'Portuguese', 'Mandarin'],
    timeZone: 'CST (UTC+8)',
    utcOffset: 8,
    visaSummary:
      'Most Western nationalities including the US, UK, Canada, Australia and EU citizens can enter visa-free for 30-90 days depending on nationality. Many nationalities can also visit as part of a Hong Kong side-trip via ferry. Verify current requirements against your specific passport before travel.',
    bestTimeToVisit:
      'October to December offers the most comfortable temperatures, low humidity, and clear skies — ideal for walking the historic center and coinciding with the Macau Grand Prix in November.',
    weatherSummary:
      'Subtropical climate with hot, humid summers (June-August, frequent typhoon risk) and mild, dry winters (December-February, highs around 18-20°C). Spring and autumn are transitional and generally pleasant.',
    safetyRating: 5,
    internetRating: 5,
    transportRating: 4,
    walkingScore: 78,
    accessibilityRating: 4,
    dailyBudgetUSD: [55, 110, 240, 550],
    costIndex: 1.15,
    emergency: { police: '999', ambulance: '999', fire: '999' },
    etiquette: [
      'Casinos enforce a strict minimum age of 21 and formal-casual dress in premium gaming rooms — flip-flops and tank tops are often turned away.',
      'Photography is prohibited on the gaming floor of any casino.',
      'Tipping isn\'t mandatory but a 10% service charge is common at restaurants; rounding up taxi fares is appreciated.',
      'The historic center blends Portuguese and Chinese culture — locals take pride in both heritages, so avoid treating it as "just a casino town."',
      'Business cards are exchanged with both hands, a habit carried over from Chinese and Portuguese trading customs.',
    ],
    festivals: [
      { name: 'Macau Grand Prix (street circuit motor race)', timing: 'Mid-November' },
      { name: 'A-Ma Temple Festival', timing: 'April/May (23rd day of the 3rd lunar month)' },
      { name: 'Feast of the Drunken Dragon', timing: 'May (8th day of the 4th lunar month)' },
      { name: 'Macau International Fireworks Display Contest', timing: 'September' },
    ],
    weatherByMonth: [18, 18, 21, 24, 28, 30, 32, 31, 30, 27, 23, 19],
    crowdByMonth: ['Peak', 'Peak', 'High', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'High', 'Peak', 'High'],
    attractionsPaid: [
      { name: 'Macau Tower Skywalk & Bungy', note: 'Glass-floor observation deck and the world\'s highest commercial bungee jump', priceUSD: 25 },
      { name: 'House of Dancing Water show', note: 'Spectacular water-stage theatrical production at City of Dreams', priceUSD: 100 },
      { name: 'The Venetian Macao gondola ride', note: 'Indoor canal ride through a recreated Venice under a painted sky', priceUSD: 15 },
      { name: 'Grand Lisboa observation & casino tour', note: 'Iconic lotus-shaped skyscraper, Macau\'s casino skyline landmark', priceUSD: 0 },
      { name: 'Macau Museum', note: 'History of Macau\'s 400+ years as a Portuguese trading post', priceUSD: 6 },
      { name: 'Coloane Village bike & beach day', note: 'Rent a bike to explore Macau\'s quieter, greener southern island', priceUSD: 10 },
    ],
    attractionsFree: [
      { name: 'Ruins of St. Paul\'s', note: 'Iconic 17th-century cathedral façade, Macau\'s most photographed landmark' },
      { name: 'Senado Square', note: 'UNESCO-listed plaza with wave-patterned Portuguese mosaic paving' },
      { name: 'A-Ma Temple', note: 'Macau\'s oldest temple, dating to 1488, dedicated to the sea goddess Mazu' },
      { name: 'Fortaleza do Monte', note: 'Historic 17th-century fortress with panoramic city views' },
      { name: 'Rua de São Paulo', note: 'Cobblestone street of colonial shophouses leading to the Ruins' },
      { name: 'Taipa Houses-Museum grounds', note: 'Pastel-colored Portuguese colonial residences by the water' },
    ],
    restaurants: [
      { name: 'A Lorcha', cuisine: 'Macanese Fusion', price: '$$$' },
      { name: 'Antonio', cuisine: 'Traditional Portuguese', price: '$$$' },
      { name: 'Robuchon au Dôme', cuisine: 'French Fine Dining (3 Michelin Stars)', price: '$$$$' },
      { name: 'Lord Stow\'s Bakery', cuisine: 'Portuguese Egg Tarts', price: '$' },
      { name: 'Wong Chi Kei Congee & Noodle', cuisine: 'Cantonese Street Food', price: '$' },
      { name: 'Restaurante Litoral', cuisine: 'Macanese', price: '$$' },
    ],
    cafes: ['Café Litoral', 'Single Origin Coffee Roasters', 'Ritz Cafe', 'Margaret\'s Café e Nata'],
    shopping: ['Rua de São Paulo souvenir shops', 'The Venetian Grand Canal Shoppes', 'Senado Square boutiques', 'Red Market'],
    nightlife: ['Casino floors of The Venetian and Grand Lisboa', 'MGM Cotai lounges', 'Docks (Rua do Cunha nightlife strip)', 'Rooftop bars overlooking the Macau skyline'],
    instagramSpots: ['Ruins of St. Paul\'s staircase', 'Senado Square wave-pattern tiles', 'Taipa Houses pastel façades', 'Macau Tower skywalk views'],
    hiddenGems: ['Coloane Village\'s quiet fishing-town lanes', 'Mount Fortress gardens at sunset', 'Lou Lim Ieoc Garden', 'Old Taipa backstreet egg tart bakeries away from the crowds'],
    familyActivities: ['The Venetian gondola rides', 'Macau Science Center', 'Hac Sa Beach in Coloane', 'AJ Hackett bungee viewing deck'],
    adventureActivities: ['Macau Tower bungee jump (233m)', 'SkyWalk X around the tower rim', 'Coloane cycling trails', 'Hiking Coloane\'s trail network'],
    luxuryExperiences: ['Suite stay and private gaming room at a Cotai Strip resort', 'Michelin-starred tasting menu at Robuchon au Dôme', 'Private junk boat cruise around the Macau peninsula', 'VIP House of Dancing Water seating'],
    honeymoonExperiences: ['Sunset stroll through Senado Square and the Ruins of St. Paul\'s', 'Romantic gondola ride at The Venetian', 'Couples spa at a Cotai Strip resort', 'Rooftop dinner overlooking the illuminated skyline'],
    budgetExperiences: ['Free walking tour of the UNESCO historic center', 'Egg tarts and street food crawl for a few dollars a stop', 'Casino floor people-watching (no minimum to enter)', 'Free ferry-view of the skyline from the Macau peninsula waterfront'],
    museums: ['Macau Museum', 'Maritime Museum', 'Grand Prix Museum'],
    parks: ['Lou Lim Ieoc Garden', 'Guia Hill', 'Seac Pai Van Park'],
    beaches: ['Hac Sa Beach (black sand, Coloane)', 'Cheoc Van Beach'],
    dayTrips: ['Hong Kong via high-speed ferry (1 hour)', 'Zhuhai, mainland China, via the Hong Kong-Zhuhai-Macau Bridge', 'Taipa and Coloane island villages'],
    localTransportGuide:
      'Macau is compact and highly walkable in the historic center; free shuttle buses run from casino resorts to the ferry terminal and border gate. Public buses cover the rest of the peninsula cheaply, and taxis are metered and reasonably priced. The Hong Kong-Zhuhai-Macau Bridge and regular ferries connect easily to Hong Kong.',
    packingNotes: ['Comfortable shoes for cobblestone streets', 'Smart-casual outfit for casino entry', 'Light layers — malls and casinos are heavily air-conditioned', 'Umbrella during the June-September wet season'],
    travelTips: [
      'Casino resorts on the Cotai Strip run free shuttle buses to/from the ferry terminal and border gate — no taxi needed.',
      'Bring your passport even for short casino visits; ID checks are routine.',
      'The historic center is best explored on foot in the morning before Senado Square gets crowded with day-trippers from Hong Kong.',
      'MOP and HKD are both widely accepted at a roughly 1:1 rate, though change is usually given in MOP.',
      'Book House of Dancing Water tickets in advance — shows regularly sell out on weekends.',
    ],
    thingsToAvoid: [
      'Photographing the gaming floor — casino security will intervene immediately.',
      'Underdressed casual wear (flip-flops, swimwear) at premium gaming areas and fine-dining restaurants.',
      'Assuming Hong Kong dollars and Macau patacas are interchangeable everywhere outside casinos and tourist areas.',
      'Visiting Senado Square at peak midday on weekends, when day-trip ferry crowds from Hong Kong are heaviest.',
    ],
    categories: ['City Break', 'Luxury', 'Culture', 'History', 'Food', 'Nightlife'],
    heroKeywords: ['Ruins of St Paul\'s Macau', 'Macau casino skyline at night', 'Senado Square mosaic tiles', 'Macau Tower skywalk'],
  },
  {
    slug: 'mexico-city',
    name: 'Mexico City',
    country: 'Mexico',
    countryCode: 'MX',
    region: 'North America',
    continent: 'North America',
    lat: 19.4326,
    lon: -99.1332,
    airportCode: 'MEX',
    airportName: 'Benito Juárez International Airport',
    currency: 'MXN',
    languages: ['Spanish'],
    timeZone: 'CST (UTC-6)',
    utcOffset: -6,
    visaSummary:
      'US, Canadian, UK, EU, and Australian citizens can enter visa-free for tourism up to 180 days with a valid passport (an FMM tourist card, usually issued on arrival or included with airline check-in, is required). Verify current requirements against your specific passport before travel.',
    bestTimeToVisit:
      'March to May and October to November offer warm, dry days with minimal rain, avoiding both the summer rainy season and the coolest winter nights at this high-altitude city.',
    weatherSummary:
      'Mild, spring-like climate year-round thanks to its 2,240m altitude — warm sunny days (18-25°C) with cool nights. The rainy season (June-September) brings brief, heavy afternoon downpours; December-February can be chilly at night.',
    safetyRating: 3,
    internetRating: 4,
    transportRating: 4,
    walkingScore: 70,
    accessibilityRating: 3,
    dailyBudgetUSD: [35, 75, 160, 380],
    costIndex: 0.65,
    emergency: { police: '911', ambulance: '911', fire: '911' },
    etiquette: [
      'A polite greeting ("Buenos días/tardes") before getting to business, even with shopkeepers or taxi drivers, is expected and appreciated.',
      'Meals are social and unhurried — rushing through a restaurant meal is considered impolite.',
      'Dress reasonably smart-casual; overly casual beachwear is out of place in this highland capital.',
      'Bargaining is expected and welcomed at markets (mercados) but not in fixed-price shops or restaurants.',
      'Public displays of frustration or raised voices are frowned upon — patience is valued in queues and traffic.',
    ],
    festivals: [
      { name: 'Día de los Muertos (Day of the Dead)', timing: 'October 31 - November 2' },
      { name: 'Independence Day (Grito de Dolores) celebrations', timing: 'September 15-16' },
      { name: 'Guelaguetza-influenced cultural festivals', timing: 'July' },
      { name: 'Christmas Posadas', timing: 'December 16-24' },
    ],
    weatherByMonth: [21, 23, 25, 26, 26, 24, 23, 23, 22, 22, 21, 20],
    crowdByMonth: ['Medium', 'Medium', 'High', 'High', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'High', 'Peak', 'Peak'],
    attractionsPaid: [
      { name: 'Teotihuacan pyramids day trip', note: 'Ancient Mesoamerican city with the Pyramid of the Sun and Moon', priceUSD: 5 },
      { name: 'Frida Kahlo Museum (Casa Azul)', note: 'The artist\'s vivid cobalt-blue family home in Coyoacán', priceUSD: 18 },
      { name: 'Palacio de Bellas Artes', note: 'Art Nouveau/Art Deco palace with Diego Rivera murals', priceUSD: 5 },
      { name: 'Templo Mayor & Museum', note: 'Excavated Aztec temple ruins in the heart of the historic center', priceUSD: 4 },
      { name: 'Xochimilco trajinera boat ride', note: 'Colorful gondola-style boats through Aztec-era floating gardens canals', priceUSD: 20 },
      { name: 'Chapultepec Castle', note: 'Hilltop former imperial residence with city panoramas', priceUSD: 5 },
    ],
    attractionsFree: [
      { name: 'Zócalo (Plaza de la Constitución)', note: 'One of the world\'s largest public squares, flanked by the Metropolitan Cathedral' },
      { name: 'Bosque de Chapultepec', note: 'Massive urban park, bigger than New York\'s Central Park' },
      { name: 'Coyoacán historic center', note: 'Cobblestone plazas, colonial architecture, and lively cafes' },
      { name: 'Paseo de la Reforma murals & Angel of Independence', note: 'Grand boulevard lined with monuments and skyscrapers' },
      { name: 'Mercado de San Juan browsing', note: 'Gourmet market famous among chefs for exotic ingredients' },
      { name: 'Diego Rivera murals at the National Palace', note: 'Sweeping historical murals inside the seat of government' },
    ],
    restaurants: [
      { name: 'Pujol', cuisine: 'Contemporary Mexican Fine Dining', price: '$$$$' },
      { name: 'El Cardenal', cuisine: 'Traditional Mexican Breakfast & Comida', price: '$$$' },
      { name: 'Contramar', cuisine: 'Coastal Mexican Seafood', price: '$$$' },
      { name: 'Tacos El Califa de León', cuisine: 'Michelin-starred Street Taco Stand', price: '$' },
      { name: 'Café de Tacuba', cuisine: 'Historic Traditional Mexican', price: '$$' },
      { name: 'Mercado Roma food stalls', cuisine: 'Gourmet Mexican Street Food', price: '$$' },
    ],
    cafes: ['Café Avellaneda', 'Cardinal Casa de Café', 'Café La Habana', 'Buna Coffee Roasters'],
    shopping: ['Mercado de la Ciudadela (crafts)', 'La Roma & Condesa boutiques', 'Mercado de San Juan (gourmet)', 'Zona Rosa'],
    nightlife: ['Mezcalería Bosforo', 'La Roma craft cocktail bars', 'Zona Rosa clubs', 'Lucha libre wrestling nights at Arena México'],
    instagramSpots: ['Frida Kahlo\'s blue-walled Casa Azul courtyard', 'Palacio de Bellas Artes dome', 'Xochimilco\'s colorful trajinera boats', 'Coyoacán\'s painted colonial streets'],
    hiddenGems: ['Museo Anahuacalli (Diego Rivera\'s volcanic-stone museum)', 'San Ángel Saturday art market', 'Luis Barragán House (Pritzker-winning architecture)', 'La Roma\'s quiet residential jacaranda-lined streets in spring'],
    familyActivities: ['Chapultepec Zoo', 'Papalote Museo del Niño', 'Xochimilco canal boat rides', 'Six Flags México'],
    adventureActivities: ['Hot air balloon over Teotihuacan at sunrise', 'Hiking Ajusco or Desierto de los Leones', 'Cycling Paseo de la Reforma on Sunday closures (Ciclovía)', 'Lucha libre wrestling spectator night'],
    luxuryExperiences: ['Tasting menu at Pujol or Quintonil', 'Private guided tour of Teotihuacan with archaeologist', 'Suite stay overlooking Chapultepec Park', 'Private mezcal tasting with a sommelier'],
    honeymoonExperiences: ['Sunset trajinera cruise through Xochimilco with mariachi', 'Rooftop dinner in La Roma with skyline views', 'Private art tour of Frida Kahlo and Diego Rivera sites', 'Wine tasting day trip to Valle de Bravo'],
    budgetExperiences: ['Street taco crawl across multiple stands for a few dollars each', 'Free entry to the Zócalo, Templo Mayor plaza, and murals at the National Palace', 'Sunday Ciclovía bike-friendly boulevard closures', 'Coyoacán market wandering and churros'],
    museums: ['Frida Kahlo Museum', 'National Museum of Anthropology', 'Museo Soumaya', 'Palacio de Bellas Artes'],
    parks: ['Bosque de Chapultepec', 'Parque México (La Roma)', 'Viveros de Coyoacán'],
    beaches: [],
    dayTrips: ['Teotihuacan pyramids', 'Puebla colonial city', 'Xochimilco floating gardens', 'Valle de Bravo lake town'],
    localTransportGuide:
      'The Metro is extremely cheap and extensive but very crowded at rush hour; the Metrobús (dedicated bus lanes along Reforma and Insurgentes) is a comfortable alternative. Ride-hailing apps (Uber, Didi) are the safest and most convenient option for tourists, especially at night — avoid hailing street taxis directly.',
    packingNotes: ['Layers for warm days and cool nights at altitude', 'Comfortable walking shoes for cobblestone historic districts', 'Light rain jacket for the June-September wet season', 'Sunscreen — the high altitude means stronger UV exposure'],
    travelTips: [
      'Use Uber or Didi rather than hailing street taxis, especially after dark.',
      'The altitude (2,240m) can cause mild breathlessness for the first day or two — stay hydrated and pace yourself.',
      'Sunday is when Paseo de la Reforma closes to cars for the Ciclovía — a great day to cycle or walk the boulevard.',
      'Tap water isn\'t potable — stick to bottled or filtered water, widely available everywhere.',
      'Visit Teotihuacan early morning to beat both the heat and tour-bus crowds.',
    ],
    thingsToAvoid: [
      'Hailing unmarked taxis on the street — use a ride-hailing app instead.',
      'Flashing expensive jewelry or phones openly in crowded markets or on the Metro.',
      'Walking alone late at night outside well-lit, busy neighborhoods like La Roma, Condesa, or Polanco.',
      'Drinking tap water or using it to brush teeth.',
    ],
    categories: ['City Break', 'Culture', 'History', 'Food', 'Nightlife', 'Bucket List'],
    heroKeywords: ['Frida Kahlo Casa Azul courtyard', 'Xochimilco colorful trajinera boats', 'Zócalo Mexico City cathedral', 'Teotihuacan pyramids sunrise'],
  },
  {
    slug: 'sao-paulo',
    name: 'São Paulo',
    country: 'Brazil',
    countryCode: 'BR',
    region: 'South America',
    continent: 'South America',
    lat: -23.5505,
    lon: -46.6333,
    airportCode: 'GRU',
    airportName: 'São Paulo/Guarulhos International Airport',
    currency: 'BRL',
    languages: ['Portuguese'],
    timeZone: 'BRT (UTC-3)',
    utcOffset: -3,
    visaSummary:
      'US, Canadian, UK, EU, and Australian citizens can generally enter visa-free for tourism up to 90 days (some nationalities require an e-visa — check current bilateral agreements before travel, as requirements have shifted in recent years).',
    bestTimeToVisit:
      'April to September (Southern Hemisphere autumn/winter) brings mild, dry weather that\'s comfortable for exploring on foot, avoiding the humid, rainy summer months.',
    weatherSummary:
      'Subtropical highland climate — mild year-round due to elevation (760m), with warm, humid, rainy summers (December-March, highs 26-28°C) and cooler, drier winters (June-August, highs around 21°C, occasional cold snaps).',
    safetyRating: 3,
    internetRating: 4,
    transportRating: 4,
    walkingScore: 72,
    accessibilityRating: 3,
    dailyBudgetUSD: [35, 75, 160, 380],
    costIndex: 0.6,
    emergency: { police: '190', ambulance: '192', fire: '193' },
    etiquette: [
      'Greetings are warm — a handshake for business, cheek kisses (one or two) among friends and acquaintances.',
      'Paulistanos dress fashionably and put effort into appearance even for casual outings; shorts and flip-flops are for the beach, not the city.',
      'Meals run late — dinner rarely starts before 8pm, and going out often continues well past midnight.',
      'Punctuality is relaxed for social occasions but expected for business meetings.',
      'Football (soccer) is a serious cultural touchstone — showing enthusiasm (or at least respect) for a local team goes a long way.',
    ],
    festivals: [
      { name: 'São Paulo Carnival', timing: 'February/March (varies with Easter)' },
      { name: 'Virada Cultural (24-hour citywide arts festival)', timing: 'May' },
      { name: 'São Paulo Fashion Week', timing: 'April and October' },
      { name: 'Festa Junina (June harvest festivals)', timing: 'June' },
    ],
    weatherByMonth: [28, 28, 27, 25, 23, 21, 21, 23, 23, 24, 26, 27],
    crowdByMonth: ['High', 'Peak', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'High', 'High'],
    attractionsPaid: [
      { name: 'São Paulo Museum of Art (MASP)', note: 'Iconic red-glass-and-concrete museum with a major European art collection', priceUSD: 8 },
      { name: 'Edifício Copan or Farol Santander viewpoint', note: 'Panoramic city skyline views from a historic downtown tower', priceUSD: 6 },
      { name: 'Museu do Futebol', note: 'Immersive museum inside Pacaembu Stadium on Brazil\'s football culture', priceUSD: 6 },
      { name: 'Sé Cathedral and downtown historic walk', note: 'Neo-Gothic cathedral anchoring the old city center', priceUSD: 0 },
      { name: 'Pinacoteca de São Paulo', note: 'Brazil\'s oldest art museum, housed in a restored 1900s building', priceUSD: 4 },
      { name: 'Football match at Allianz Parque or Morumbi', note: 'Experience Brazilian football fervor live', priceUSD: 30 },
    ],
    attractionsFree: [
      { name: 'Ibirapuera Park', note: 'São Paulo\'s green heart, with museums, lakes, and Oscar Niemeyer buildings' },
      { name: 'Avenida Paulista on Sunday (car-free)', note: 'The city\'s main avenue closes to traffic for pedestrians and street performers' },
      { name: 'Beco do Batman (Batman Alley)', note: 'Vila Madalena alley covered floor-to-ceiling in vibrant street art' },
      { name: 'Mercado Municipal (browsing)', note: 'Historic stained-glass market hall famous for its mortadella sandwich' },
      { name: 'Liberdade neighborhood', note: 'The largest Japanese community outside Japan, with lantern-lined streets' },
      { name: 'Vila Madalena bar-hopping streets', note: 'Bohemian neighborhood of galleries, bars, and murals' },
    ],
    restaurants: [
      { name: 'D.O.M.', cuisine: 'Contemporary Brazilian Fine Dining', price: '$$$$' },
      { name: 'Mocotó', cuisine: 'Northeastern Brazilian', price: '$$' },
      { name: 'Bar da Dona Onça', cuisine: 'Modern Brazilian', price: '$$' },
      { name: 'Mercado Municipal mortadella stalls', cuisine: 'Brazilian Street Food', price: '$' },
      { name: 'Fogo de Chão (original churrascaria)', cuisine: 'Brazilian Steakhouse', price: '$$$' },
      { name: 'Liberdade street-food stalls', cuisine: 'Japanese-Brazilian Fusion', price: '$' },
    ],
    cafes: ['Coffee Lab', 'Isso é Café', 'Suplicy Cafés Especiais', 'Café Floresta'],
    shopping: ['Rua Oscar Freire (luxury boutiques)', 'Mercado Municipal', 'Shopping Iguatemi', 'Feira da Liberdade (weekend market)'],
    nightlife: ['Vila Madalena bar scene', 'Skye Bar rooftop at Hotel Unique', 'D-Edge nightclub', 'Rua Augusta live music venues'],
    instagramSpots: ['Beco do Batman street art alley', 'MASP\'s red suspended concrete facade', 'Ibirapuera Park\'s Niemeyer marquee', 'Avenida Paulista skyline at dusk'],
    hiddenGems: ['Instituto Moreira Salles cultural center', 'Beco do Aprendiz street-art alley', 'Mercado de Pinheiros (locals\' market, less touristy)', 'Parque Burle Marx landscaped gardens'],
    familyActivities: ['Aquário de São Paulo', 'Ibirapuera Park bike rentals', 'Catavento Cultural science museum', 'Zoológico de São Paulo'],
    adventureActivities: ['Hang gliding over São Paulo from Rei Pelé ramp', 'Cycling Ibirapuera Park trails', 'Serra da Cantareira hiking trails', 'Day trip rock climbing near São Bento do Sapucaí'],
    luxuryExperiences: ['Tasting menu at D.O.M. or Tuju', 'Suite stay at a Jardins boutique hotel', 'Private art tour of MASP and Pinacoteca', 'VIP box at an Allianz Parque football match'],
    honeymoonExperiences: ['Sunset drinks at Skye Bar overlooking the skyline', 'Private wine and cheese tasting in Jardins', 'Romantic dinner in Vila Madalena', 'Weekend escape to nearby Campos do Jordão mountain town'],
    budgetExperiences: ['Sunday car-free stroll down Avenida Paulista', 'Mortadella sandwich at Mercado Municipal for a few dollars', 'Free entry to Ibirapuera Park and its museums', 'Beco do Batman street-art photo walk'],
    museums: ['MASP', 'Pinacoteca de São Paulo', 'Museu do Futebol', 'Instituto Moreira Salles'],
    parks: ['Ibirapuera Park', 'Parque Burle Marx', 'Parque Villa-Lobos'],
    beaches: [],
    dayTrips: ['Campos do Jordão mountain town', 'Ilhabela island beaches', 'Embu das Artes crafts town', 'Santos coastal city'],
    localTransportGuide:
      'The Metro is fast, clean, and inexpensive, though it doesn\'t cover every neighborhood — pair it with ride-hailing apps (Uber/99) for the last mile. Traffic is notoriously heavy, so the Metro is usually faster than a car during rush hour. Avoid driving yourself; even locals rely on transit and rideshares.',
    packingNotes: ['Layers — weather shifts quickly across the day', 'Smart-casual clothing; Paulistanos dress well even casually', 'Comfortable shoes for uneven sidewalks', 'A light rain jacket, especially November-March'],
    travelTips: [
      'Use the Metro for cross-city trips during rush hour — traffic can triple travel time by car.',
      'Avenida Paulista closes to cars every Sunday, making it the best day for a car-free walk or bike ride.',
      'Dinner reservations for well-known restaurants (D.O.M., Mocotó) should be made well in advance.',
      'Stick to well-known, busy neighborhoods (Jardins, Vila Madalena, Pinheiros) for evening outings.',
      'Carry a card rather than large amounts of cash, and keep phones out of sight on public transit.',
    ],
    thingsToAvoid: [
      'Walking alone in unfamiliar or poorly-lit neighborhoods at night.',
      'Displaying expensive jewelry, watches, or phones openly on the street or public transit.',
      'Driving yourself — traffic and parking are genuinely difficult even for locals.',
      'Assuming all of Brazil operates on "Brazilian time" for business meetings — punctuality matters professionally.',
    ],
    categories: ['City Break', 'Culture', 'Food', 'Nightlife', 'Shopping', 'Bucket List'],
    heroKeywords: ['MASP museum red facade São Paulo', 'Beco do Batman street art', 'Avenida Paulista skyline', 'Ibirapuera Park Niemeyer architecture'],
  },
  {
    slug: 'jeju-island',
    name: 'Jeju Island',
    country: 'South Korea',
    countryCode: 'KR',
    region: 'East Asia',
    continent: 'Asia',
    lat: 33.4996,
    lon: 126.5312,
    airportCode: 'CJU',
    airportName: 'Jeju International Airport',
    currency: 'KRW',
    languages: ['Korean'],
    timeZone: 'KST (UTC+9)',
    utcOffset: 9,
    visaSummary:
      'Most Western nationalities including the US, UK, Canada, Australia, and EU citizens can enter South Korea visa-free for 30-90 days for tourism (K-ETA pre-authorization required for many nationalities). Verify current requirements against your specific passport before travel.',
    bestTimeToVisit:
      'May and September to October offer mild temperatures, blooming or fresh scenery, and lighter crowds than the peak Korean summer holiday season.',
    weatherSummary:
      'Temperate maritime climate — mild winters (rarely below 5°C), warm humid summers (June-August, highs around 29-31°C with a rainy season and occasional typhoons), and comfortable spring/autumn shoulder seasons famous for canola-flower and cherry-blossom blooms.',
    safetyRating: 5,
    internetRating: 5,
    transportRating: 4,
    walkingScore: 55,
    accessibilityRating: 4,
    dailyBudgetUSD: [40, 85, 180, 400],
    costIndex: 0.75,
    emergency: { police: '112', ambulance: '119', fire: '119' },
    etiquette: [
      'Bowing is a common greeting alongside handshakes; a slight bow when greeting elders or service staff is appreciated.',
      'Remove shoes before entering traditional guesthouses (hanok) and many homes.',
      'Two hands (or supporting your forearm) should be used when giving or receiving items, especially with elders.',
      'Haenyeo (Jeju\'s famous free-diving "sea women") are a source of local pride — treat their diving demonstrations respectfully, not as a photo prop.',
      'Quiet, orderly queuing is the norm, including at popular photo spots.',
    ],
    festivals: [
      { name: 'Jeju Fire Festival', timing: 'March' },
      { name: 'Jeju Canola Flower Festival', timing: 'April' },
      { name: 'Jeju Cherry Blossom Festival', timing: 'Late March-early April' },
      { name: 'Tamna Cultural Festival', timing: 'October' },
    ],
    weatherByMonth: [8, 9, 12, 17, 20, 24, 29, 30, 26, 21, 15, 10],
    crowdByMonth: ['Medium', 'Medium', 'High', 'High', 'Peak', 'Medium', 'Peak', 'Peak', 'Medium', 'High', 'Medium', 'Medium'],
    attractionsPaid: [
      { name: 'Seongsan Ilchulbong (Sunrise Peak)', note: 'UNESCO-listed volcanic tuff cone with sweeping sunrise views', priceUSD: 4 },
      { name: 'Manjanggul Lava Tube', note: 'One of the world\'s finest lava tube cave systems, walkable for 1km', priceUSD: 4 },
      { name: 'Hallim Park', note: 'Botanical garden with sculpted lava-rock landscapes and caves', priceUSD: 11 },
      { name: 'Jeju Loveland', note: 'Quirky outdoor sculpture park (adults-only)', priceUSD: 12 },
      { name: 'Spirited Garden (Bonsai Garden)', note: 'One of Asia\'s most acclaimed bonsai and landscape gardens', priceUSD: 15 },
      { name: 'Teddy Bear Museum', note: 'Family-friendly museum of teddy-bear-recreated art history', priceUSD: 10 },
    ],
    attractionsFree: [
      { name: 'Hallasan National Park trails', note: 'South Korea\'s tallest mountain (1,947m), a dormant volcano with multiple hiking routes' },
      { name: 'Jeju Olle Trail sections', note: 'A network of coastal walking trails circling the island' },
      { name: 'Yongduam Rock (Dragon Head Rock)', note: 'Naturally sculpted volcanic rock formation on the coast' },
      { name: 'Jeju Haenyeo Museum grounds', note: 'Exhibits on the island\'s traditional female free-divers' },
      { name: 'Iho Tewoo Beach', note: 'Beach with iconic red-and-white lighthouse horse statues' },
      { name: 'Cheonjiyeon Waterfall', note: 'Scenic waterfall walk near Seogwipo' },
    ],
    restaurants: [
      { name: 'Jeju black pork BBQ houses (Heukdwaeji Geori)', cuisine: 'Korean BBQ', price: '$$' },
      { name: 'Myeongjin Jeonbok (abalone rice porridge)', cuisine: 'Korean Seafood', price: '$$' },
      { name: 'Halmang Jip', cuisine: 'Traditional Jeju Home Cooking', price: '$$' },
      { name: 'Dombegogi restaurants near Jungmun', cuisine: 'Jeju Pork Specialty', price: '$$' },
      { name: 'Olle Market food stalls', cuisine: 'Korean Street Food', price: '$' },
      { name: 'Seongsan seafood raw fish (hoe) restaurants', cuisine: 'Fresh Raw Seafood', price: '$$$' },
    ],
    cafes: ['Café Momento', 'Monsant Café (oceanview)', 'Anthracite Coffee Jeju', 'Yuedam Café'],
    shopping: ['Jeju Dongmun Market', 'Jungmun Tourist Complex duty-free', 'Lotte Duty Free Jeju', 'Olle Market'],
    nightlife: ['Jeju City downtown bars (Chilsipni-ro)', 'Seogwipo Maeil Olle Market evening stalls', 'Hyatt Regency Jeju lounge', 'Jungmun resort strip bars'],
    instagramSpots: ['Seongsan Ilchulbong sunrise silhouette', 'Iho Tewoo Beach lighthouse horses', 'Canola flower fields in spring', 'Yongduam Rock coastline at sunset'],
    hiddenGems: ['Gimnyeong Maze Park', 'Sangumburi volcanic crater', 'Bijarim Forest\'s ancient nutmeg trees', 'Udo Island bike loop (a short ferry from Seongsan)'],
    familyActivities: ['Teddy Bear Museum', 'Jeju Shinhwa Theme Park', 'Hallim Park caves and gardens', 'Trick Eye Museum Jeju'],
    adventureActivities: ['Hiking Hallasan to the summit crater lake', 'Scuba diving with Jeju\'s haenyeo dive sites', 'Olle Trail multi-day coastal hiking', 'Udo Island cycling loop'],
    luxuryExperiences: ['Suite stay at a Jungmun resort with ocean views', 'Private abalone and black pork tasting course', 'Helicopter tour over Hallasan and the coastline', 'Spa day at a resort onsen-style bathhouse'],
    honeymoonExperiences: ['Sunrise hike up Seongsan Ilchulbong together', 'Private couples\' photo shoot amid canola flower fields', 'Romantic dinner overlooking Jungmun coast', 'Udo Island day trip by bike and ferry'],
    budgetExperiences: ['Olle Trail sections cost nothing beyond good shoes', 'Dongmun Market street food crawl', 'Free coastal viewpoints at Yongduam Rock and Iho Beach', 'Hallasan National Park hiking (entry is free)'],
    museums: ['Jeju Haenyeo Museum', 'Jeju National Museum', 'Trick Eye Museum'],
    parks: ['Hallasan National Park', 'Hallim Park', 'Bijarim Forest'],
    beaches: ['Hyeopjae Beach', 'Iho Tewoo Beach', 'Hamdeok Beach'],
    dayTrips: ['Udo Island (bike loop and peanut ice cream)', 'Marado Island (Korea\'s southernmost point)', 'Seogwipo waterfalls circuit'],
    localTransportGuide:
      'Renting a car is by far the most convenient way to explore Jeju\'s spread-out attractions, and an international driving permit is required. Public buses cover the main towns and attractions but run less frequently in rural areas. Taxis and ride-hailing (Kakao T) are reliable for shorter hops within Jeju City or Seogwipo.',
    packingNotes: ['Hiking shoes for Hallasan and Olle Trail sections', 'Windbreaker — coastal winds are strong year-round', 'Swimwear for summer beach visits', 'Rain gear for the June-July wet season'],
    travelTips: [
      'Rent a car if possible — Jeju\'s best sights are spread across the island and public transit is limited outside the main towns.',
      'Book Hallasan summit trail permits/timed slots in advance during peak season.',
      'Try Jeju\'s famous black pork (heukdwaeji) — it\'s a genuinely distinct local specialty, not just a marketing label.',
      'Seongsan Ilchulbong is best visited at sunrise both for the light and to avoid tour-bus crowds.',
      'Download the Kakao Map app — Google Maps has limited functionality for driving directions in South Korea.',
    ],
    thingsToAvoid: [
      'Relying solely on Google Maps for driving directions — use Kakao Map or Naver Map instead.',
      'Treating haenyeo (traditional divers) demonstrations as a casual photo-op without respect for the tradition.',
      'Visiting Seongsan Ilchulbong or the canola flower fields at midday in peak season, when tour buses crowd every viewpoint.',
      'Underestimating Hallasan\'s summit hike — it\'s a genuine full-day, ~1,950m ascent requiring an early start.',
    ],
    categories: ['Nature', 'Adventure', 'Honeymoon', 'Beach', 'Family'],
    heroKeywords: ['Seongsan Ilchulbong sunrise Jeju', 'Jeju canola flower fields', 'Hallasan volcano summit', 'Udo Island coastline'],
  },
  {
    slug: 'alula',
    name: 'AlUla',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    region: 'Middle East',
    continent: 'Asia',
    lat: 26.6084,
    lon: 37.9214,
    airportCode: 'ULH',
    airportName: 'AlUla International Airport (Prince Abdulmajeed bin Abdulaziz Airport)',
    currency: 'SAR',
    languages: ['Arabic'],
    timeZone: 'AST (UTC+3)',
    utcOffset: 3,
    visaSummary:
      'Most Western nationalities including the US, UK, EU, and Australian citizens can obtain a Saudi e-Visa online in minutes or a visa-on-arrival, valid for multiple entries over one year (90 days per visit). Verify current requirements against your specific passport before travel.',
    bestTimeToVisit:
      'November to February offers cool, comfortable desert temperatures (highs 20-25°C) ideal for exploring Hegra\'s tombs and canyon trails on foot; summer heat is intense and best avoided.',
    weatherSummary:
      'Hot desert climate — scorching summers (May-September, highs regularly above 40°C) and mild, pleasant winters (November-February, highs 20-25°C, cool desert nights). Rain is rare year-round.',
    safetyRating: 5,
    internetRating: 4,
    transportRating: 3,
    walkingScore: 30,
    accessibilityRating: 3,
    dailyBudgetUSD: [60, 130, 280, 650],
    costIndex: 1.0,
    emergency: { police: '999', ambulance: '997', fire: '998' },
    etiquette: [
      'Modest dress is expected for all visitors — shoulders and knees covered; loose, lightweight clothing is both respectful and practical in the heat.',
      'Public displays of affection between couples should be minimal and discreet.',
      'Photography of local people requires permission — always ask first.',
      'Friday is the primary day of prayer; some services and attractions may adjust hours around midday prayer times.',
      'Alcohol is not sold or served anywhere in Saudi Arabia, including international hotels.',
    ],
    festivals: [
      { name: 'AlUla Winter at Tantora Season (arts, music, and desert experiences)', timing: 'December-March' },
      { name: 'Beauty of AlUla balloon festival', timing: 'January' },
      { name: 'Ramadan cultural evenings', timing: 'Varies (Islamic calendar)' },
      { name: 'Saudi National Day', timing: 'September 23' },
    ],
    weatherByMonth: [22, 25, 29, 34, 39, 42, 42, 42, 39, 34, 27, 22],
    crowdByMonth: ['Peak', 'Peak', 'High', 'Medium', 'Low', 'Low', 'Low', 'Low', 'Low', 'Medium', 'High', 'Peak'],
    attractionsPaid: [
      { name: 'Hegra (Mada\'in Salih) guided tour', note: 'Saudi Arabia\'s first UNESCO World Heritage Site — 111 monumental Nabatean tombs carved into sandstone', priceUSD: 25 },
      { name: 'Maraya concert hall visit', note: 'The world\'s largest mirrored building, reflecting the surrounding desert canyon', priceUSD: 15 },
      { name: 'AlUla Old Town walking tour', note: 'Restored century-old mudbrick town beneath the AlUla Fortress', priceUSD: 10 },
      { name: 'Elephant Rock (sunset experience)', note: 'Massive elephant-shaped sandstone formation with a desert lounge for sunset', priceUSD: 0 },
      { name: 'Hot air balloon ride over AlUla valley', note: 'Sunrise balloon flight over Hegra and the surrounding canyons', priceUSD: 250 },
      { name: 'Dadan and Jabal Ikmah rock art sites', note: 'Ancient Lihyanite capital and an open-air "library" of inscriptions', priceUSD: 10 },
    ],
    attractionsFree: [
      { name: 'Elephant Rock viewing area', note: 'Iconic natural sandstone formation, popular at sunset' },
      { name: 'AlUla Arts District (SUPERNOVA and gallery walks)', note: 'Rotating contemporary art installations set against desert scenery' },
      { name: 'Harrat Uwayrid escarpment viewpoints', note: 'Volcanic plateau overlooking the AlUla valley' },
      { name: 'AlUla Old Town exterior walk', note: 'Wander the mudbrick alleyways at golden hour' },
    ],
    restaurants: [
      { name: 'Somewhere by Habitas', cuisine: 'Contemporary Middle Eastern', price: '$$$' },
      { name: 'Basalt Restaurant', cuisine: 'Fine Dining Desert Cuisine', price: '$$$$' },
      { name: 'AlUla Old Town cafes', cuisine: 'Traditional Saudi', price: '$$' },
      { name: 'Fusaifisaa Farm Restaurant', cuisine: 'Farm-to-table Saudi', price: '$$' },
      { name: 'Habitas AlUla dining', cuisine: 'International/Fusion', price: '$$$' },
    ],
    cafes: ['AlUla Old Town coffee houses', 'Traditional Arabic coffee (qahwa) tents at desert camps'],
    shopping: ['AlUla Old Town artisan shops', 'Madrasat Addeera crafts center', 'Local date and incense stalls'],
    nightlife: ['Maraya evening concerts (seasonal)', 'Desert stargazing lounges', 'Winter at Tantora seasonal event nights'],
    instagramSpots: ['Elephant Rock at sunset', 'Hegra\'s Qasr al-Farid tomb (the "Lonely Castle")', 'Maraya mirrored facade reflecting the canyon', 'Hot air balloons over the AlUla valley at sunrise'],
    hiddenGems: ['Jabal Ikmah open-air inscription "library"', 'Harrat Uwayrid lava-field hiking trails', 'Dadan archaeological site (older and quieter than Hegra)', 'Ashar Valley canyon walks'],
    familyActivities: ['AlUla Old Town exploration', 'Elephant Rock desert lounge', 'Stargazing sessions with astronomy guides', 'Camel riding experiences'],
    adventureActivities: ['Hot air ballooning over Hegra', 'Rock climbing in Harrat Uwayrid', 'Desert dune bashing 4x4 tours', 'Multi-day trekking through AlUla\'s canyons'],
    luxuryExperiences: ['Overnight desert camp stay under the stars', 'Private guided tour of Hegra with an archaeologist', 'Sunrise hot air balloon with champagne breakfast (non-alcoholic, per local law)', 'Suite stay at Habitas AlUla eco-resort'],
    honeymoonExperiences: ['Private sunset dinner at Elephant Rock', 'Stargazing under some of the clearest desert skies in the region', 'Hot air balloon ride together at sunrise', 'Overnight luxury desert camp experience'],
    budgetExperiences: ['Elephant Rock at sunset — free to visit', 'AlUla Old Town self-guided walk', 'Harrat Uwayrid viewpoint hikes', 'Public evenings during the Winter at Tantora season'],
    museums: ['AlUla World Heritage Incubator exhibits', 'Hegra visitor center exhibits'],
    parks: [],
    beaches: [],
    dayTrips: ['Madain Saleh extended Hegra tour', 'Tayma ancient oasis', 'Wadi Al Disah canyon (further north)'],
    localTransportGuide:
      'AlUla is spread across a wide desert valley with sites well outside walking distance of each other — nearly all visitors book guided tours or arrange private drivers, as this is the standard and expected way to see Hegra and the surrounding sites (independent access to some heritage areas is restricted). Ride-hailing apps have limited coverage; arranging transport through your hotel or a tour operator is far more reliable.',
    packingNotes: ['Modest, lightweight clothing covering shoulders and knees', 'Sturdy shoes for desert and canyon walking', 'Sun protection — hat, sunglasses, high-SPF sunscreen', 'A warm layer for chilly desert nights in winter'],
    travelTips: [
      'Book Hegra tours in advance — access is guided-only and slots can fill up during the Winter at Tantora season.',
      'Visit in winter (November-February); summer heat regularly exceeds 40°C and many outdoor sites are impractical.',
      'Arrange transport through your hotel or a tour operator rather than relying on ride-hailing apps.',
      'Alcohol is unavailable anywhere in the country — plan accordingly.',
      'Respect photography etiquette — always ask before photographing local people.',
    ],
    thingsToAvoid: [
      'Expecting to visit Hegra independently without a guide — access is tour-guided only.',
      'Visiting in peak summer heat (June-August) without serious sun/heat precautions.',
      'Immodest clothing (shorts, sleeveless tops) outside of resort pool areas.',
      'Assuming alcohol will be available at hotels — it is not sold anywhere in Saudi Arabia.',
    ],
    categories: ['Bucket List', 'History', 'Culture', 'Adventure', 'Luxury', 'Romantic'],
    heroKeywords: ['Hegra Nabatean tombs AlUla', 'Elephant Rock sunset Saudi Arabia', 'Maraya mirrored concert hall desert', 'AlUla hot air balloon sunrise'],
  },
  {
    slug: 'antalya',
    name: 'Antalya',
    country: 'Turkey',
    countryCode: 'TR',
    region: 'Mediterranean',
    continent: 'Europe',
    lat: 36.8969,
    lon: 30.7133,
    airportCode: 'AYT',
    airportName: 'Antalya Airport',
    currency: 'TRY',
    languages: ['Turkish'],
    timeZone: 'TRT (UTC+3)',
    utcOffset: 3,
    visaSummary:
      'US, Canadian, and Australian citizens generally need an e-Visa (obtainable online in minutes); most EU/UK citizens can enter visa-free for short stays. Verify current requirements against your specific passport before travel.',
    bestTimeToVisit:
      'May-June and September-October offer warm, sunny weather ideal for beaches and sightseeing without the intense heat and peak crowds of July-August.',
    weatherSummary:
      'Mediterranean climate — hot, dry summers (June-August, highs 33-36°C) perfect for the beach, and mild, wetter winters (December-February, highs around 15°C) with occasional rain. The sea stays swimmable May through October.',
    safetyRating: 4,
    internetRating: 4,
    transportRating: 4,
    walkingScore: 68,
    accessibilityRating: 3,
    dailyBudgetUSD: [30, 65, 140, 320],
    costIndex: 0.55,
    emergency: { police: '155', ambulance: '112', fire: '110' },
    etiquette: [
      'A polite greeting and small talk before business is customary, even in shops and taxis.',
      'Modest dress is appreciated when visiting mosques (headscarves for women, covered shoulders/knees for all).',
      'Turkish hospitality often includes offers of tea (çay) — accepting is polite, even briefly.',
      'Bargaining is expected and enjoyed in the bazaars of Kaleiçi, but not in fixed-price stores.',
      'Remove shoes when entering a mosque or a local home.',
    ],
    festivals: [
      { name: 'Antalya International Film Festival (Golden Orange)', timing: 'October' },
      { name: 'Aspendos International Opera & Ballet Festival', timing: 'June-July' },
      { name: 'Antalya Sand Sculpture Festival', timing: 'Summer season' },
      { name: 'Republic Day celebrations', timing: 'October 29' },
    ],
    weatherByMonth: [15, 16, 18, 21, 26, 31, 34, 34, 30, 25, 20, 16],
    crowdByMonth: ['Low', 'Low', 'Medium', 'Medium', 'High', 'Peak', 'Peak', 'Peak', 'High', 'Medium', 'Low', 'Low'],
    attractionsPaid: [
      { name: 'Aspendos Roman Theatre', note: 'One of the best-preserved Roman theatres in the world, still used for performances', priceUSD: 6 },
      { name: 'Düden Waterfalls boat tour', note: 'Boat trip to see the falls cascade directly into the Mediterranean', priceUSD: 20 },
      { name: 'Antalya Aquarium', note: 'One of the world\'s longest underwater tunnel aquariums', priceUSD: 25 },
      { name: 'Perge ancient city ruins', note: 'Extensive Greco-Roman ruins including a stadium and colonnaded street', priceUSD: 6 },
      { name: 'Antalya cable car (Tünektepe)', note: 'Panoramic views over the city, mountains, and coastline', priceUSD: 12 },
      { name: 'Köprülü Canyon white-water rafting', note: 'Popular half-day rafting trip through a scenic canyon', priceUSD: 35 },
    ],
    attractionsFree: [
      { name: 'Kaleiçi (old town) streets', note: 'Ottoman-era cobblestone quarter with the historic harbor and Hıdırlık Tower' },
      { name: 'Hadrian\'s Gate', note: 'Roman triumphal arch built for Emperor Hadrian\'s visit in 130 AD' },
      { name: 'Yivli Minare (Fluted Minaret)', note: 'Seljuk-era minaret, a symbol of the city' },
      { name: 'Karaalioğlu Park', note: 'Clifftop park with sweeping Mediterranean and mountain views' },
      { name: 'Antalya Marina promenade', note: 'Yacht-lined harbor walk with restaurants and views' },
    ],
    restaurants: [
      { name: 'Vanilla Lounge', cuisine: 'Modern Mediterranean', price: '$$$' },
      { name: 'Seraser Fine Dining', cuisine: 'Ottoman & Mediterranean Fine Dining', price: '$$$$' },
      { name: 'Parlakoglu Restaurant', cuisine: 'Traditional Turkish', price: '$$' },
      { name: 'Kaleiçi kebab houses', cuisine: 'Turkish Kebab & Grill', price: '$' },
      { name: 'Kral Sofrasi', cuisine: 'Traditional Anatolian', price: '$$' },
      { name: 'Antalya seafront meyhanes', cuisine: 'Turkish Meze & Seafood', price: '$$' },
    ],
    cafes: ['Kaleiçi Turkish tea gardens', 'Sissi Restaurant & Café', 'Marina Lounge cafes', 'Hasanağa Konağı courtyard café'],
    shopping: ['Kaleiçi bazaars', 'MarkAntalya mall', 'TerraCity shopping center', 'Antalya Grand Bazaar'],
    nightlife: ['Kaleiçi harbor bars', 'Marina rooftop lounges', 'Lara Beach clubs', 'Konyaaltı beachfront bars'],
    instagramSpots: ['Kaleiçi harbor with the old town backdrop', 'Düden Waterfalls cliff drop into the sea', 'Yivli Minare against the sky', 'Konyaaltı Beach with Taurus Mountains behind'],
    hiddenGems: ['Termessos ancient mountain city ruins', 'Karain Cave archaeological site', 'Olympos ancient ruins and Chimaera eternal flames', 'Side\'s quieter Temple of Apollo at sunset'],
    familyActivities: ['Antalya Aquarium', 'The Land of Legends theme park', 'Konyaaltı Beach', 'Dolphinarium shows'],
    adventureActivities: ['Köprülü Canyon white-water rafting', 'Paragliding over Antalya\'s coastline', 'Taurus Mountains jeep safari', 'Scuba diving Kaş\'s underwater sites (day trip)'],
    luxuryExperiences: ['Private yacht charter along the Turkish Riviera', 'Spa day at a 5-star Belek resort', 'Fine dining tasting menu at Seraser', 'Private guided tour of Aspendos and Perge'],
    honeymoonExperiences: ['Sunset dinner cruise from Antalya Marina', 'Private beach cabana at a Belek resort', 'Couples Turkish hammam experience', 'Romantic stroll through Kaleiçi\'s lantern-lit lanes'],
    budgetExperiences: ['Free walking tour of Kaleiçi and Hadrian\'s Gate', 'Konyaaltı and Lara public beaches', 'Karaalioğlu Park clifftop views', 'Local kebab and çay for just a few dollars'],
    museums: ['Antalya Museum (Antalya Müzesi)', 'Suna & İnan Kıraç Kaleiçi Museum'],
    parks: ['Karaalioğlu Park', 'Konyaaltı Beach Park'],
    beaches: ['Konyaaltı Beach', 'Lara Beach', 'Cleopatra Beach (Alanya, day trip)'],
    dayTrips: ['Perge and Aspendos ancient cities', 'Termessos mountain ruins', 'Side ancient port town', 'Köprülü Canyon rafting'],
    localTransportGuide:
      'Antalya has an efficient tram (Antray) connecting the airport, city center, and Konyaaltı Beach. Dolmuş (shared minibuses) cover routes buses don\'t, and taxis are metered and affordable. Most beach resorts along the coast (Belek, Side, Lara) are more easily reached by rental car or organized transfer.',
    packingNotes: ['Swimwear and reef-safe sunscreen', 'Comfortable shoes for Kaleiçi\'s cobblestones and ancient ruin sites', 'A light cover-up for mosque visits', 'Light layers for cooler spring/autumn evenings'],
    travelTips: [
      'The Antray tram is the easiest way to get from the airport to Kaleiçi and the beaches.',
      'Visit Aspendos and Perge early morning to avoid both the heat and tour-group crowds.',
      'Bargain at Kaleiçi bazaars — starting around 30-40% below the asking price is normal.',
      'Book Köprülü Canyon rafting trips in advance during July-August peak season.',
      'The sea is warm and swimmable from late May through October.',
    ],
    thingsToAvoid: [
      'Walking Kaleiçi\'s cobblestones in flip-flops or heels — sturdy shoes make a real difference.',
      'Visiting major ruin sites (Aspendos, Perge) at midday in summer without sun protection.',
      'Overpaying at tourist-facing restaurants directly on the marina without checking a menu with prices first.',
      'Assuming taxi meters are always used — confirm the driver starts the meter or agree a fare upfront.',
    ],
    categories: ['Beach', 'History', 'Culture', 'Family', 'Adventure', 'Summer'],
    heroKeywords: ['Kaleiçi old town harbor Antalya', 'Düden Waterfalls sea cliff', 'Aspendos Roman theatre', 'Turkish Riviera coastline'],
  },
  {
    slug: 'kuala-lumpur',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    countryCode: 'MY',
    region: 'Southeast Asia',
    continent: 'Asia',
    lat: 3.1390,
    lon: 101.6869,
    airportCode: 'KUL',
    airportName: 'Kuala Lumpur International Airport',
    currency: 'MYR',
    languages: ['Malay', 'English', 'Mandarin', 'Tamil'],
    timeZone: 'MYT (UTC+8)',
    utcOffset: 8,
    visaSummary:
      'Most Western nationalities including the US, UK, Canada, Australia, and EU citizens can enter visa-free for up to 90 days for tourism. Verify current requirements against your specific passport before travel.',
    bestTimeToVisit:
      'June to August offers a relatively drier window between monsoon seasons, though Kuala Lumpur is warm and humid year-round with rain possible at any time.',
    weatherSummary:
      'Equatorial tropical climate — consistently hot and humid year-round (highs 31-33°C) with frequent afternoon thunderstorms, heaviest during the October-December monsoon season.',
    safetyRating: 4,
    internetRating: 5,
    transportRating: 4,
    walkingScore: 62,
    accessibilityRating: 4,
    dailyBudgetUSD: [30, 65, 140, 320],
    costIndex: 0.55,
    emergency: { police: '999', ambulance: '999', fire: '994' },
    etiquette: [
      'Malaysia is multicultural (Malay, Chinese, Indian) — dress and behave respectfully at each community\'s religious sites: mosques, Buddhist/Taoist temples, and Hindu temples all have their own customs.',
      'Remove shoes before entering mosques, temples, and most homes.',
      'Use your right hand for eating, giving, and receiving items, especially in Malay and Indian communities.',
      'Modest dress is expected at religious sites, including headscarves for women at mosques (usually provided on-site).',
      'Public displays of affection are best kept minimal, particularly at religious or conservative venues.',
    ],
    festivals: [
      { name: 'Hari Raya Aidilfitri (end of Ramadan)', timing: 'Varies (Islamic calendar)' },
      { name: 'Chinese New Year', timing: 'January/February' },
      { name: 'Deepavali (Diwali)', timing: 'October/November' },
      { name: 'Thaipusam at Batu Caves', timing: 'January/February' },
    ],
    weatherByMonth: [32, 33, 33, 33, 33, 33, 32, 32, 32, 32, 31, 31],
    crowdByMonth: ['High', 'Peak', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'High', 'Peak'],
    attractionsPaid: [
      { name: 'Petronas Twin Towers Skybridge & Observation Deck', note: 'Iconic 88-story twin towers, once the world\'s tallest buildings', priceUSD: 25 },
      { name: 'Batu Caves temple complex', note: 'Hindu shrine inside a limestone cave, reached via a colorful 272-step staircase', priceUSD: 0 },
      { name: 'KL Tower (Menara KL) Sky Deck', note: 'Open-air observation deck with panoramic skyline views', priceUSD: 20 },
      { name: 'Aquaria KLCC', note: 'Underwater tunnel aquarium beneath the convention center', priceUSD: 18 },
      { name: 'Islamic Arts Museum Malaysia', note: 'One of the finest collections of Islamic art in Southeast Asia', priceUSD: 4 },
      { name: 'Sunway Lagoon theme park', note: 'Water park, wildlife park, and amusement rides combined', priceUSD: 45 },
    ],
    attractionsFree: [
      { name: 'Batu Caves staircase and grounds', note: 'The 42.7m golden Lord Murugan statue is free to view and photograph' },
      { name: 'KLCC Park & Petronas Towers fountain show', note: 'Landscaped park at the foot of the twin towers with an evening light-and-water show' },
      { name: 'Merdeka Square', note: 'Historic colonial-era square where Malaysian independence was declared' },
      { name: 'Petaling Street (Chinatown)', note: 'Bustling market street for street food and bargain shopping' },
      { name: 'Central Market (browsing)', note: 'Art Deco heritage building of local crafts and galleries' },
      { name: 'Little India, Brickfields', note: 'Colorful, fragrant neighborhood of temples, sarees, and South Indian food' },
    ],
    restaurants: [
      { name: 'Jalan Alor night food street', cuisine: 'Malaysian & Chinese Street Food', price: '$' },
      { name: 'Nasi Kandar Pelita', cuisine: 'Malaysian-Indian', price: '$' },
      { name: 'Dewakan', cuisine: 'Progressive Malaysian Fine Dining', price: '$$$$' },
      { name: 'Village Park Restaurant', cuisine: 'Malay (famous nasi lemak)', price: '$' },
      { name: 'Old China Cafe', cuisine: 'Peranakan (Nyonya)', price: '$$' },
      { name: 'Lot 10 Hutong food court', cuisine: 'Malaysian Hawker Food Hall', price: '$' },
    ],
    cafes: ['VCR Café', 'Pulp by Papa Palheta', 'PS150 speakeasy café', 'Merchant\'s Lane'],
    shopping: ['Bukit Bintang malls (Pavilion, Lot 10)', 'Central Market crafts', 'Petaling Street markets', 'Suria KLCC'],
    nightlife: ['Changkat Bukit Bintang bar strip', 'TREC KL nightclub district', 'Heli Lounge Bar (helipad rooftop bar)', 'Jalan Alor late-night food scene'],
    instagramSpots: ['Petronas Twin Towers at dusk from KLCC Park', 'Batu Caves colorful staircase', 'Merdeka Square colonial architecture', 'Heli Lounge Bar helipad skyline view'],
    hiddenGems: ['Thean Hou Temple hilltop views', 'Kampung Baru traditional Malay village amid skyscrapers', 'Publika art and lifestyle precinct', 'REXKL heritage cinema turned cultural space'],
    familyActivities: ['Aquaria KLCC', 'Sunway Lagoon theme park', 'Petrosains Science Discovery Centre', 'Bird Park and Butterfly Park in the Lake Gardens'],
    adventureActivities: ['Via ferrata / ropes course at Sunway', 'Day trip caving near Batu Caves\' Dark Cave', 'Cycling KL\'s riverside park connectors', 'Genting Highlands cable car and cool-climate hikes (day trip)'],
    luxuryExperiences: ['Tasting menu at Dewakan (Malaysia\'s first Michelin-recognized progressive restaurant)', 'Suite stay overlooking the Petronas Towers', 'Private guided food tour of Jalan Alor and Chinatown', 'Spa day at a KLCC luxury hotel'],
    honeymoonExperiences: ['Sunset drinks at Heli Lounge Bar overlooking the towers', 'Private dinner cruise or rooftop dining with skyline views', 'Couples spa treatment using traditional Malay techniques', 'Evening stroll through KLCC Park\'s fountain show'],
    budgetExperiences: ['Batu Caves visit — free beyond a small optional cave-tour fee', 'Jalan Alor and Petaling Street street food for a few dollars a dish', 'KLCC Park and the Petronas fountain show, both free', 'Central Market and Chinatown wandering'],
    museums: ['Islamic Arts Museum Malaysia', 'National Museum (Muzium Negara)', 'Petrosains Science Discovery Centre'],
    parks: ['KLCC Park', 'Perdana Botanical Garden (Lake Gardens)', 'Titiwangsa Lake Gardens'],
    beaches: [],
    dayTrips: ['Batu Caves', 'Genting Highlands', 'Putrajaya (Malaysia\'s planned federal capital)', 'Malacca (UNESCO-listed historic port city)'],
    localTransportGuide:
      'Kuala Lumpur\'s LRT, MRT, and Monorail network covers most tourist areas cheaply and efficiently, and the KLIA Ekspres train connects the airport to the city center in about 28 minutes. Grab (ride-hailing) is widely used, affordable, and often more convenient than street taxis.',
    packingNotes: ['Lightweight, breathable clothing for constant heat and humidity', 'A modest cover-up/scarf for temple and mosque visits', 'A compact umbrella — afternoon storms are frequent', 'Comfortable shoes for walking between transit stations and malls'],
    travelTips: [
      'Take the KLIA Ekspres train from the airport — it\'s fast, comfortable, and avoids traffic.',
      'Use Grab rather than street taxis for transparent, metered pricing.',
      'Visit Batu Caves early morning to avoid both the heat and the biggest crowds.',
      'Malaysia\'s food scene mixes Malay, Chinese, and Indian cuisines — Jalan Alor and hawker courts are the best way to sample all three.',
      'Malls double as a practical way to escape the heat and humidity between outdoor sightseeing.',
    ],
    thingsToAvoid: [
      'Visiting Batu Caves\' main temple in revealing clothing — modest dress is required inside.',
      'Assuming all of Malaysia serves alcohol freely — some Malay-majority establishments do not.',
      'Underestimating the heat and humidity — pace outdoor sightseeing and stay hydrated.',
      'Haggling aggressively at fixed-price mall stores (bargaining is for markets like Petaling Street, not malls).',
    ],
    categories: ['City Break', 'Food', 'Culture', 'Shopping', 'Family', 'Nightlife'],
    heroKeywords: ['Petronas Twin Towers sunset', 'Batu Caves golden staircase', 'Jalan Alor night food street', 'KLCC Park fountain show'],
  },
  {
    slug: 'sharm-el-sheikh',
    name: 'Sharm El Sheikh',
    country: 'Egypt',
    countryCode: 'EG',
    region: 'Middle East',
    continent: 'Africa',
    lat: 27.9158,
    lon: 34.3300,
    airportCode: 'SSH',
    airportName: 'Sharm El Sheikh International Airport',
    currency: 'EGP',
    languages: ['Arabic'],
    timeZone: 'EET (UTC+2)',
    utcOffset: 2,
    visaSummary:
      'Most Western nationalities including the US, UK, EU, and Australian citizens can obtain a visa-on-arrival or e-Visa; a free Sinai-only entry stamp (up to 15 days) is available for visitors staying solely within the Sharm El Sheikh/Sinai region. Verify current requirements against your specific passport before travel.',
    bestTimeToVisit:
      'March-May and October-November offer warm, comfortable temperatures for diving and sightseeing without the extreme summer heat of June-August.',
    weatherSummary:
      'Hot desert climate with a coastal moderating effect — very hot, dry summers (June-August, highs 38-40°C) and mild, pleasant winters (December-February, highs around 22-23°C). Rain is virtually nonexistent year-round.',
    safetyRating: 4,
    internetRating: 3,
    transportRating: 3,
    walkingScore: 35,
    accessibilityRating: 3,
    dailyBudgetUSD: [35, 75, 160, 380],
    costIndex: 0.6,
    emergency: { police: '122', ambulance: '123', fire: '180' },
    etiquette: [
      'Modest dress is appreciated away from resort pools and beaches, especially in Old Market/Na\'ama Bay town areas.',
      'Tipping (baksheesh) is customary and expected for most services, from dive guides to hotel staff.',
      'Bargaining is standard practice at markets and with taxi fares — always agree a price before starting a ride.',
      'Friday is the main day of prayer; some shops and services may have adjusted hours.',
      'Public displays of affection should be kept minimal outside of resort areas.',
    ],
    festivals: [
      { name: 'Sharm El Sheikh International Film Festival', timing: 'Varies, typically spring' },
      { name: 'Coptic Christmas', timing: 'January 7' },
      { name: 'Eid al-Fitr and Eid al-Adha celebrations', timing: 'Varies (Islamic calendar)' },
      { name: 'Sinai diving season kickoff events', timing: 'March' },
    ],
    weatherByMonth: [23, 24, 27, 31, 35, 38, 40, 40, 37, 33, 28, 24],
    crowdByMonth: ['High', 'Medium', 'Medium', 'Medium', 'Medium', 'High', 'Peak', 'Peak', 'Medium', 'Medium', 'High', 'Peak'],
    attractionsPaid: [
      { name: 'Ras Mohammed National Park snorkeling/diving', note: 'One of the world\'s top dive sites at the tip of the Sinai Peninsula, famous coral walls', priceUSD: 15 },
      { name: 'Tiran Island snorkeling boat trip', note: 'Vivid coral reefs in the Straits of Tiran between Sinai and Saudi Arabia', priceUSD: 40 },
      { name: 'Blue Hole diving (Dahab day trip)', note: 'World-famous deep-water diving sinkhole', priceUSD: 60 },
      { name: 'Colored Canyon & St. Catherine\'s Monastery tour', note: 'Desert canyon hike and visit to one of the world\'s oldest working monasteries', priceUSD: 55 },
      { name: 'Quad biking / desert safari with Bedouin dinner', note: 'Sunset desert excursion with traditional Bedouin hospitality', priceUSD: 35 },
      { name: 'SOHO Square entertainment complex', note: 'Fountains, shows, and dining in Sharm\'s entertainment hub', priceUSD: 0 },
    ],
    attractionsFree: [
      { name: 'Na\'ama Bay promenade', note: 'Palm-lined beachfront strip of cafes, shops, and sea views' },
      { name: 'Old Market (Sharm el Maya)', note: 'Traditional souk area for browsing spices, textiles, and souvenirs' },
      { name: 'Ras Um Sid public viewpoint', note: 'Cliffside lookout over a famous reef and lighthouse' },
      { name: 'Sharm el Sheikh Old Town streets', note: 'Quieter, more local area away from the resort strip' },
    ],
    restaurants: [
      { name: 'Il Mercato', cuisine: 'Italian', price: '$$$' },
      { name: 'Fares Seafood', cuisine: 'Fresh Red Sea Seafood', price: '$$' },
      { name: 'El Fanar Restaurant', cuisine: 'Egyptian & Mediterranean (clifftop views)', price: '$$$' },
      { name: 'Old Market kushari stalls', cuisine: 'Egyptian Street Food', price: '$' },
      { name: 'Rangoli', cuisine: 'Indian', price: '$$' },
      { name: 'Pomodoro', cuisine: 'Italian Beachfront', price: '$$' },
    ],
    cafes: ['Costa Coffee Na\'ama Bay', 'Cinnabon SOHO Square', 'Sanafir Hotel lounge cafes'],
    shopping: ['Old Market souk', 'SOHO Square boutiques', 'Na\'ama Bay Duty Free', 'Nabq beachfront shops'],
    nightlife: ['Pacha Sharm El Sheikh', 'SOHO Square evening fountains and bars', 'Camel Bar (Na\'ama Bay institution)', 'Little Buddha Bar & Restaurant'],
    instagramSpots: ['Ras Mohammed coral reef walls underwater', 'Colored Canyon\'s striated rock formations', 'Na\'ama Bay palm-lined promenade at sunset', 'St. Catherine\'s Monastery against Mount Sinai'],
    hiddenGems: ['Ras Abu Galum protected bay (accessible by camel or boat from Dahab)', 'White Canyon lesser-visited hiking route', 'Nabq Bay mangroves', 'Sharks Bay quieter house-reef snorkeling'],
    familyActivities: ['Glass-bottom boat tours', 'SOHO Square fountain shows', 'Dolphin World Sharm El Sheikh', 'Nabq Bay resort water parks'],
    adventureActivities: ['Scuba diving Ras Mohammed and the SS Thistlegorm wreck', 'Blue Hole diving in Dahab', 'Quad biking and desert safaris', 'Hiking Mount Sinai for sunrise'],
    luxuryExperiences: ['Private yacht snorkeling charter to Tiran Island', 'Liveaboard dive boat to the Straits of Tiran and Ras Mohammed', 'Suite stay at a Nabq Bay 5-star resort', 'Private Bedouin desert dinner experience'],
    honeymoonExperiences: ['Sunset dinner cruise on the Red Sea', 'Private beach cabana at a couples-focused resort', 'Snorkeling together at Ras Mohammed\'s coral gardens', 'Overnight desert camp with stargazing'],
    budgetExperiences: ['Old Market wandering and street food', 'Na\'ama Bay promenade — free to walk', 'Ras Um Sid clifftop viewpoint', 'Snorkeling directly off many public beach areas'],
    museums: [],
    parks: ['Ras Mohammed National Park'],
    beaches: ['Na\'ama Bay', 'Nabq Bay', 'Shark\'s Bay'],
    dayTrips: ['St. Catherine\'s Monastery & Mount Sinai sunrise hike', 'Dahab\'s Blue Hole', 'Colored Canyon desert trek', 'Tiran Island boat excursion'],
    localTransportGuide:
      'Sharm El Sheikh\'s resort areas (Na\'ama Bay, Nabq Bay, Sharm el Maya) are spread along the coast, so taxis (always agree a fare beforehand) or hotel shuttles are the main way to get around. Most excursions — diving, desert safaris, day trips — include pickup and drop-off from your hotel.',
    packingNotes: ['Swimwear and snorkel gear (or rent locally)', 'Reef-safe sunscreen — the Red Sea reefs are ecologically sensitive', 'A light cover-up for visits beyond the resort strip', 'Sturdy sandals for desert excursions'],
    travelTips: [
      'Always agree a taxi fare before the ride begins — meters are uncommon.',
      'Book diving trips with PADI/SSI-certified operators, especially for Ras Mohammed and wreck dives.',
      'Bring cash in small denominations for tipping (baksheesh), which is expected throughout the service industry.',
      'The Red Sea reefs here are among the best-preserved in the world — use reef-safe sunscreen and never touch coral.',
      'Desert safari evenings can get cool — bring a light jacket even in summer.',
    ],
    thingsToAvoid: [
      'Touching or standing on coral while snorkeling or diving — it\'s slow-growing and easily damaged.',
      'Getting into a taxi without agreeing the fare first.',
      'Drinking tap water — stick to bottled water, provided at nearly all resorts.',
      'Wandering into the desert independently without a guide — stick to organized excursions.',
    ],
    categories: ['Beach', 'Adventure', 'Honeymoon', 'Luxury', 'Family'],
    heroKeywords: ['Ras Mohammed coral reef diving', 'Na\'ama Bay promenade sunset', 'Red Sea snorkeling Sharm El Sheikh', 'Colored Canyon Sinai desert'],
  },
  {
    slug: 'ibiza',
    name: 'Ibiza',
    country: 'Spain',
    countryCode: 'ES',
    region: 'Mediterranean',
    continent: 'Europe',
    lat: 38.9067,
    lon: 1.4206,
    airportCode: 'IBZ',
    airportName: 'Ibiza Airport',
    currency: 'EUR',
    languages: ['Spanish', 'Catalan'],
    timeZone: 'CET (UTC+1)',
    utcOffset: 1,
    visaSummary:
      'US, UK, Canadian, and Australian citizens can enter visa-free under the Schengen Area rules for up to 90 days within a 180-day period. EU citizens face no restrictions. Verify current requirements against your specific passport before travel.',
    bestTimeToVisit:
      'June and September offer the island\'s famous nightlife and beach season with noticeably lower prices and crowds than the July-August peak.',
    weatherSummary:
      'Mediterranean climate — hot, dry summers (June-September, highs 28-31°C) perfect for the beach club season, and mild, quiet winters (December-February, highs around 15-16°C) when most clubs and many restaurants close entirely.',
    safetyRating: 4,
    internetRating: 4,
    transportRating: 3,
    walkingScore: 58,
    accessibilityRating: 3,
    dailyBudgetUSD: [45, 100, 220, 550],
    costIndex: 1.05,
    emergency: { police: '112', ambulance: '112', fire: '112' },
    etiquette: [
      'Dress codes at beach clubs and nightclubs can be strict and stylish — check ahead, especially for VIP areas.',
      'Lunch and dinner run later than much of Northern Europe — restaurants often don\'t fill up until 9-10pm.',
      'Ibiza has a strong bohemian/hippie heritage (the famous hippy markets) alongside its clubbing reputation — both cultures are respected locally.',
      'Topless sunbathing is common and accepted on many beaches, though full nudity is generally restricted to designated areas.',
      'Noise ordinances are taken seriously outside licensed venues — residential areas expect quiet after certain hours.',
    ],
    festivals: [
      { name: 'Ibiza opening/closing club season parties', timing: 'May (opening) and October (closing)' },
      { name: 'Festa d\'Estiu (summer solstice celebrations)', timing: 'June' },
      { name: 'Las Dalias Hippy Market', timing: 'Every Saturday, May-October' },
      { name: 'Sant Bartomeu local patron saint festival', timing: 'August' },
    ],
    weatherByMonth: [15, 15, 17, 19, 22, 27, 29, 30, 27, 23, 19, 16],
    crowdByMonth: ['Low', 'Low', 'Low', 'Medium', 'Medium', 'High', 'Peak', 'Peak', 'High', 'Medium', 'Low', 'Low'],
    attractionsPaid: [
      { name: 'Dalt Vila (walled old town) guided tour', note: 'UNESCO World Heritage Renaissance-era fortress walls overlooking the harbor', priceUSD: 10 },
      { name: 'Es Vedrà boat trip', note: 'Circle the mystical uninhabited rock islet by boat, popular for sunset', priceUSD: 45 },
      { name: 'Beach club day bed at Blue Marlin or Ushuaïa', note: 'Iconic sunset beach club experience with DJs and cocktails', priceUSD: 80 },
      { name: 'Hippy Market at Las Dalias', note: 'Bohemian market of handmade crafts, jewelry, and clothing (entry free, budget for shopping)', priceUSD: 0 },
      { name: 'Ibiza nightclub entry (Pacha, Amnesia, Hï Ibiza)', note: 'World-famous superclubs that put Ibiza on the electronic music map', priceUSD: 60 },
      { name: 'Formentera day-trip ferry', note: 'Fast ferry to Ibiza\'s pristine, quieter sister island', priceUSD: 40 },
    ],
    attractionsFree: [
      { name: 'Dalt Vila walls exterior walk', note: 'Wander the fortress ramparts and cathedral square for free' },
      { name: 'Cala Comte sunset viewpoint', note: 'One of the island\'s most photographed sunset beaches' },
      { name: 'Es Vedrà viewpoint from the cliffs', note: 'See the famous rock islet without a boat trip' },
      { name: 'Ibiza Town marina promenade', note: 'Yacht-lined harbor walk beneath Dalt Vila\'s walls' },
    ],
    restaurants: [
      { name: 'La Paloma', cuisine: 'Mediterranean Organic Garden Restaurant', price: '$$$' },
      { name: 'Sa Punta', cuisine: 'Traditional Ibizan Seafood', price: '$$' },
      { name: 'Ca n\'Alfredo', cuisine: 'Classic Ibizan (since 1934)', price: '$$' },
      { name: 'Amante Beach Club', cuisine: 'Mediterranean Cliffside Dining', price: '$$$$' },
      { name: 'Bar Costa (Santa Gertrudis)', cuisine: 'Tapas & Jamón', price: '$$' },
      { name: 'La Paloma', cuisine: 'Farm-to-table Mediterranean', price: '$$$' },
    ],
    cafes: ['Croissant Show (Ibiza Town institution)', 'Cafe Sidney', 'Mister Coffee', 'Wild Beets'],
    shopping: ['Las Dalias Hippy Market', 'Ibiza Town boutiques (Sa Penya)', 'Es Canar hippy market', 'Dalt Vila artisan shops'],
    nightlife: ['Pacha Ibiza', 'Amnesia', 'Hï Ibiza', 'Ushuaïa Ibiza Beach Club', 'DC-10 (underground techno institution)'],
    instagramSpots: ['Es Vedrà at sunset from Cala d\'Hort', 'Dalt Vila\'s cathedral and city walls', 'Cala Comte turquoise water', 'Ibiza Town marina with the old town backdrop'],
    hiddenGems: ['Cala Xarraca\'s clay-mud coves', 'Santa Gertrudis\'s bohemian village square', 'Es Portitxol tiny islet off Punta Galera', 'Formentera\'s Ses Illetes beach (day trip)'],
    familyActivities: ['Aguamar Water Park', 'Cala Bassa\'s calm shallow waters', 'Ibiza Town aquarium (Aquarium Cap Blanc)', 'Formentera cycling day trip'],
    adventureActivities: ['Jet skiing and parasailing at San Antonio Bay', 'Sea kayaking to hidden coves', 'Cycling the island\'s interior countryside', 'Scuba diving around Es Vedrà'],
    luxuryExperiences: ['VIP table at Ushuaïa or Hï Ibiza', 'Private yacht charter around Es Vedrà and Formentera', 'Suite stay at a 5-star Dalt Vila boutique hotel', 'Private chef dinner at a countryside finca villa'],
    honeymoonExperiences: ['Sunset at Café del Mar or Cala Comte', 'Private boat trip around Es Vedrà', 'Romantic dinner in Dalt Vila\'s old town', 'Day trip to quiet, pristine Formentera'],
    budgetExperiences: ['Public beaches (Cala Comte, Cala Bassa) are free to enjoy', 'Dalt Vila\'s fortress walls and old town — free to explore', 'Las Dalias Hippy Market browsing', 'Es Vedrà cliffside viewpoint at sunset'],
    museums: ['Museu d\'Art Contemporani d\'Eivissa', 'Dalt Vila Cathedral and Archaeology Museum'],
    parks: ['Ses Salines Natural Park (salt flats & beaches)'],
    beaches: ['Cala Comte', 'Cala Bassa', 'Playa d\'en Bossa', 'Ses Salines Beach'],
    dayTrips: ['Formentera island (ferry from Ibiza Town)', 'Santa Gertrudis village', 'Es Vedrà and Cala d\'Hort', 'Santa Eulalia countryside'],
    localTransportGuide:
      'Renting a car or scooter is the most practical way to reach Ibiza\'s scattered beaches and villages, especially outside Ibiza Town and San Antonio. Public buses connect main towns but run infrequently, especially off-season. Taxis are reliable but pricier at night; ferries connect to Formentera and mainland Spain.',
    packingNotes: ['Stylish beach-to-club outfits — Ibiza\'s dress culture is part of the experience', 'Reef-safe sunscreen', 'A light jacket for cooler evenings, even in summer', 'Comfortable sandals for Dalt Vila\'s cobblestones'],
    travelTips: [
      'Book superclub tickets (Pacha, Amnesia, Hï Ibiza) online in advance — door prices are higher and lines are long.',
      'Rent a car or scooter to properly explore the island\'s beaches beyond Ibiza Town and San Antonio.',
      'Visit in June or September for the same beach-club atmosphere at lower prices and crowds than peak summer.',
      'Sunset at Café del Mar or Es Vedrà\'s viewpoint is a genuinely iconic, free experience — don\'t skip it.',
      'Many clubs and restaurants close completely November through April — this is a summer-season island.',
    ],
    thingsToAvoid: [
      'Visiting outside May-October expecting nightlife or beach clubs to be open — most close for winter.',
      'Skipping advance beach club/nightclub reservations in July-August, when top venues sell out.',
      'Renting a scooter without proper licensing/insurance — enforcement has tightened in recent years.',
      'Assuming taxis are cheap — short hops can be pricier than expected, especially late at night.',
    ],
    categories: ['Nightlife', 'Beach', 'Luxury', 'Romantic', 'Summer'],
    heroKeywords: ['Es Vedrà sunset Ibiza', 'Dalt Vila old town walls', 'Cala Comte turquoise beach', 'Ibiza beach club DJ sunset'],
  },
];
