-- PostgreSQL seed for Car Rentals database

CREATE TABLE IF NOT EXISTS rental_companies (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  tier VARCHAR(50),
  commission_rate NUMERIC,
  hq_country VARCHAR(100),
  description TEXT
);

INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('enterprise', 'Enterprise Rent-A-Car', 'enterprise', 'midRange', 0.12, 'United States', 'The world''s largest car rental company by fleet size, known for its neighborhood branch network, "We''ll pick you up" service, and consistently strong customer satisfaction scores.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('hertz', 'Hertz', 'hertz', 'premium', 0.13, 'United States', 'One of the oldest and most recognized rental brands worldwide, operating in 160 countries with a premium fleet including the Hertz Ultimate Choice airport experience and a large EV program.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('avis', 'Avis', 'avis', 'premium', 0.13, 'United States', 'A premium global brand famous for the "We try harder" ethos, strong business-travel offerings, and the Avis Preferred loyalty program with counter-free pickup at major airports.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('budget', 'Budget', 'budget', 'budget', 0.11, 'United States', 'Avis Budget Group''s value brand — reliable airport and city rentals at consistently lower rates, popular with leisure travelers and road-trippers across the Americas and Europe.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('sixt', 'Sixt', 'sixt', 'premium', 0.14, 'Germany', 'Germany''s premium mobility group with a famously young, high-spec fleet — heavy on BMW, Mercedes-Benz, and Audi — and fast-growing airport coverage across Europe, North America, and the Gulf.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('europcar', 'Europcar', 'europcar', 'midRange', 0.12, 'France', 'Europe''s largest home-grown rental network, with deep coverage of European cities, rail stations, and airports plus a growing van and truck division for movers and trades.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('national', 'National Car Rental', 'national', 'premium', 0.13, 'United States', 'Enterprise Holdings'' business-travel brand, beloved by frequent flyers for the Emerald Aisle — walk to the aisle, pick any car, and go, no counter required.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('alamo', 'Alamo', 'alamo', 'budget', 0.11, 'United States', 'Enterprise Holdings'' leisure value brand — self-service kiosks, online check-in, and family-friendly rates at major airports across North America and holiday destinations worldwide.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('dollar', 'Dollar Rent A Car', 'dollar', 'budget', 0.11, 'United States', 'Hertz Group''s value brand offering dependable airport rentals with straightforward pricing, aimed squarely at budget-conscious leisure travelers.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('thrifty', 'Thrifty Car Rental', 'thrifty', 'budget', 0.11, 'United States', 'A long-running budget brand under the Hertz umbrella, popular for cheap weekly rates and holiday rentals across the US, Europe, and Australia/New Zealand.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('ace', 'Ace Rent A Car', 'ace', 'budget', 0.1, 'United States', 'An independent US-based discount operator with franchised locations near major airports, undercutting the big brands with no-frills service and off-airport shuttle lots.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('fox', 'Fox Rent A Car', 'fox', 'budget', 0.1, 'United States', 'A deep-discount operator at major US west-coast and sunbelt airports, popular with price-first travelers willing to take a shuttle to an off-airport lot for the lowest rate.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('payless', 'Payless', 'payless', 'budget', 0.1, 'United States', 'Avis Budget Group''s deep-value brand — basic, reliable cars at the lowest prices in the group''s airport portfolio, for travelers who just need wheels.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('green-motion', 'Green Motion', 'green-motion', 'budget', 0.12, 'United Kingdom', 'A UK-founded franchise focused on lower-emission rentals — hybrid and electric-heavy fleets across Europe, the Americas, and beyond, marketed to eco-conscious travelers.') ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('routes', 'Routes Car Rental', 'routes', 'budget', 0.1, 'Canada', 'A Canadian-founded discount operator expanding across North American airports, competing on price with lean off-airport locations and long-rental value.') ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS vehicle_models (
  id VARCHAR(255) PRIMARY KEY,
  brand VARCHAR(100),
  model VARCHAR(100),
  year INT,
  category VARCHAR(50),
  transmission VARCHAR(20),
  fuel_type VARCHAR(30),
  horsepower INT,
  doors INT,
  seats INT,
  price_index NUMERIC
);

INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('toyota-yaris', 'Toyota', 'Yaris', 2024, 'Economy', 'Automatic', 'Petrol', 106, 5, 5, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('hyundai-i20', 'Hyundai', 'i20', 2024, 'Economy', 'Manual', 'Petrol', 84, 5, 5, 0.9) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('kia-picanto', 'Kia', 'Picanto', 2024, 'Economy', 'Manual', 'Petrol', 67, 5, 4, 0.85) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('suzuki-swift', 'Suzuki', 'Swift', 2024, 'Economy', 'Manual', 'Petrol', 82, 5, 5, 0.85) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('fiat-500', 'Fiat', '500', 2023, 'Economy', 'Manual', 'Petrol', 70, 3, 4, 0.9) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('renault-clio', 'Renault', 'Clio', 2024, 'Compact', 'Manual', 'Petrol', 90, 5, 5, 0.95) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('peugeot-208', 'Peugeot', '208', 2024, 'Compact', 'Automatic', 'Petrol', 100, 5, 5, 0.95) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('citroen-c3', 'Citroën', 'C3', 2024, 'Compact', 'Manual', 'Petrol', 83, 5, 5, 0.9) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('vw-polo', 'Volkswagen', 'Polo', 2024, 'Compact', 'Automatic', 'Petrol', 95, 5, 5, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('vw-golf', 'Volkswagen', 'Golf', 2024, 'Compact', 'Automatic', 'Petrol', 130, 5, 5, 1.15) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('skoda-fabia', 'Škoda', 'Fabia', 2024, 'Compact', 'Manual', 'Petrol', 95, 5, 5, 0.9) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mini-cooper', 'Mini', 'Cooper', 2024, 'Compact', 'Automatic', 'Petrol', 136, 3, 4, 1.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mg3', 'MG', 'MG3', 2024, 'Economy', 'Automatic', 'Hybrid', 194, 5, 5, 0.95) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('toyota-corolla', 'Toyota', 'Corolla', 2024, 'Midsize', 'Automatic', 'Hybrid', 140, 4, 5, 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('toyota-camry', 'Toyota', 'Camry', 2024, 'Full Size', 'Automatic', 'Hybrid', 225, 4, 5, 1.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('honda-civic', 'Honda', 'Civic', 2024, 'Midsize', 'Automatic', 'Petrol', 180, 4, 5, 1.25) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('honda-accord', 'Honda', 'Accord', 2024, 'Full Size', 'Automatic', 'Hybrid', 204, 4, 5, 1.45) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('hyundai-elantra', 'Hyundai', 'Elantra', 2024, 'Midsize', 'Automatic', 'Petrol', 147, 4, 5, 1.15) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('kia-k5', 'Kia', 'K5', 2024, 'Full Size', 'Automatic', 'Petrol', 180, 4, 5, 1.35) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('nissan-altima', 'Nissan', 'Altima', 2024, 'Full Size', 'Automatic', 'Petrol', 188, 4, 5, 1.3) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mazda3', 'Mazda', 'Mazda3', 2024, 'Midsize', 'Automatic', 'Petrol', 191, 4, 5, 1.25) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('chevrolet-malibu', 'Chevrolet', 'Malibu', 2024, 'Full Size', 'Automatic', 'Petrol', 163, 4, 5, 1.3) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('skoda-octavia', 'Škoda', 'Octavia', 2024, 'Midsize', 'Automatic', 'Diesel', 150, 5, 5, 1.3) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('vw-passat', 'Volkswagen', 'Passat', 2024, 'Full Size', 'Automatic', 'Diesel', 150, 5, 5, 1.45) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('bmw-3-series', 'BMW', '330i', 2024, 'Premium', 'Automatic', 'Petrol', 255, 4, 5, 2.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mercedes-c-class', 'Mercedes-Benz', 'C 300', 2024, 'Premium', 'Automatic', 'Petrol', 255, 4, 5, 2.3) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('audi-a4', 'Audi', 'A4 45 TFSI', 2024, 'Premium', 'Automatic', 'Petrol', 261, 4, 5, 2.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('volvo-s60', 'Volvo', 'S60 B5', 2024, 'Premium', 'Automatic', 'Hybrid', 247, 4, 5, 2.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('lexus-es', 'Lexus', 'ES 300h', 2024, 'Luxury', 'Automatic', 'Hybrid', 215, 4, 5, 2.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mercedes-e-class', 'Mercedes-Benz', 'E 350', 2024, 'Executive', 'Automatic', 'Petrol', 302, 4, 5, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('bmw-5-series', 'BMW', '530i', 2024, 'Executive', 'Automatic', 'Petrol', 255, 4, 5, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('genesis-g80', 'Genesis', 'G80', 2024, 'Executive', 'Automatic', 'Petrol', 300, 4, 5, 2.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mercedes-s-class', 'Mercedes-Benz', 'S 500', 2024, 'Luxury', 'Automatic', 'Petrol', 429, 4, 5, 5.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('jaguar-xf', 'Jaguar', 'XF P250', 2023, 'Executive', 'Automatic', 'Petrol', 246, 4, 5, 2.9) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('maserati-ghibli', 'Maserati', 'Ghibli GT', 2023, 'Luxury', 'Automatic', 'Hybrid', 330, 4, 5, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('bentley-flying-spur', 'Bentley', 'Flying Spur V8', 2023, 'Luxury', 'Automatic', 'Petrol', 542, 4, 5, 12) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('rolls-royce-ghost', 'Rolls-Royce', 'Ghost', 2023, 'Limousine', 'Automatic', 'Petrol', 563, 4, 5, 20) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('toyota-raize', 'Toyota', 'Raize', 2024, 'Compact SUV', 'Automatic', 'Petrol', 98, 5, 5, 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('hyundai-creta', 'Hyundai', 'Creta', 2024, 'Compact SUV', 'Automatic', 'Petrol', 115, 5, 5, 1.25) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('kia-seltos', 'Kia', 'Seltos', 2024, 'Compact SUV', 'Automatic', 'Petrol', 146, 5, 5, 1.3) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('vw-troc', 'Volkswagen', 'T-Roc', 2024, 'Compact SUV', 'Automatic', 'Petrol', 150, 5, 5, 1.35) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('toyota-rav4', 'Toyota', 'RAV4', 2024, 'Midsize SUV', 'Automatic', 'Hybrid', 219, 5, 5, 1.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('honda-crv', 'Honda', 'CR-V', 2024, 'Midsize SUV', 'Automatic', 'Hybrid', 204, 5, 5, 1.65) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mazda-cx5', 'Mazda', 'CX-5', 2024, 'Midsize SUV', 'Automatic', 'Petrol', 187, 5, 5, 1.55) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('nissan-xtrail', 'Nissan', 'X-Trail', 2024, 'Midsize SUV', 'Automatic', 'Hybrid', 204, 5, 7, 1.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mitsubishi-outlander', 'Mitsubishi', 'Outlander', 2024, 'Midsize SUV', 'Automatic', 'Plug-in Hybrid', 248, 5, 7, 1.65) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('ford-explorer', 'Ford', 'Explorer', 2024, 'Full Size SUV', 'Automatic', 'Petrol', 300, 5, 7, 1.9) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('chevrolet-tahoe', 'Chevrolet', 'Tahoe', 2024, 'Full Size SUV', 'Automatic', 'Petrol', 355, 5, 8, 2.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('jeep-wrangler', 'Jeep', 'Wrangler Unlimited', 2024, 'Full Size SUV', 'Automatic', 'Petrol', 285, 4, 5, 2.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('land-rover-defender', 'Land Rover', 'Defender 110', 2024, 'Luxury SUV', 'Automatic', 'Petrol', 395, 5, 7, 3.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('range-rover-sport', 'Land Rover', 'Range Rover Sport', 2024, 'Luxury SUV', 'Automatic', 'Petrol', 355, 5, 5, 4.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('bmw-x5', 'BMW', 'X5 xDrive40i', 2024, 'Luxury SUV', 'Automatic', 'Petrol', 375, 5, 5, 3.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mercedes-gle', 'Mercedes-Benz', 'GLE 450', 2024, 'Luxury SUV', 'Automatic', 'Petrol', 375, 5, 5, 3.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('audi-q7', 'Audi', 'Q7 55 TFSI', 2024, 'Luxury SUV', 'Automatic', 'Petrol', 335, 5, 7, 3.3) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('volvo-xc90', 'Volvo', 'XC90 B5', 2024, 'Luxury SUV', 'Automatic', 'Hybrid', 247, 5, 7, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('suzuki-jimny', 'Suzuki', 'Jimny', 2024, 'Compact SUV', 'Manual', 'Petrol', 102, 3, 4, 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('ford-mustang-convertible', 'Ford', 'Mustang GT Convertible', 2024, 'Convertible', 'Automatic', 'Petrol', 480, 2, 4, 2.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mini-convertible', 'Mini', 'Cooper S Convertible', 2024, 'Convertible', 'Automatic', 'Petrol', 178, 2, 4, 2.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('bmw-4-convertible', 'BMW', '430i Convertible', 2024, 'Convertible', 'Automatic', 'Petrol', 255, 2, 4, 3.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mazda-mx5', 'Mazda', 'MX-5 Miata', 2024, 'Convertible', 'Manual', 'Petrol', 181, 2, 2, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('porsche-911', 'Porsche', '911 Carrera', 2024, 'Sports Car', 'Automatic', 'Petrol', 379, 2, 4, 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('porsche-boxster', 'Porsche', '718 Boxster', 2024, 'Convertible', 'Automatic', 'Petrol', 300, 2, 2, 5.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('chevrolet-corvette', 'Chevrolet', 'Corvette Stingray', 2024, 'Sports Car', 'Automatic', 'Petrol', 495, 2, 2, 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('ferrari-roma', 'Ferrari', 'Roma', 2023, 'Sports Car', 'Automatic', 'Petrol', 612, 2, 4, 15) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('lamborghini-huracan', 'Lamborghini', 'Huracán EVO', 2023, 'Sports Car', 'Automatic', 'Petrol', 631, 2, 2, 18) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('tesla-model-3', 'Tesla', 'Model 3', 2024, 'Electric Vehicle', 'Automatic', 'Electric', 366, 4, 5, 1.9) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('tesla-model-y', 'Tesla', 'Model Y', 2024, 'Electric Vehicle', 'Automatic', 'Electric', 384, 5, 5, 2.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('byd-atto3', 'BYD', 'Atto 3', 2024, 'Electric Vehicle', 'Automatic', 'Electric', 201, 5, 5, 1.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('byd-seal', 'BYD', 'Seal', 2024, 'Electric Vehicle', 'Automatic', 'Electric', 523, 4, 5, 1.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('polestar-2', 'Polestar', 'Polestar 2', 2024, 'Electric Vehicle', 'Automatic', 'Electric', 421, 5, 5, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('hyundai-ioniq5', 'Hyundai', 'IONIQ 5', 2024, 'Electric Vehicle', 'Automatic', 'Electric', 320, 5, 5, 1.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('kia-ev6', 'Kia', 'EV6', 2024, 'Electric Vehicle', 'Automatic', 'Electric', 320, 5, 5, 1.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('vw-id4', 'Volkswagen', 'ID.4', 2024, 'Electric Vehicle', 'Automatic', 'Electric', 282, 5, 5, 1.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mg4', 'MG', 'MG4 EV', 2024, 'Electric Vehicle', 'Automatic', 'Electric', 201, 5, 5, 1.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('ford-f150', 'Ford', 'F-150 XLT', 2024, 'Pickup Truck', 'Automatic', 'Petrol', 400, 4, 5, 1.9) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('toyota-hilux', 'Toyota', 'Hilux Double Cab', 2024, 'Pickup Truck', 'Automatic', 'Diesel', 201, 4, 5, 1.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('chevrolet-silverado', 'Chevrolet', 'Silverado 1500', 2024, 'Pickup Truck', 'Automatic', 'Petrol', 355, 4, 6, 1.85) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('chrysler-pacifica', 'Chrysler', 'Pacifica', 2024, 'Minivan', 'Automatic', 'Petrol', 287, 5, 7, 1.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('toyota-sienna', 'Toyota', 'Sienna', 2024, 'Minivan', 'Automatic', 'Hybrid', 245, 5, 8, 1.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('vw-multivan', 'Volkswagen', 'Multivan', 2024, 'Passenger Van', 'Automatic', 'Diesel', 150, 5, 7, 1.9) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mercedes-vito-tourer', 'Mercedes-Benz', 'Vito Tourer (9-seat)', 2024, 'Passenger Van', 'Automatic', 'Diesel', 163, 5, 9, 2.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('ford-transit-12', 'Ford', 'Transit Passenger (12-seat)', 2024, 'Passenger Van', 'Automatic', 'Petrol', 275, 4, 12, 2.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('ford-transit-15', 'Ford', 'Transit Passenger (15-seat)', 2024, 'Passenger Van', 'Automatic', 'Petrol', 275, 4, 15, 2.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('toyota-hiace', 'Toyota', 'HiAce Commuter (12-seat)', 2024, 'Passenger Van', 'Automatic', 'Diesel', 174, 4, 12, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('ford-transit-cargo', 'Ford', 'Transit Cargo LWB', 2024, 'Cargo Van', 'Automatic', 'Diesel', 170, 4, 3, 1.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('mercedes-sprinter-cargo', 'Mercedes-Benz', 'Sprinter Cargo', 2024, 'Cargo Van', 'Automatic', 'Diesel', 168, 4, 3, 1.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('renault-master', 'Renault', 'Master L3H2', 2024, 'Cargo Van', 'Manual', 'Diesel', 150, 4, 3, 1.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('winnebago-solis', 'Winnebago', 'Solis Camper Van', 2024, 'Motorhome / RV', 'Automatic', 'Petrol', 280, 3, 4, 3.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO vehicle_models (id, brand, model, year, category, transmission, fuel_type, horsepower, doors, seats, price_index) VALUES ('vw-california', 'Volkswagen', 'California Ocean', 2024, 'Motorhome / RV', 'Automatic', 'Diesel', 150, 4, 4, 3) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS rental_locations (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255),
  type VARCHAR(30),
  city VARCHAR(100),
  country VARCHAR(100),
  country_code VARCHAR(2),
  region VARCHAR(30),
  lat NUMERIC,
  lon NUMERIC,
  currency VARCHAR(3),
  airport_code VARCHAR(3),
  cost_index NUMERIC
);

INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('jfk-airport', 'New York JFK International Airport', 'airport', 'New York', 'United States', 'US', 'north-america', 40.6413, -73.7781, 'USD', 'JFK', 1.35) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('lax-airport', 'Los Angeles International Airport', 'airport', 'Los Angeles', 'United States', 'US', 'north-america', 33.9416, -118.4085, 'USD', 'LAX', 1.25) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('mia-airport', 'Miami International Airport', 'airport', 'Miami', 'United States', 'US', 'north-america', 25.7959, -80.287, 'USD', 'MIA', 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('ord-airport', 'Chicago O''Hare International Airport', 'airport', 'Chicago', 'United States', 'US', 'north-america', 41.9742, -87.9073, 'USD', 'ORD', 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('mco-airport', 'Orlando International Airport', 'airport', 'Orlando', 'United States', 'US', 'north-america', 28.4312, -81.3081, 'USD', 'MCO', 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('las-airport', 'Las Vegas Harry Reid International Airport', 'airport', 'Las Vegas', 'United States', 'US', 'north-america', 36.086, -115.1539, 'USD', 'LAS', 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('sfo-airport', 'San Francisco International Airport', 'airport', 'San Francisco', 'United States', 'US', 'north-america', 37.6213, -122.379, 'USD', 'SFO', 1.35) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('dfw-airport', 'Dallas/Fort Worth International Airport', 'airport', 'Dallas', 'United States', 'US', 'north-america', 32.8998, -97.0403, 'USD', 'DFW', 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('sea-airport', 'Seattle-Tacoma International Airport', 'airport', 'Seattle', 'United States', 'US', 'north-america', 47.4502, -122.3088, 'USD', 'SEA', 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('yyz-airport', 'Toronto Pearson International Airport', 'airport', 'Toronto', 'Canada', 'CA', 'north-america', 43.6777, -79.6248, 'CAD', 'YYZ', 1.15) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('yvr-airport', 'Vancouver International Airport', 'airport', 'Vancouver', 'Canada', 'CA', 'north-america', 49.1967, -123.1815, 'CAD', 'YVR', 1.15) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('mex-airport', 'Mexico City International Airport', 'airport', 'Mexico City', 'Mexico', 'MX', 'north-america', 19.4363, -99.0721, 'MXN', 'MEX', 0.75) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('cun-airport', 'Cancún International Airport', 'airport', 'Cancún', 'Mexico', 'MX', 'north-america', 21.0365, -86.8771, 'MXN', 'CUN', 0.85) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('manhattan-downtown', 'Manhattan Midtown Office', 'downtown', 'New York', 'United States', 'US', 'north-america', 40.7549, -73.984, 'USD', NULL, 1.45) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('miami-cruise-port', 'PortMiami Cruise Terminal Desk', 'cruise-port', 'Miami', 'United States', 'US', 'north-america', 25.7781, -80.1774, 'USD', NULL, 1.25) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('la-downtown', 'Downtown Los Angeles Office', 'downtown', 'Los Angeles', 'United States', 'US', 'north-america', 34.0407, -118.2468, 'USD', NULL, 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('orlando-downtown', 'Orlando International Drive Office', 'city-office', 'Orlando', 'United States', 'US', 'north-america', 28.4744, -81.4679, 'USD', NULL, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('toronto-union-station', 'Toronto Union Station Rail Desk', 'rail-station', 'Toronto', 'Canada', 'CA', 'north-america', 43.6453, -79.3806, 'CAD', NULL, 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('lhr-airport', 'London Heathrow Airport', 'airport', 'London', 'United Kingdom', 'GB', 'europe', 51.47, -0.4543, 'GBP', 'LHR', 1.3) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('lgw-airport', 'London Gatwick Airport', 'airport', 'London', 'United Kingdom', 'GB', 'europe', 51.1537, -0.1821, 'GBP', 'LGW', 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('cdg-airport', 'Paris Charles de Gaulle Airport', 'airport', 'Paris', 'France', 'FR', 'europe', 49.0097, 2.5479, 'EUR', 'CDG', 1.25) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('fra-airport', 'Frankfurt Airport', 'airport', 'Frankfurt', 'Germany', 'DE', 'europe', 50.0379, 8.5622, 'EUR', 'FRA', 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('muc-airport', 'Munich Airport', 'airport', 'Munich', 'Germany', 'DE', 'europe', 48.3538, 11.7861, 'EUR', 'MUC', 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('mad-airport', 'Madrid-Barajas Airport', 'airport', 'Madrid', 'Spain', 'ES', 'europe', 40.4983, -3.5676, 'EUR', 'MAD', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('bcn-airport', 'Barcelona-El Prat Airport', 'airport', 'Barcelona', 'Spain', 'ES', 'europe', 41.2974, 2.0833, 'EUR', 'BCN', 1.05) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('fco-airport', 'Rome Fiumicino Airport', 'airport', 'Rome', 'Italy', 'IT', 'europe', 41.8003, 12.2389, 'EUR', 'FCO', 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('mxp-airport', 'Milan Malpensa Airport', 'airport', 'Milan', 'Italy', 'IT', 'europe', 45.63, 8.7231, 'EUR', 'MXP', 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('ams-airport', 'Amsterdam Schiphol Airport', 'airport', 'Amsterdam', 'Netherlands', 'NL', 'europe', 52.3105, 4.7683, 'EUR', 'AMS', 1.25) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('zrh-airport', 'Zurich Airport', 'airport', 'Zurich', 'Switzerland', 'CH', 'europe', 47.4582, 8.5555, 'CHF', 'ZRH', 1.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('vie-airport', 'Vienna International Airport', 'airport', 'Vienna', 'Austria', 'AT', 'europe', 48.1103, 16.5697, 'EUR', 'VIE', 1.15) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('lis-airport', 'Lisbon Humberto Delgado Airport', 'airport', 'Lisbon', 'Portugal', 'PT', 'europe', 38.7756, -9.1354, 'EUR', 'LIS', 0.95) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('ath-airport', 'Athens International Airport', 'airport', 'Athens', 'Greece', 'GR', 'europe', 37.9364, 23.9445, 'EUR', 'ATH', 0.95) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('dub-airport', 'Dublin Airport', 'airport', 'Dublin', 'Ireland', 'IE', 'europe', 53.4264, -6.2499, 'EUR', 'DUB', 1.15) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('ist-airport', 'Istanbul Airport', 'airport', 'Istanbul', 'Turkey', 'TR', 'europe', 41.2753, 28.7519, 'TRY', 'IST', 0.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('ayt-airport', 'Antalya Airport', 'airport', 'Antalya', 'Turkey', 'TR', 'europe', 36.8987, 30.8005, 'TRY', 'AYT', 0.75) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('st-pancras-rail', 'London St Pancras International Rail Desk', 'rail-station', 'London', 'United Kingdom', 'GB', 'europe', 51.5322, -0.1263, 'GBP', NULL, 1.25) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('gare-de-lyon-rail', 'Paris Gare de Lyon Rail Desk', 'rail-station', 'Paris', 'France', 'FR', 'europe', 48.8443, 2.3743, 'EUR', NULL, 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('berlin-hbf-rail', 'Berlin Hauptbahnhof Rail Desk', 'rail-station', 'Berlin', 'Germany', 'DE', 'europe', 52.525, 13.3694, 'EUR', NULL, 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('barcelona-cruise-port', 'Barcelona Cruise Terminal Desk', 'cruise-port', 'Barcelona', 'Spain', 'ES', 'europe', 41.3772, 2.1812, 'EUR', NULL, 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('civitavecchia-cruise-port', 'Civitavecchia (Rome) Cruise Terminal Desk', 'cruise-port', 'Rome', 'Italy', 'IT', 'europe', 42.0963, 11.7891, 'EUR', NULL, 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('paris-downtown', 'Paris Opéra District Office', 'downtown', 'Paris', 'France', 'FR', 'europe', 48.8709, 2.3323, 'EUR', NULL, 1.25) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('rome-downtown', 'Rome Termini District Office', 'downtown', 'Rome', 'Italy', 'IT', 'europe', 41.9011, 12.5011, 'EUR', NULL, 1.05) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('dxb-airport', 'Dubai International Airport', 'airport', 'Dubai', 'United Arab Emirates', 'AE', 'middle-east', 25.2532, 55.3657, 'AED', 'DXB', 1.15) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('dubai-downtown', 'Dubai Downtown / Sheikh Zayed Road Office', 'downtown', 'Dubai', 'United Arab Emirates', 'AE', 'middle-east', 25.2048, 55.2708, 'AED', NULL, 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('auh-airport', 'Abu Dhabi Zayed International Airport', 'airport', 'Abu Dhabi', 'United Arab Emirates', 'AE', 'middle-east', 24.4539, 54.6511, 'AED', 'AUH', 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('doh-airport', 'Doha Hamad International Airport', 'airport', 'Doha', 'Qatar', 'QA', 'middle-east', 25.2731, 51.6081, 'QAR', 'DOH', 1.15) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('jed-airport', 'Jeddah King Abdulaziz International Airport', 'airport', 'Jeddah', 'Saudi Arabia', 'SA', 'middle-east', 21.6796, 39.1565, 'SAR', 'JED', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('tlv-airport', 'Tel Aviv Ben Gurion Airport', 'airport', 'Tel Aviv', 'Israel', 'IL', 'middle-east', 32.0055, 34.8854, 'ILS', 'TLV', 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('del-airport', 'Delhi Indira Gandhi International Airport', 'airport', 'New Delhi', 'India', 'IN', 'asia', 28.5562, 77.1, 'INR', 'DEL', 0.55) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('bom-airport', 'Mumbai Chhatrapati Shivaji Maharaj International Airport', 'airport', 'Mumbai', 'India', 'IN', 'asia', 19.0896, 72.8656, 'INR', 'BOM', 0.55) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('sin-airport', 'Singapore Changi Airport', 'airport', 'Singapore', 'Singapore', 'SG', 'asia', 1.3644, 103.9915, 'SGD', 'SIN', 1.35) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('hnd-airport', 'Tokyo Haneda Airport', 'airport', 'Tokyo', 'Japan', 'JP', 'asia', 35.5494, 139.7798, 'JPY', 'HND', 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('kix-airport', 'Osaka Kansai International Airport', 'airport', 'Osaka', 'Japan', 'JP', 'asia', 34.4342, 135.2328, 'JPY', 'KIX', 1.15) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('icn-airport', 'Seoul Incheon International Airport', 'airport', 'Seoul', 'South Korea', 'KR', 'asia', 37.4602, 126.4407, 'KRW', 'ICN', 1.1) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('bkk-airport', 'Bangkok Suvarnabhumi Airport', 'airport', 'Bangkok', 'Thailand', 'TH', 'asia', 13.69, 100.7501, 'THB', 'BKK', 0.65) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('kul-airport', 'Kuala Lumpur International Airport', 'airport', 'Kuala Lumpur', 'Malaysia', 'MY', 'asia', 2.7456, 101.7099, 'MYR', 'KUL', 0.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('hkg-airport', 'Hong Kong International Airport', 'airport', 'Hong Kong', 'Hong Kong SAR', 'HK', 'asia', 22.308, 113.9185, 'HKD', 'HKG', 1.3) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('dps-airport', 'Bali Ngurah Rai International Airport', 'airport', 'Denpasar', 'Indonesia', 'ID', 'asia', -8.7482, 115.1672, 'IDR', 'DPS', 0.55) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('syd-airport', 'Sydney Kingsford Smith Airport', 'airport', 'Sydney', 'Australia', 'AU', 'oceania', -33.9399, 151.1753, 'AUD', 'SYD', 1.2) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('mel-airport', 'Melbourne Airport', 'airport', 'Melbourne', 'Australia', 'AU', 'oceania', -37.669, 144.841, 'AUD', 'MEL', 1.15) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('akl-airport', 'Auckland Airport', 'airport', 'Auckland', 'New Zealand', 'NZ', 'oceania', -37.0082, 174.785, 'NZD', 'AKL', 1.15) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('sydney-downtown', 'Sydney CBD Office', 'downtown', 'Sydney', 'Australia', 'AU', 'oceania', -33.8688, 151.2093, 'AUD', NULL, 1.15) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('gru-airport', 'São Paulo/Guarulhos International Airport', 'airport', 'São Paulo', 'Brazil', 'BR', 'south-america', -23.4356, -46.4731, 'BRL', 'GRU', 0.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('eze-airport', 'Buenos Aires Ezeiza International Airport', 'airport', 'Buenos Aires', 'Argentina', 'AR', 'south-america', -34.8222, -58.5358, 'ARS', 'EZE', 0.65) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('scl-airport', 'Santiago Arturo Merino Benítez Airport', 'airport', 'Santiago', 'Chile', 'CL', 'south-america', -33.393, -70.7858, 'CLP', 'SCL', 0.75) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('cpt-airport', 'Cape Town International Airport', 'airport', 'Cape Town', 'South Africa', 'ZA', 'africa', -33.9715, 18.6021, 'ZAR', 'CPT', 0.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('jnb-airport', 'Johannesburg O.R. Tambo International Airport', 'airport', 'Johannesburg', 'South Africa', 'ZA', 'africa', -26.1367, 28.246, 'ZAR', 'JNB', 0.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('cmn-airport', 'Casablanca Mohammed V International Airport', 'airport', 'Casablanca', 'Morocco', 'MA', 'africa', 33.3675, -7.5898, 'MAD', 'CMN', 0.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO rental_locations (id, name, type, city, country, country_code, region, lat, lon, currency, airport_code, cost_index) VALUES ('nbo-airport', 'Nairobi Jomo Kenyatta International Airport', 'airport', 'Nairobi', 'Kenya', 'KE', 'africa', -1.3192, 36.9278, 'KES', 'NBO', 0.65) ON CONFLICT (id) DO NOTHING;
