-- MySQL seed for Car Rentals database

CREATE TABLE IF NOT EXISTS rental_companies (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  tier VARCHAR(50),
  commission_rate DECIMAL(5,2),
  hq_country VARCHAR(100),
  description TEXT
);

INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('enterprise', 'Enterprise Rent-A-Car', 'enterprise', 'midRange', 0.12, 'United States', 'The world''s largest car rental company by fleet size, known for its neighborhood branch network, "We''ll pick you up" service, and consistently strong customer satisfaction scores.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('hertz', 'Hertz', 'hertz', 'premium', 0.13, 'United States', 'One of the oldest and most recognized rental brands worldwide, operating in 160 countries with a premium fleet including the Hertz Ultimate Choice airport experience and a large EV program.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('avis', 'Avis', 'avis', 'premium', 0.13, 'United States', 'A premium global brand famous for the "We try harder" ethos, strong business-travel offerings, and the Avis Preferred loyalty program with counter-free pickup at major airports.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('budget', 'Budget', 'budget', 'budget', 0.11, 'United States', 'Avis Budget Group''s value brand — reliable airport and city rentals at consistently lower rates, popular with leisure travelers and road-trippers across the Americas and Europe.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('sixt', 'Sixt', 'sixt', 'premium', 0.14, 'Germany', 'Germany''s premium mobility group with a famously young, high-spec fleet — heavy on BMW, Mercedes-Benz, and Audi — and fast-growing airport coverage across Europe, North America, and the Gulf.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('europcar', 'Europcar', 'europcar', 'midRange', 0.12, 'France', 'Europe''s largest home-grown rental network, with deep coverage of European cities, rail stations, and airports plus a growing van and truck division for movers and trades.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('national', 'National Car Rental', 'national', 'premium', 0.13, 'United States', 'Enterprise Holdings'' business-travel brand, beloved by frequent flyers for the Emerald Aisle — walk to the aisle, pick any car, and go, no counter required.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('alamo', 'Alamo', 'alamo', 'budget', 0.11, 'United States', 'Enterprise Holdings'' leisure value brand — self-service kiosks, online check-in, and family-friendly rates at major airports across North America and holiday destinations worldwide.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('dollar', 'Dollar Rent A Car', 'dollar', 'budget', 0.11, 'United States', 'Hertz Group''s value brand offering dependable airport rentals with straightforward pricing, aimed squarely at budget-conscious leisure travelers.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('thrifty', 'Thrifty Car Rental', 'thrifty', 'budget', 0.11, 'United States', 'A long-running budget brand under the Hertz umbrella, popular for cheap weekly rates and holiday rentals across the US, Europe, and Australia/New Zealand.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('ace', 'Ace Rent A Car', 'ace', 'budget', 0.1, 'United States', 'An independent US-based discount operator with franchised locations near major airports, undercutting the big brands with no-frills service and off-airport shuttle lots.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('fox', 'Fox Rent A Car', 'fox', 'budget', 0.1, 'United States', 'A deep-discount operator at major US west-coast and sunbelt airports, popular with price-first travelers willing to take a shuttle to an off-airport lot for the lowest rate.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('payless', 'Payless', 'payless', 'budget', 0.1, 'United States', 'Avis Budget Group''s deep-value brand — basic, reliable cars at the lowest prices in the group''s airport portfolio, for travelers who just need wheels.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('green-motion', 'Green Motion', 'green-motion', 'budget', 0.12, 'United Kingdom', 'A UK-founded franchise focused on lower-emission rentals — hybrid and electric-heavy fleets across Europe, the Americas, and beyond, marketed to eco-conscious travelers.');
INSERT IGNORE INTO rental_companies (id, name, slug, tier, commission_rate, hq_country, description) VALUES ('routes', 'Routes Car Rental', 'routes', 'budget', 0.1, 'Canada', 'A Canadian-founded discount operator expanding across North American airports, competing on price with lean off-airport locations and long-rental value.');
