-- MySQL seed for Cruises database

CREATE TABLE IF NOT EXISTS cruise_lines (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  river_cruise BOOLEAN,
  expedition_cruise BOOLEAN,
  adults_only BOOLEAN,
  luxury_level VARCHAR(50),
  commission_rate DECIMAL(5,2),
  hq_country VARCHAR(100),
  description TEXT
);

INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('royal-caribbean', 'Royal Caribbean International', 'royal-caribbean', FALSE, FALSE, FALSE, 'midRange', 0.12, 'United States', 'Known for building the world''s largest, most innovative cruise ships featuring rock-climbing walls, ice-skating rinks, surf simulators, and Broadway-style shows. Ideal for active families and couples.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('carnival', 'Carnival Cruise Line', 'carnival', FALSE, FALSE, FALSE, 'budget', 0.1, 'United States', 'The "Choose Fun" cruise line, offering high-energy, value-packed ocean cruises with water parks, casual dining, and a festive atmosphere. Great for families, groups, and solo travelers.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('norwegian', 'Norwegian Cruise Line', 'norwegian', FALSE, FALSE, FALSE, 'midRange', 0.12, 'United States', 'Pioneered "Freestyle Cruising" with no set dining times or dress codes. Features impressive entertainment, top-tier restaurants, go-kart racetracks, and dedicated studio cabins for solo travelers.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('msc', 'MSC Cruises', 'msc', FALSE, FALSE, FALSE, 'budget', 0.1, 'Switzerland', 'A European-inspired cruise line offering modern, stylish mega-ships, an international onboard atmosphere, and a premium "ship-within-a-ship" concept with the MSC Yacht Club.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('princess', 'Princess Cruises', 'princess', FALSE, FALSE, FALSE, 'midRange', 0.12, 'United States', 'Famous as the cruise line from "The Love Boat." Princess focuses on destination-rich itineraries, culinary excellence, and technological innovation with the MedallionClass experience.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('celebrity', 'Celebrity Cruises', 'celebrity', FALSE, FALSE, FALSE, 'premium', 0.13, 'United States', 'Offers a "new luxury" experience blending modern design, high-end culinary options, and excellent service. Known for its iconic Lawn Clubs with real grass and Edge-class outward-facing designs.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('holland-america', 'Holland America Line', 'holland-america', FALSE, FALSE, FALSE, 'midRange', 0.12, 'United States', 'A classic, refined cruise line specializing in destination immersion, culinary arts, and live music. Attracts mature couples, multi-generational families, and world cruise travelers.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('disney', 'Disney Cruise Line', 'disney', FALSE, FALSE, FALSE, 'premium', 0.1, 'United States', 'The ultimate family cruise experience combining legendary Disney service, character meet-and-greets, rotational dining, themed deck parties, and dedicated adults-only areas.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('virgin-voyages', 'Virgin Voyages', 'virgin-voyages', FALSE, FALSE, TRUE, 'premium', 0.15, 'United States', 'An adults-only (18+), luxury-casual cruise line. Replaces buffets and dress codes with 20+ specialty restaurants, yacht-inspired design, dynamic fitness classes, and high-energy nightlife.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('cunard', 'Cunard Line', 'cunard', FALSE, FALSE, FALSE, 'premium', 0.12, 'United Kingdom', 'Sophisticated ocean liner travel capturing the golden age of ocean travel. Renowned for transatlantic crossings, formal gala nights, white-glove Afternoon Tea, and royal class service.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('oceania', 'Oceania Cruises', 'oceania', FALSE, FALSE, FALSE, 'premium', 0.14, 'United States', 'Renowned for serving "The Finest Cuisine at Sea," Oceania offers mid-sized, elegant ships that focus on culinary excellence, destination-focused itineraries, and a club-like atmosphere.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('regent-seven-seas', 'Regent Seven Seas Cruises', 'regent-seven-seas', FALSE, FALSE, FALSE, 'luxury', 0.16, 'United States', 'An ultra-luxury, all-inclusive cruise experience. Fares include round-trip flights, unlimited shore excursions, premium drinks, fine dining, Wi-Fi, laundry service, and gratuities.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('silversea', 'Silversea Cruises', 'silversea', FALSE, TRUE, FALSE, 'luxury', 0.16, 'Monaco', 'An ultra-luxury line known for intimate small ships, butler service for every suite, and a robust fleet of luxury expedition ships sailing to the polar regions and Galapagos.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('seabourn', 'Seabourn Cruise Line', 'seabourn', FALSE, TRUE, FALSE, 'luxury', 0.16, 'United States', 'Pioneered ultra-luxury cruising with small, yacht-like ships. Features open bars, Caviar in the Surf beach parties, and partnerships with Chef Thomas Keller.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('azamara', 'Azamara', 'azamara', FALSE, FALSE, FALSE, 'premium', 0.14, 'United States', 'A premium boutique line focusing on Destination Immersion. Offers longer stays, overnights in port, and unique cultural experiences like the AzAmazing Evening.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('viking-ocean', 'Viking Ocean Cruises', 'viking-ocean', FALSE, FALSE, TRUE, 'premium', 0.15, 'Switzerland', 'An adults-only (18+), highly-rated ocean cruise line focusing on history, culture, and science. Free of casinos, children, and hidden fees, with a Nordic design aesthetic.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('viking-river', 'Viking River Cruises', 'viking-river', TRUE, FALSE, TRUE, 'premium', 0.15, 'Switzerland', 'The world''s leading river cruise line, operating a massive fleet of Longships across Europe, Egypt, Asia, and the Mississippi. Focuses on local history and culture.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('amawaterways', 'AmaWaterways', 'amawaterways', TRUE, FALSE, FALSE, 'premium', 0.15, 'United States', 'A premier river cruise line known for active excursions (carrying a fleet of bicycles), award-winning cuisine, Chef''s Table dining, and innovative double-balcony suites.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('avalon', 'Avalon Waterways', 'avalon', TRUE, FALSE, FALSE, 'premium', 0.14, 'United States', 'Known for its "Suite Ships" featuring Panorama Suites with wall-to-wall, floor-to-ceiling windows that open to create a giant Open-Air Balcony. Offers active and discovery cruises.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('scenic', 'Scenic Cruises', 'scenic', TRUE, TRUE, FALSE, 'luxury', 0.16, 'Australia', 'Offers 5-star, truly all-inclusive luxury river cruises in Europe and Asia, and ultra-luxury ocean voyages on the Scenic Eclipse "Discovery Yachts" equipped with helicopters and a submarine.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('emerald', 'Emerald Cruises', 'emerald', TRUE, FALSE, FALSE, 'midRange', 0.12, 'Switzerland', 'A modern, stylish river cruise and luxury yacht line offering excellent value. Features an innovative pool that transforms into a cinema at night on river ships.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('uniworld', 'Uniworld Boutique River Cruises', 'uniworld', TRUE, FALSE, FALSE, 'luxury', 0.16, 'United States', 'Offers ultra-luxury, boutique river cruises. Each ship is a unique, lavishly designed work of art reflecting the destinations sailed, featuring antique decor and high culinary standards.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('ponant', 'Ponant', 'ponant', FALSE, TRUE, FALSE, 'luxury', 0.15, 'France', 'A French luxury expedition cruise line. Offers small yacht-like ships, polar expeditions in ultra-luxury comfort, French culinary arts (partnered with Ducasse Conseil), and the Blue Eye underwater lounge.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('hurtigruten', 'Hurtigruten', 'hurtigruten', FALSE, TRUE, FALSE, 'midRange', 0.12, 'Norway', 'The global leader in sustainable expedition cruising, sailing Norway''s coast since 1893. Operates hybrid-powered ships to Antarctica, the Arctic, and Greenland with a focus on science and nature.');
INSERT IGNORE INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('windstar', 'Windstar Cruises', 'windstar', FALSE, FALSE, FALSE, 'premium', 0.14, 'United States', 'Operates a fleet of small, masted sailing ships and luxury all-suite motor yachts. Carrying just 148–342 guests, Windstar accesses small harbors where large ships cannot go.');
