-- PostgreSQL seed for Cruises database

CREATE TABLE IF NOT EXISTS cruise_lines (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  river_cruise BOOLEAN,
  expedition_cruise BOOLEAN,
  adults_only BOOLEAN,
  luxury_level VARCHAR(50),
  commission_rate NUMERIC,
  hq_country VARCHAR(100),
  description TEXT
);

INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('royal-caribbean', 'Royal Caribbean International', 'royal-caribbean', FALSE, FALSE, FALSE, 'midRange', 0.12, 'United States', 'Known for building the world''s largest, most innovative cruise ships featuring rock-climbing walls, ice-skating rinks, surf simulators, and Broadway-style shows. Ideal for active families and couples.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('carnival', 'Carnival Cruise Line', 'carnival', FALSE, FALSE, FALSE, 'budget', 0.1, 'United States', 'The "Choose Fun" cruise line, offering high-energy, value-packed ocean cruises with water parks, casual dining, and a festive atmosphere. Great for families, groups, and solo travelers.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('norwegian', 'Norwegian Cruise Line', 'norwegian', FALSE, FALSE, FALSE, 'midRange', 0.12, 'United States', 'Pioneered "Freestyle Cruising" with no set dining times or dress codes. Features impressive entertainment, top-tier restaurants, go-kart racetracks, and dedicated studio cabins for solo travelers.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('msc', 'MSC Cruises', 'msc', FALSE, FALSE, FALSE, 'budget', 0.1, 'Switzerland', 'A European-inspired cruise line offering modern, stylish mega-ships, an international onboard atmosphere, and a premium "ship-within-a-ship" concept with the MSC Yacht Club.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('princess', 'Princess Cruises', 'princess', FALSE, FALSE, FALSE, 'midRange', 0.12, 'United States', 'Famous as the cruise line from "The Love Boat." Princess focuses on destination-rich itineraries, culinary excellence, and technological innovation with the MedallionClass experience.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('celebrity', 'Celebrity Cruises', 'celebrity', FALSE, FALSE, FALSE, 'premium', 0.13, 'United States', 'Offers a "new luxury" experience blending modern design, high-end culinary options, and excellent service. Known for its iconic Lawn Clubs with real grass and Edge-class outward-facing designs.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('holland-america', 'Holland America Line', 'holland-america', FALSE, FALSE, FALSE, 'midRange', 0.12, 'United States', 'A classic, refined cruise line specializing in destination immersion, culinary arts, and live music. Attracts mature couples, multi-generational families, and world cruise travelers.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('disney', 'Disney Cruise Line', 'disney', FALSE, FALSE, FALSE, 'premium', 0.1, 'United States', 'The ultimate family cruise experience combining legendary Disney service, character meet-and-greets, rotational dining, themed deck parties, and dedicated adults-only areas.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('virgin-voyages', 'Virgin Voyages', 'virgin-voyages', FALSE, FALSE, TRUE, 'premium', 0.15, 'United States', 'An adults-only (18+), luxury-casual cruise line. Replaces buffets and dress codes with 20+ specialty restaurants, yacht-inspired design, dynamic fitness classes, and high-energy nightlife.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('cunard', 'Cunard Line', 'cunard', FALSE, FALSE, FALSE, 'premium', 0.12, 'United Kingdom', 'Sophisticated ocean liner travel capturing the golden age of ocean travel. Renowned for transatlantic crossings, formal gala nights, white-glove Afternoon Tea, and royal class service.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('oceania', 'Oceania Cruises', 'oceania', FALSE, FALSE, FALSE, 'premium', 0.14, 'United States', 'Renowned for serving "The Finest Cuisine at Sea," Oceania offers mid-sized, elegant ships that focus on culinary excellence, destination-focused itineraries, and a club-like atmosphere.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('regent-seven-seas', 'Regent Seven Seas Cruises', 'regent-seven-seas', FALSE, FALSE, FALSE, 'luxury', 0.16, 'United States', 'An ultra-luxury, all-inclusive cruise experience. Fares include round-trip flights, unlimited shore excursions, premium drinks, fine dining, Wi-Fi, laundry service, and gratuities.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('silversea', 'Silversea Cruises', 'silversea', FALSE, TRUE, FALSE, 'luxury', 0.16, 'Monaco', 'An ultra-luxury line known for intimate small ships, butler service for every suite, and a robust fleet of luxury expedition ships sailing to the polar regions and Galapagos.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('seabourn', 'Seabourn Cruise Line', 'seabourn', FALSE, TRUE, FALSE, 'luxury', 0.16, 'United States', 'Pioneered ultra-luxury cruising with small, yacht-like ships. Features open bars, Caviar in the Surf beach parties, and partnerships with Chef Thomas Keller.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('azamara', 'Azamara', 'azamara', FALSE, FALSE, FALSE, 'premium', 0.14, 'United States', 'A premium boutique line focusing on Destination Immersion. Offers longer stays, overnights in port, and unique cultural experiences like the AzAmazing Evening.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('viking-ocean', 'Viking Ocean Cruises', 'viking-ocean', FALSE, FALSE, TRUE, 'premium', 0.15, 'Switzerland', 'An adults-only (18+), highly-rated ocean cruise line focusing on history, culture, and science. Free of casinos, children, and hidden fees, with a Nordic design aesthetic.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('viking-river', 'Viking River Cruises', 'viking-river', TRUE, FALSE, TRUE, 'premium', 0.15, 'Switzerland', 'The world''s leading river cruise line, operating a massive fleet of Longships across Europe, Egypt, Asia, and the Mississippi. Focuses on local history and culture.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('amawaterways', 'AmaWaterways', 'amawaterways', TRUE, FALSE, FALSE, 'premium', 0.15, 'United States', 'A premier river cruise line known for active excursions (carrying a fleet of bicycles), award-winning cuisine, Chef''s Table dining, and innovative double-balcony suites.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('avalon', 'Avalon Waterways', 'avalon', TRUE, FALSE, FALSE, 'premium', 0.14, 'United States', 'Known for its "Suite Ships" featuring Panorama Suites with wall-to-wall, floor-to-ceiling windows that open to create a giant Open-Air Balcony. Offers active and discovery cruises.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('scenic', 'Scenic Cruises', 'scenic', TRUE, TRUE, FALSE, 'luxury', 0.16, 'Australia', 'Offers 5-star, truly all-inclusive luxury river cruises in Europe and Asia, and ultra-luxury ocean voyages on the Scenic Eclipse "Discovery Yachts" equipped with helicopters and a submarine.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('emerald', 'Emerald Cruises', 'emerald', TRUE, FALSE, FALSE, 'midRange', 0.12, 'Switzerland', 'A modern, stylish river cruise and luxury yacht line offering excellent value. Features an innovative pool that transforms into a cinema at night on river ships.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('uniworld', 'Uniworld Boutique River Cruises', 'uniworld', TRUE, FALSE, FALSE, 'luxury', 0.16, 'United States', 'Offers ultra-luxury, boutique river cruises. Each ship is a unique, lavishly designed work of art reflecting the destinations sailed, featuring antique decor and high culinary standards.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('ponant', 'Ponant', 'ponant', FALSE, TRUE, FALSE, 'luxury', 0.15, 'France', 'A French luxury expedition cruise line. Offers small yacht-like ships, polar expeditions in ultra-luxury comfort, French culinary arts (partnered with Ducasse Conseil), and the Blue Eye underwater lounge.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('hurtigruten', 'Hurtigruten', 'hurtigruten', FALSE, TRUE, FALSE, 'midRange', 0.12, 'Norway', 'The global leader in sustainable expedition cruising, sailing Norway''s coast since 1893. Operates hybrid-powered ships to Antarctica, the Arctic, and Greenland with a focus on science and nature.') ON CONFLICT (id) DO NOTHING;
INSERT INTO cruise_lines (id, name, slug, river_cruise, expedition_cruise, adults_only, luxury_level, commission_rate, hq_country, description) VALUES ('windstar', 'Windstar Cruises', 'windstar', FALSE, FALSE, FALSE, 'premium', 0.14, 'United States', 'Operates a fleet of small, masted sailing ships and luxury all-suite motor yachts. Carrying just 148–342 guests, Windstar accesses small harbors where large ships cannot go.') ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS ships (
  id VARCHAR(255) PRIMARY KEY,
  cruise_line_id VARCHAR(255),
  name VARCHAR(255),
  tonnage INT,
  passenger_capacity INT,
  crew_size INT,
  launch_year INT
);

INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('icon-of-the-seas', 'royal-caribbean', 'Icon of the Seas', 248663, 5610, 2350, 2024) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('wonder-of-the-seas', 'royal-caribbean', 'Wonder of the Seas', 236857, 5734, 2300, 2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('symphony-of-the-seas', 'royal-caribbean', 'Symphony of the Seas', 228081, 5518, 2200, 2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('odyssey-of-the-seas', 'royal-caribbean', 'Odyssey of the Seas', 169300, 4198, 1550, 2021) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('mariner-of-the-seas', 'royal-caribbean', 'Mariner of the Seas', 138279, 3114, 1180, 2003) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('carnival-jubilee', 'carnival', 'Carnival Jubilee', 183521, 5374, 1735, 2023) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('carnival-celebration', 'carnival', 'Carnival Celebration', 183521, 5374, 1735, 2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('mardi-gras', 'carnival', 'Mardi Gras', 180800, 5282, 1735, 2021) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('carnival-horizon', 'carnival', 'Carnival Horizon', 133500, 3960, 1450, 2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('norwegian-viva', 'norwegian', 'Norwegian Viva', 143535, 3099, 1500, 2023) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('norwegian-prima', 'norwegian', 'Norwegian Prima', 143535, 3099, 1500, 2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('norwegian-encore', 'norwegian', 'Norwegian Encore', 169116, 3998, 1735, 2019) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('norwegian-bliss', 'norwegian', 'Norwegian Bliss', 168028, 4004, 1716, 2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('msc-world-europa', 'msc', 'MSC World Europa', 215863, 5400, 2138, 2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('msc-euribia', 'msc', 'MSC Euribia', 184011, 4838, 1410, 2023) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('msc-seascape', 'msc', 'MSC Seascape', 170400, 4540, 1648, 2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('sun-princess', 'princess', 'Sun Princess', 175500, 4300, 1600, 2024) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('discovery-princess', 'princess', 'Discovery Princess', 145000, 3660, 1346, 2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('enchanted-princess', 'princess', 'Enchanted Princess', 145000, 3660, 1346, 2020) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('celebrity-ascent', 'celebrity', 'Celebrity Ascent', 140600, 3260, 1400, 2023) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('celebrity-beyond', 'celebrity', 'Celebrity Beyond', 140600, 3260, 1400, 2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('celebrity-edge', 'celebrity', 'Celebrity Edge', 130818, 2918, 1320, 2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('celebrity-flora', 'celebrity', 'Celebrity Flora', 5739, 100, 80, 2019) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('rotterdam', 'holland-america', 'Rotterdam', 99800, 2668, 1025, 2021) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('koningsdam', 'holland-america', 'Koningsdam', 99500, 2650, 1025, 2016) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('disney-wish', 'disney', 'Disney Wish', 144000, 2500, 1555, 2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('disney-fantasy', 'disney', 'Disney Fantasy', 129690, 2500, 1450, 2012) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('scarlet-lady', 'virgin-voyages', 'Scarlet Lady', 110000, 2770, 1160, 2020) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('valiant-lady', 'virgin-voyages', 'Valiant Lady', 110000, 2770, 1160, 2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('queen-mary-2', 'cunard', 'Queen Mary 2', 149215, 2691, 1292, 2004) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('queen-anne', 'cunard', 'Queen Anne', 113000, 2996, 1225, 2024) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('oceania-vista', 'oceania', 'Vista', 67000, 1200, 800, 2023) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('seven-seas-grandeur', 'regent-seven-seas', 'Seven Seas Grandeur', 55500, 746, 548, 2023) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('seven-seas-explorer', 'regent-seven-seas', 'Seven Seas Explorer', 56000, 750, 552, 2016) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('silver-nova', 'silversea', 'Silver Nova', 54700, 728, 544, 2023) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('silver-origin', 'silversea', 'Silver Origin', 5800, 100, 90, 2020) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('seabourn-ovation', 'seabourn', 'Seabourn Ovation', 40350, 600, 450, 2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('seabourn-venture', 'seabourn', 'Seabourn Venture', 23000, 264, 120, 2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('azamara-onward', 'azamara', 'Azamara Onward', 30277, 684, 408, 1999) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('viking-star', 'viking-ocean', 'Viking Star', 47800, 930, 550, 2015) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('viking-sky', 'viking-ocean', 'Viking Sky', 47800, 930, 550, 2017) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('viking-alsvid', 'viking-river', 'Viking Alsvid', 5000, 190, 50, 2014) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('viking-kara', 'viking-river', 'Viking Kara', 5000, 190, 50, 2014) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('amamagna', 'amawaterways', 'AmaMagna', 8000, 196, 70, 2019) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('amakristina', 'amawaterways', 'AmaKristina', 4000, 156, 51, 2017) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('avalon-envision', 'avalon', 'Avalon Envision', 4000, 166, 47, 2019) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('scenic-eclipse', 'scenic', 'Scenic Eclipse', 17085, 228, 176, 2019) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('emerald-azzurra', 'emerald', 'Emerald Azzurra', 5300, 100, 64, 2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('ss-joie-de-vivre', 'uniworld', 'S.S. Joie de Vivre', 3500, 128, 54, 2017) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('le-commandant-charcot', 'ponant', 'Le Commandant Charcot', 31283, 270, 187, 2021) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('ms-roald-amundsen', 'hurtigruten', 'MS Roald Amundsen', 20889, 530, 150, 2019) ON CONFLICT (id) DO NOTHING;
INSERT INTO ships (id, cruise_line_id, name, tonnage, passenger_capacity, crew_size, launch_year) VALUES ('wind-surf', 'windstar', 'Wind Surf', 14745, 342, 210, 1989) ON CONFLICT (id) DO NOTHING;
